# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::SessionUpdate::AgentMessageChunk
  # @dynamic content
  attr_reader :content #: ACP::Types::ContentBlock::t

  # @dynamic message_id
  attr_reader :message_id #: String?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs content: ACP::Types::ContentBlock::t
  # @rbs message_id: String?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(content:, message_id: nil, meta: nil)
    @content = content
    @message_id = message_id
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::SessionUpdate::AgentMessageChunk
  def self.from_h(hash)
    new(
      content: ACP::Types::Check.object(ACP::Types::Check.key(hash, 'content'), 'content', ACP::Types::ContentBlock),
      message_id: ACP::Types::Check.string(hash['messageId'], 'messageId', allow_nil: true),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'sessionUpdate' => 'agent_message_chunk',
      'content' => content.to_h,
      'messageId' => message_id,
      '_meta' => meta
    }.compact
  end
end
