# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::SessionUpdate::AvailableCommandsUpdate
  # @dynamic available_commands
  attr_reader :available_commands #: Array[ACP::Types::AvailableCommand]

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs available_commands: Array[ACP::Types::AvailableCommand]
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(available_commands:, meta: nil)
    @available_commands = available_commands
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::SessionUpdate::AvailableCommandsUpdate
  def self.from_h(hash)
    new(
      available_commands: hash.fetch('availableCommands').map { |item| ACP::Types::AvailableCommand.from_h(item) },
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'sessionUpdate' => 'available_commands_update',
      'availableCommands' => available_commands.map(&:to_h),
      '_meta' => meta
    }.compact
  end
end
