# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::SessionUpdate::Plan
  # @dynamic entries
  attr_reader :entries #: Array[ACP::Types::PlanEntry]

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs entries: Array[ACP::Types::PlanEntry]
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(entries:, meta: nil)
    @entries = entries
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::SessionUpdate::Plan
  def self.from_h(hash)
    new(entries: hash.fetch('entries').map { |item| ACP::Types::PlanEntry.from_h(item) }, meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'sessionUpdate' => 'plan', 'entries' => entries.map(&:to_h), '_meta' => meta }.compact
  end
end
