# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::SessionUpdate::UsageUpdate
  # @dynamic used
  attr_reader :used #: Integer

  # @dynamic size
  attr_reader :size #: Integer

  # @dynamic cost
  attr_reader :cost #: ACP::Types::Cost?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs used: Integer
  # @rbs size: Integer
  # @rbs cost: ACP::Types::Cost?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(used:, size:, cost: nil, meta: nil)
    @used = used
    @size = size
    @cost = cost
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::SessionUpdate::UsageUpdate
  def self.from_h(hash)
    new(
      used: hash.fetch('used'),
      size: hash.fetch('size'),
      cost: hash['cost']&.then { |value| ACP::Types::Cost.from_h(value) },
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'sessionUpdate' => 'usage_update', 'used' => used, 'size' => size, 'cost' => cost&.to_h, '_meta' => meta }.compact
  end
end
