# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::AgentCapabilities
  # @dynamic load_session
  attr_reader :load_session #: bool?

  # @dynamic prompt_capabilities
  attr_reader :prompt_capabilities #: ACP::Types::PromptCapabilities?

  # @dynamic mcp_capabilities
  attr_reader :mcp_capabilities #: ACP::Types::Unstable::McpCapabilities?

  # @dynamic session_capabilities
  attr_reader :session_capabilities #: ACP::Types::Unstable::SessionCapabilities?

  # @dynamic auth
  attr_reader :auth #: ACP::Types::AgentAuthCapabilities?

  # @dynamic providers
  attr_reader :providers #: ACP::Types::Unstable::ProvidersCapabilities?

  # @dynamic nes
  attr_reader :nes #: ACP::Types::Unstable::NesCapabilities?

  # @dynamic position_encoding
  attr_reader :position_encoding #: String?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs load_session: bool?
  # @rbs prompt_capabilities: ACP::Types::PromptCapabilities?
  # @rbs mcp_capabilities: ACP::Types::Unstable::McpCapabilities?
  # @rbs session_capabilities: ACP::Types::Unstable::SessionCapabilities?
  # @rbs auth: ACP::Types::AgentAuthCapabilities?
  # @rbs providers: ACP::Types::Unstable::ProvidersCapabilities?
  # @rbs nes: ACP::Types::Unstable::NesCapabilities?
  # @rbs position_encoding: String?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(
    load_session: nil,
    prompt_capabilities: nil,
    mcp_capabilities: nil,
    session_capabilities: nil,
    auth: nil,
    providers: nil,
    nes: nil,
    position_encoding: nil,
    meta: nil
  )
    @load_session = load_session
    @prompt_capabilities = prompt_capabilities
    @mcp_capabilities = mcp_capabilities
    @session_capabilities = session_capabilities
    @auth = auth
    @providers = providers
    @nes = nes
    @position_encoding = position_encoding
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::AgentCapabilities
  def self.from_h(hash)
    new(
      load_session: ACP::Types::Check.boolean(hash['loadSession'], 'loadSession', allow_nil: true),
      prompt_capabilities: ACP::Types::Check.object(
        hash['promptCapabilities'],
        'promptCapabilities',
        ACP::Types::PromptCapabilities,
        allow_nil: true
      ),
      mcp_capabilities: ACP::Types::Check.object(
        hash['mcpCapabilities'],
        'mcpCapabilities',
        ACP::Types::Unstable::McpCapabilities,
        allow_nil: true
      ),
      session_capabilities: ACP::Types::Check.object(
        hash['sessionCapabilities'],
        'sessionCapabilities',
        ACP::Types::Unstable::SessionCapabilities,
        allow_nil: true
      ),
      auth: ACP::Types::Check.object(hash['auth'], 'auth', ACP::Types::AgentAuthCapabilities, allow_nil: true),
      providers: ACP::Types::Check.object(
        hash['providers'],
        'providers',
        ACP::Types::Unstable::ProvidersCapabilities,
        allow_nil: true
      ),
      nes: ACP::Types::Check.object(hash['nes'], 'nes', ACP::Types::Unstable::NesCapabilities, allow_nil: true),
      position_encoding: ACP::Types::Check.enum(
        hash['positionEncoding'],
        'positionEncoding',
        %w[utf-16 utf-32 utf-8],
        allow_nil: true
      ),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'loadSession' => load_session,
      'promptCapabilities' => prompt_capabilities&.to_h,
      'mcpCapabilities' => mcp_capabilities&.to_h,
      'sessionCapabilities' => session_capabilities&.to_h,
      'auth' => auth&.to_h,
      'providers' => providers&.to_h,
      'nes' => nes&.to_h,
      'positionEncoding' => position_encoding,
      '_meta' => meta
    }.compact
  end
end
