# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::ClientCapabilities
  # @dynamic fs
  attr_reader :fs #: ACP::Types::FileSystemCapabilities?

  # @dynamic terminal
  attr_reader :terminal #: bool?

  # @dynamic session
  attr_reader :session #: ACP::Types::Unstable::ClientSessionCapabilities?

  # @dynamic subagents
  attr_reader :subagents #: ACP::Types::Unstable::SubagentCapabilities?

  # @dynamic plan
  attr_reader :plan #: ACP::Types::Unstable::PlanCapabilities?

  # @dynamic auth
  attr_reader :auth #: ACP::Types::AuthCapabilities?

  # @dynamic elicitation
  attr_reader :elicitation #: ACP::Types::ElicitationCapabilities?

  # @dynamic nes
  attr_reader :nes #: ACP::Types::Unstable::ClientNesCapabilities?

  # @dynamic position_encodings
  attr_reader :position_encodings #: Array[String]?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs fs: ACP::Types::FileSystemCapabilities?
  # @rbs terminal: bool?
  # @rbs session: ACP::Types::Unstable::ClientSessionCapabilities?
  # @rbs subagents: ACP::Types::Unstable::SubagentCapabilities?
  # @rbs plan: ACP::Types::Unstable::PlanCapabilities?
  # @rbs auth: ACP::Types::AuthCapabilities?
  # @rbs elicitation: ACP::Types::ElicitationCapabilities?
  # @rbs nes: ACP::Types::Unstable::ClientNesCapabilities?
  # @rbs position_encodings: Array[String]?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(
    fs: nil,
    terminal: nil,
    session: nil,
    subagents: nil,
    plan: nil,
    auth: nil,
    elicitation: nil,
    nes: nil,
    position_encodings: nil,
    meta: nil
  )
    @fs = fs
    @terminal = terminal
    @session = session
    @subagents = subagents
    @plan = plan
    @auth = auth
    @elicitation = elicitation
    @nes = nes
    @position_encodings = position_encodings
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::ClientCapabilities
  def self.from_h(hash)
    position_encodings = ACP::Types::Check.array(
      hash['positionEncodings'],
      'positionEncodings',
      allow_nil: true
    ) do |item, path|
      ACP::Types::Check.enum(item, path, %w[utf-16 utf-32 utf-8])
    end
    new(
      fs: ACP::Types::Check.object(hash['fs'], 'fs', ACP::Types::FileSystemCapabilities, allow_nil: true),
      terminal: ACP::Types::Check.boolean(hash['terminal'], 'terminal', allow_nil: true),
      session: ACP::Types::Check.object(
        hash['session'],
        'session',
        ACP::Types::Unstable::ClientSessionCapabilities,
        allow_nil: true
      ),
      subagents: ACP::Types::Check.object(
        hash['subagents'],
        'subagents',
        ACP::Types::Unstable::SubagentCapabilities,
        allow_nil: true
      ),
      plan: ACP::Types::Check.object(hash['plan'], 'plan', ACP::Types::Unstable::PlanCapabilities, allow_nil: true),
      auth: ACP::Types::Check.object(hash['auth'], 'auth', ACP::Types::AuthCapabilities, allow_nil: true),
      elicitation: ACP::Types::Check.object(
        hash['elicitation'],
        'elicitation',
        ACP::Types::ElicitationCapabilities,
        allow_nil: true
      ),
      nes: ACP::Types::Check.object(hash['nes'], 'nes', ACP::Types::Unstable::ClientNesCapabilities, allow_nil: true),
      position_encodings:,
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'fs' => fs&.to_h,
      'terminal' => terminal,
      'session' => session&.to_h,
      'subagents' => subagents&.to_h,
      'plan' => plan&.to_h,
      'auth' => auth&.to_h,
      'elicitation' => elicitation&.to_h,
      'nes' => nes&.to_h,
      'positionEncodings' => position_encodings,
      '_meta' => meta
    }.compact
  end
end
