# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::ClientSessionCapabilities
  # @dynamic compaction
  attr_reader :compaction #: Hash[String, untyped]?

  # @dynamic config_options
  attr_reader :config_options #: ACP::Types::SessionConfigOptionsCapabilities?

  # @dynamic notices
  attr_reader :notices #: Hash[String, untyped]?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs compaction: Hash[String, untyped]?
  # @rbs config_options: ACP::Types::SessionConfigOptionsCapabilities?
  # @rbs notices: Hash[String, untyped]?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(compaction: nil, config_options: nil, notices: nil, meta: nil)
    @compaction = compaction
    @config_options = config_options
    @notices = notices
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::ClientSessionCapabilities
  def self.from_h(hash)
    new(
      compaction: hash['compaction'],
      config_options: ACP::Types::Check.object(
        hash['configOptions'],
        'configOptions',
        ACP::Types::SessionConfigOptionsCapabilities,
        allow_nil: true
      ),
      notices: hash['notices'],
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'compaction' => compaction,
      'configOptions' => config_options&.to_h,
      'notices' => notices,
      '_meta' => meta
    }.compact
  end
end
