# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::ClientNesCapabilities
  # @dynamic jump
  attr_reader :jump #: ACP::Types::Unstable::NesJumpCapabilities?

  # @dynamic rename
  attr_reader :rename #: ACP::Types::Unstable::NesRenameCapabilities?

  # @dynamic search_and_replace
  attr_reader :search_and_replace #: ACP::Types::Unstable::NesSearchAndReplaceCapabilities?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs jump: ACP::Types::Unstable::NesJumpCapabilities?
  # @rbs rename: ACP::Types::Unstable::NesRenameCapabilities?
  # @rbs search_and_replace: ACP::Types::Unstable::NesSearchAndReplaceCapabilities?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(jump: nil, rename: nil, search_and_replace: nil, meta: nil)
    @jump = jump
    @rename = rename
    @search_and_replace = search_and_replace
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::ClientNesCapabilities
  def self.from_h(hash)
    new(
      jump: ACP::Types::Check.object(hash['jump'], 'jump', ACP::Types::Unstable::NesJumpCapabilities, allow_nil: true),
      rename: ACP::Types::Check.object(
        hash['rename'],
        'rename',
        ACP::Types::Unstable::NesRenameCapabilities,
        allow_nil: true
      ),
      search_and_replace: ACP::Types::Check.object(
        hash['searchAndReplace'],
        'searchAndReplace',
        ACP::Types::Unstable::NesSearchAndReplaceCapabilities,
        allow_nil: true
      ),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'jump' => jump&.to_h,
      'rename' => rename&.to_h,
      'searchAndReplace' => search_and_replace&.to_h,
      '_meta' => meta
    }.compact
  end
end
