# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::CompactionSummaryChunk
  # @dynamic compaction_id
  attr_reader :compaction_id #: String

  # @dynamic content
  attr_reader :content #: ACP::Types::ContentBlock::t

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs compaction_id: String
  # @rbs content: ACP::Types::ContentBlock::t
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(compaction_id:, content:, meta: nil)
    @compaction_id = compaction_id
    @content = content
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::CompactionSummaryChunk
  def self.from_h(hash)
    new(
      compaction_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'compactionId'), 'compactionId'),
      content: ACP::Types::Check.object(ACP::Types::Check.key(hash, 'content'), 'content', ACP::Types::ContentBlock),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'compactionId' => compaction_id, 'content' => content.to_h, '_meta' => meta }.compact
  end
end
