# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::DidFocusDocumentNotification
  # @dynamic session_id
  attr_reader :session_id #: String

  # @dynamic uri
  attr_reader :uri #: String

  # @dynamic version
  attr_reader :version #: Integer

  # @dynamic position
  attr_reader :position #: ACP::Types::Unstable::Position

  # @dynamic visible_range
  attr_reader :visible_range #: ACP::Types::Unstable::Range

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs session_id: String
  # @rbs uri: String
  # @rbs version: Integer
  # @rbs position: ACP::Types::Unstable::Position
  # @rbs visible_range: ACP::Types::Unstable::Range
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(session_id:, uri:, version:, position:, visible_range:, meta: nil)
    @session_id = session_id
    @uri = uri
    @version = version
    @position = position
    @visible_range = visible_range
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::DidFocusDocumentNotification
  def self.from_h(hash)
    new(
      session_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'sessionId'), 'sessionId'),
      uri: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'uri'), 'uri'),
      version: ACP::Types::Check.integer(ACP::Types::Check.key(hash, 'version'), 'version'),
      position: ACP::Types::Check.object(
        ACP::Types::Check.key(hash, 'position'),
        'position',
        ACP::Types::Unstable::Position
      ),
      visible_range: ACP::Types::Check.object(
        ACP::Types::Check.key(hash, 'visibleRange'),
        'visibleRange',
        ACP::Types::Unstable::Range
      ),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'sessionId' => session_id,
      'uri' => uri,
      'version' => version,
      'position' => position.to_h,
      'visibleRange' => visible_range.to_h,
      '_meta' => meta
    }.compact
  end
end
