# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::DidOpenDocumentNotification
  # @dynamic session_id
  attr_reader :session_id #: String

  # @dynamic uri
  attr_reader :uri #: String

  # @dynamic language_id
  attr_reader :language_id #: String

  # @dynamic version
  attr_reader :version #: Integer

  # @dynamic text
  attr_reader :text #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs session_id: String
  # @rbs uri: String
  # @rbs language_id: String
  # @rbs version: Integer
  # @rbs text: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(session_id:, uri:, language_id:, version:, text:, meta: nil)
    @session_id = session_id
    @uri = uri
    @language_id = language_id
    @version = version
    @text = text
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::DidOpenDocumentNotification
  def self.from_h(hash)
    new(
      session_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'sessionId'), 'sessionId'),
      uri: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'uri'), 'uri'),
      language_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'languageId'), 'languageId'),
      version: ACP::Types::Check.integer(ACP::Types::Check.key(hash, 'version'), 'version'),
      text: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'text'), 'text'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'sessionId' => session_id,
      'uri' => uri,
      'languageId' => language_id,
      'version' => version,
      'text' => text,
      '_meta' => meta
    }.compact
  end
end
