# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::DidChangeDocumentNotification
  # @dynamic session_id
  attr_reader :session_id #: String

  # @dynamic uri
  attr_reader :uri #: String

  # @dynamic version
  attr_reader :version #: Integer

  # @dynamic content_changes
  attr_reader :content_changes #: Array[ACP::Types::Unstable::TextDocumentContentChangeEvent]

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs session_id: String
  # @rbs uri: String
  # @rbs version: Integer
  # @rbs content_changes: Array[ACP::Types::Unstable::TextDocumentContentChangeEvent]
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(session_id:, uri:, version:, content_changes:, meta: nil)
    @session_id = session_id
    @uri = uri
    @version = version
    @content_changes = content_changes
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::DidChangeDocumentNotification
  def self.from_h(hash)
    content_changes = ACP::Types::Check.array(
      ACP::Types::Check.key(hash, 'contentChanges'),
      'contentChanges'
    ) do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::Unstable::TextDocumentContentChangeEvent)
    end
    new(
      session_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'sessionId'), 'sessionId'),
      uri: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'uri'), 'uri'),
      version: ACP::Types::Check.integer(ACP::Types::Check.key(hash, 'version'), 'version'),
      content_changes:,
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'sessionId' => session_id,
      'uri' => uri,
      'version' => version,
      'contentChanges' => content_changes.map(&:to_h),
      '_meta' => meta
    }.compact
  end
end
