# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::DisableProviderRequest
  # @dynamic provider_id
  attr_reader :provider_id #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs provider_id: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(provider_id:, meta: nil)
    @provider_id = provider_id
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::DisableProviderRequest
  def self.from_h(hash)
    new(
      provider_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'providerId'), 'providerId'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'providerId' => provider_id, '_meta' => meta }.compact
  end
end
