# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::ForkSessionResponse
  # @dynamic session_id
  attr_reader :session_id #: String

  # @dynamic modes
  attr_reader :modes #: ACP::Types::SessionModeState?

  # @dynamic config_options
  attr_reader :config_options #: Array[ACP::Types::SessionConfigOption]?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs session_id: String
  # @rbs modes: ACP::Types::SessionModeState?
  # @rbs config_options: Array[ACP::Types::SessionConfigOption]?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(session_id:, modes: nil, config_options: nil, meta: nil)
    @session_id = session_id
    @modes = modes
    @config_options = config_options
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::ForkSessionResponse
  def self.from_h(hash)
    config_options = ACP::Types::Check.array(hash['configOptions'], 'configOptions', allow_nil: true) do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::SessionConfigOption)
    end
    new(
      session_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'sessionId'), 'sessionId'),
      modes: ACP::Types::Check.object(hash['modes'], 'modes', ACP::Types::SessionModeState, allow_nil: true),
      config_options:,
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'sessionId' => session_id,
      'modes' => modes&.to_h,
      'configOptions' => config_options&.map(&:to_h),
      '_meta' => meta
    }.compact
  end
end
