# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::IdleStateUpdate
  # @dynamic stop_reason
  attr_reader :stop_reason #: String?

  # @dynamic usage
  attr_reader :usage #: ACP::Types::Unstable::Usage?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs stop_reason: String?
  # @rbs usage: ACP::Types::Unstable::Usage?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(stop_reason: nil, usage: nil, meta: nil)
    @stop_reason = stop_reason
    @usage = usage
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::IdleStateUpdate
  def self.from_h(hash)
    new(
      stop_reason: ACP::Types::Check.enum(
        hash['stopReason'],
        'stopReason',
        %w[end_turn max_tokens max_turn_requests refusal cancelled],
        allow_nil: true
      ),
      usage: ACP::Types::Check.object(hash['usage'], 'usage', ACP::Types::Unstable::Usage, allow_nil: true),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'stopReason' => stop_reason, 'usage' => usage&.to_h, '_meta' => meta }.compact
  end
end
