# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::ListProvidersRequest
  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(meta: nil)
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::ListProvidersRequest
  def self.from_h(hash)
    new(meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { '_meta' => meta }.compact
  end
end
