# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::ListProvidersResponse
  # @dynamic providers
  attr_reader :providers #: Array[ACP::Types::Unstable::ProviderInfo]

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs providers: Array[ACP::Types::Unstable::ProviderInfo]
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(providers:, meta: nil)
    @providers = providers
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::ListProvidersResponse
  def self.from_h(hash)
    providers = ACP::Types::Check.array(ACP::Types::Check.key(hash, 'providers'), 'providers') do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::Unstable::ProviderInfo)
    end
    new(providers:, meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'providers' => providers.map(&:to_h), '_meta' => meta }.compact
  end
end
