# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

module ACP::Types::Unstable::McpServer
  # @rbs!
  #   type t = ACP::Types::Unstable::McpServer::Http
  #          | ACP::Types::Unstable::McpServer::Sse
  #          | ACP::Types::Unstable::McpServer::Acp
  #          | ACP::Types::McpServerStdio
  #          | Hash[String, untyped]

  # @rbs hash: Hash[String, untyped]
  # @rbs return: t
  def self.from_h(hash)
    case hash['type']
    when 'http' then ACP::Types::Unstable::McpServer::Http.from_h(hash)
    when 'sse' then ACP::Types::Unstable::McpServer::Sse.from_h(hash)
    when 'acp' then ACP::Types::Unstable::McpServer::Acp.from_h(hash)
    when nil then ACP::Types::McpServerStdio.from_h(hash)
    else hash
    end
  end
end
