# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::McpServerAcp
  # @dynamic name
  attr_reader :name #: String

  # @dynamic server_id
  attr_reader :server_id #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs name: String
  # @rbs server_id: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(name:, server_id:, meta: nil)
    @name = name
    @server_id = server_id
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::McpServerAcp
  def self.from_h(hash)
    new(
      name: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'name'), 'name'),
      server_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'serverId'), 'serverId'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'name' => name, 'serverId' => server_id, '_meta' => meta }.compact
  end
end
