# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::McpCapabilities
  # @dynamic http
  attr_reader :http #: bool?

  # @dynamic sse
  attr_reader :sse #: bool?

  # @dynamic acp
  attr_reader :acp #: bool?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs http: bool?
  # @rbs sse: bool?
  # @rbs acp: bool?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(http: nil, sse: nil, acp: nil, meta: nil)
    @http = http
    @sse = sse
    @acp = acp
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::McpCapabilities
  def self.from_h(hash)
    new(
      http: ACP::Types::Check.boolean(hash['http'], 'http', allow_nil: true),
      sse: ACP::Types::Check.boolean(hash['sse'], 'sse', allow_nil: true),
      acp: ACP::Types::Check.boolean(hash['acp'], 'acp', allow_nil: true),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'http' => http, 'sse' => sse, 'acp' => acp, '_meta' => meta }.compact
  end
end
