# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::McpError
  # @dynamic code
  attr_reader :code #: Integer

  # @dynamic message
  attr_reader :message #: String

  # @dynamic data
  attr_reader :data #: untyped

  # @rbs code: Integer
  # @rbs message: String
  # @rbs data: untyped
  # @rbs return: void
  def initialize(code:, message:, data: nil)
    @code = code
    @message = message
    @data = data
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::McpError
  def self.from_h(hash)
    new(
      code: ACP::Types::Check.integer(ACP::Types::Check.key(hash, 'code'), 'code'),
      message: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'message'), 'message'),
      data: hash['data']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'code' => code, 'message' => message, 'data' => data }.compact
  end
end
