# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

module ACP::Types::Unstable::MessageMcpResponse
  # @rbs!
  #   type t = ACP::Types::Unstable::MessageMcpResponse::Result
  #          | ACP::Types::Unstable::MessageMcpResponse::Error
  #          | Hash[String, untyped]

  # @rbs hash: Hash[String, untyped]
  # @rbs return: t
  def self.from_h(hash)
    if hash.key?('result')
      ACP::Types::Unstable::MessageMcpResponse::Result.from_h(hash)
    elsif hash.key?('error')
      ACP::Types::Unstable::MessageMcpResponse::Error.from_h(hash)
    else
      hash
    end
  end
end
