# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::MessageMcpRequest
  # @dynamic server_id
  attr_reader :server_id #: String

  # @dynamic request_id
  attr_reader :request_id #: String

  # @dynamic method
  attr_reader :method #: String

  # @dynamic params
  attr_reader :params #: Hash[String, untyped]?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs server_id: String
  # @rbs request_id: String
  # @rbs method: String
  # @rbs params: Hash[String, untyped]?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(server_id:, request_id:, method:, params: nil, meta: nil)
    @server_id = server_id
    @request_id = request_id
    @method = method
    @params = params
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::MessageMcpRequest
  def self.from_h(hash)
    new(
      server_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'serverId'), 'serverId'),
      request_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'requestId'), 'requestId'),
      method: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'method'), 'method'),
      params: hash['params'],
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'serverId' => server_id,
      'requestId' => request_id,
      'method' => method,
      'params' => params,
      '_meta' => meta
    }.compact
  end
end
