# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::NesRenameSuggestion
  # @dynamic id
  attr_reader :id #: String

  # @dynamic uri
  attr_reader :uri #: String

  # @dynamic position
  attr_reader :position #: ACP::Types::Unstable::Position

  # @dynamic new_name
  attr_reader :new_name #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs id: String
  # @rbs uri: String
  # @rbs position: ACP::Types::Unstable::Position
  # @rbs new_name: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(id:, uri:, position:, new_name:, meta: nil)
    @id = id
    @uri = uri
    @position = position
    @new_name = new_name
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::NesRenameSuggestion
  def self.from_h(hash)
    new(
      id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'id'), 'id'),
      uri: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'uri'), 'uri'),
      position: ACP::Types::Check.object(
        ACP::Types::Check.key(hash, 'position'),
        'position',
        ACP::Types::Unstable::Position
      ),
      new_name: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'newName'), 'newName'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'id' => id, 'uri' => uri, 'position' => position.to_h, 'newName' => new_name, '_meta' => meta }.compact
  end
end
