# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::NesOpenFile
  # @dynamic uri
  attr_reader :uri #: String

  # @dynamic language_id
  attr_reader :language_id #: String

  # @dynamic visible_range
  attr_reader :visible_range #: ACP::Types::Unstable::Range?

  # @dynamic last_focused_ms
  attr_reader :last_focused_ms #: Integer?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs uri: String
  # @rbs language_id: String
  # @rbs visible_range: ACP::Types::Unstable::Range?
  # @rbs last_focused_ms: Integer?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(uri:, language_id:, visible_range: nil, last_focused_ms: nil, meta: nil)
    @uri = uri
    @language_id = language_id
    @visible_range = visible_range
    @last_focused_ms = last_focused_ms
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::NesOpenFile
  def self.from_h(hash)
    new(
      uri: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'uri'), 'uri'),
      language_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'languageId'), 'languageId'),
      visible_range: ACP::Types::Check.object(
        hash['visibleRange'],
        'visibleRange',
        ACP::Types::Unstable::Range,
        allow_nil: true
      ),
      last_focused_ms: ACP::Types::Check.integer(hash['lastFocusedMs'], 'lastFocusedMs', min: 0, allow_nil: true),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'uri' => uri,
      'languageId' => language_id,
      'visibleRange' => visible_range&.to_h,
      'lastFocusedMs' => last_focused_ms,
      '_meta' => meta
    }.compact
  end
end
