# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::NesDocumentDidChangeCapabilities
  # @dynamic sync_kind
  attr_reader :sync_kind #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs sync_kind: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(sync_kind:, meta: nil)
    @sync_kind = sync_kind
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::NesDocumentDidChangeCapabilities
  def self.from_h(hash)
    new(
      sync_kind: ACP::Types::Check.enum(ACP::Types::Check.key(hash, 'syncKind'), 'syncKind', %w[full incremental]),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'syncKind' => sync_kind, '_meta' => meta }.compact
  end
end
