# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::NesEventCapabilities
  # @dynamic document
  attr_reader :document #: ACP::Types::Unstable::NesDocumentEventCapabilities?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs document: ACP::Types::Unstable::NesDocumentEventCapabilities?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(document: nil, meta: nil)
    @document = document
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::NesEventCapabilities
  def self.from_h(hash)
    new(
      document: ACP::Types::Check.object(
        hash['document'],
        'document',
        ACP::Types::Unstable::NesDocumentEventCapabilities,
        allow_nil: true
      ),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'document' => document&.to_h, '_meta' => meta }.compact
  end
end
