# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

module ACP::Types::Unstable::NesDiagnosticSeverity
  ERROR = 'error'
  WARNING = 'warning'
  INFORMATION = 'information'
  HINT = 'hint'
end
