# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::NesCapabilities
  # @dynamic events
  attr_reader :events #: ACP::Types::Unstable::NesEventCapabilities?

  # @dynamic context
  attr_reader :context #: ACP::Types::Unstable::NesContextCapabilities?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs events: ACP::Types::Unstable::NesEventCapabilities?
  # @rbs context: ACP::Types::Unstable::NesContextCapabilities?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(events: nil, context: nil, meta: nil)
    @events = events
    @context = context
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::NesCapabilities
  def self.from_h(hash)
    new(
      events: ACP::Types::Check.object(
        hash['events'],
        'events',
        ACP::Types::Unstable::NesEventCapabilities,
        allow_nil: true
      ),
      context: ACP::Types::Check.object(
        hash['context'],
        'context',
        ACP::Types::Unstable::NesContextCapabilities,
        allow_nil: true
      ),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'events' => events&.to_h, 'context' => context&.to_h, '_meta' => meta }.compact
  end
end
