# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::NesUserAction
  # @dynamic action
  attr_reader :action #: String

  # @dynamic uri
  attr_reader :uri #: String

  # @dynamic position
  attr_reader :position #: ACP::Types::Unstable::Position

  # @dynamic timestamp_ms
  attr_reader :timestamp_ms #: Integer

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs action: String
  # @rbs uri: String
  # @rbs position: ACP::Types::Unstable::Position
  # @rbs timestamp_ms: Integer
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(action:, uri:, position:, timestamp_ms:, meta: nil)
    @action = action
    @uri = uri
    @position = position
    @timestamp_ms = timestamp_ms
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::NesUserAction
  def self.from_h(hash)
    new(
      action: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'action'), 'action'),
      uri: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'uri'), 'uri'),
      position: ACP::Types::Check.object(
        ACP::Types::Check.key(hash, 'position'),
        'position',
        ACP::Types::Unstable::Position
      ),
      timestamp_ms: ACP::Types::Check.integer(ACP::Types::Check.key(hash, 'timestampMs'), 'timestampMs', min: 0),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'action' => action,
      'uri' => uri,
      'position' => position.to_h,
      'timestampMs' => timestamp_ms,
      '_meta' => meta
    }.compact
  end
end
