# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::NesSuggestContext
  # @dynamic recent_files
  attr_reader :recent_files #: Array[ACP::Types::Unstable::NesRecentFile]?

  # @dynamic related_snippets
  attr_reader :related_snippets #: Array[ACP::Types::Unstable::NesRelatedSnippet]?

  # @dynamic edit_history
  attr_reader :edit_history #: Array[ACP::Types::Unstable::NesEditHistoryEntry]?

  # @dynamic user_actions
  attr_reader :user_actions #: Array[ACP::Types::Unstable::NesUserAction]?

  # @dynamic open_files
  attr_reader :open_files #: Array[ACP::Types::Unstable::NesOpenFile]?

  # @dynamic diagnostics
  attr_reader :diagnostics #: Array[ACP::Types::Unstable::NesDiagnostic]?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs recent_files: Array[ACP::Types::Unstable::NesRecentFile]?
  # @rbs related_snippets: Array[ACP::Types::Unstable::NesRelatedSnippet]?
  # @rbs edit_history: Array[ACP::Types::Unstable::NesEditHistoryEntry]?
  # @rbs user_actions: Array[ACP::Types::Unstable::NesUserAction]?
  # @rbs open_files: Array[ACP::Types::Unstable::NesOpenFile]?
  # @rbs diagnostics: Array[ACP::Types::Unstable::NesDiagnostic]?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(
    recent_files: nil,
    related_snippets: nil,
    edit_history: nil,
    user_actions: nil,
    open_files: nil,
    diagnostics: nil,
    meta: nil
  )
    @recent_files = recent_files
    @related_snippets = related_snippets
    @edit_history = edit_history
    @user_actions = user_actions
    @open_files = open_files
    @diagnostics = diagnostics
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::NesSuggestContext
  def self.from_h(hash)
    recent_files = ACP::Types::Check.array(hash['recentFiles'], 'recentFiles', allow_nil: true) do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::Unstable::NesRecentFile)
    end
    related_snippets = ACP::Types::Check.array(
      hash['relatedSnippets'],
      'relatedSnippets',
      allow_nil: true
    ) do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::Unstable::NesRelatedSnippet)
    end
    edit_history = ACP::Types::Check.array(hash['editHistory'], 'editHistory', allow_nil: true) do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::Unstable::NesEditHistoryEntry)
    end
    user_actions = ACP::Types::Check.array(hash['userActions'], 'userActions', allow_nil: true) do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::Unstable::NesUserAction)
    end
    open_files = ACP::Types::Check.array(hash['openFiles'], 'openFiles', allow_nil: true) do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::Unstable::NesOpenFile)
    end
    diagnostics = ACP::Types::Check.array(hash['diagnostics'], 'diagnostics', allow_nil: true) do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::Unstable::NesDiagnostic)
    end
    new(recent_files:, related_snippets:, edit_history:, user_actions:, open_files:, diagnostics:, meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'recentFiles' => recent_files&.map(&:to_h),
      'relatedSnippets' => related_snippets&.map(&:to_h),
      'editHistory' => edit_history&.map(&:to_h),
      'userActions' => user_actions&.map(&:to_h),
      'openFiles' => open_files&.map(&:to_h),
      'diagnostics' => diagnostics&.map(&:to_h),
      '_meta' => meta
    }.compact
  end
end
