# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::NesRepository
  # @dynamic name
  attr_reader :name #: String

  # @dynamic owner
  attr_reader :owner #: String

  # @dynamic remote_url
  attr_reader :remote_url #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs name: String
  # @rbs owner: String
  # @rbs remote_url: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(name:, owner:, remote_url:, meta: nil)
    @name = name
    @owner = owner
    @remote_url = remote_url
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::NesRepository
  def self.from_h(hash)
    new(
      name: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'name'), 'name'),
      owner: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'owner'), 'owner'),
      remote_url: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'remoteUrl'), 'remoteUrl'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'name' => name, 'owner' => owner, 'remoteUrl' => remote_url, '_meta' => meta }.compact
  end
end
