# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::NesEditHistoryCapabilities
  # @dynamic max_count
  attr_reader :max_count #: Integer?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs max_count: Integer?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(max_count: nil, meta: nil)
    @max_count = max_count
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::NesEditHistoryCapabilities
  def self.from_h(hash)
    new(
      max_count: ACP::Types::Check.integer(hash['maxCount'], 'maxCount', min: 0, allow_nil: true),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'maxCount' => max_count, '_meta' => meta }.compact
  end
end
