# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::NesSearchAndReplaceSuggestion
  # @dynamic id
  attr_reader :id #: String

  # @dynamic uri
  attr_reader :uri #: String

  # @dynamic search
  attr_reader :search #: String

  # @dynamic replace
  attr_reader :replace #: String

  # @dynamic is_regex
  attr_reader :is_regex #: bool?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs id: String
  # @rbs uri: String
  # @rbs search: String
  # @rbs replace: String
  # @rbs is_regex: bool?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(id:, uri:, search:, replace:, is_regex: nil, meta: nil)
    @id = id
    @uri = uri
    @search = search
    @replace = replace
    @is_regex = is_regex
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::NesSearchAndReplaceSuggestion
  def self.from_h(hash)
    new(
      id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'id'), 'id'),
      uri: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'uri'), 'uri'),
      search: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'search'), 'search'),
      replace: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'replace'), 'replace'),
      is_regex: ACP::Types::Check.boolean(hash['isRegex'], 'isRegex', allow_nil: true),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'id' => id,
      'uri' => uri,
      'search' => search,
      'replace' => replace,
      'isRegex' => is_regex,
      '_meta' => meta
    }.compact
  end
end
