# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::NesExcerpt
  # @dynamic start_line
  attr_reader :start_line #: Integer

  # @dynamic end_line
  attr_reader :end_line #: Integer

  # @dynamic text
  attr_reader :text #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs start_line: Integer
  # @rbs end_line: Integer
  # @rbs text: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(start_line:, end_line:, text:, meta: nil)
    @start_line = start_line
    @end_line = end_line
    @text = text
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::NesExcerpt
  def self.from_h(hash)
    new(
      start_line: ACP::Types::Check.integer(ACP::Types::Check.key(hash, 'startLine'), 'startLine', min: 0),
      end_line: ACP::Types::Check.integer(ACP::Types::Check.key(hash, 'endLine'), 'endLine', min: 0),
      text: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'text'), 'text'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'startLine' => start_line, 'endLine' => end_line, 'text' => text, '_meta' => meta }.compact
  end
end
