# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

# @rbs!
#   class ACP::Types::Unstable::NesSearchAndReplaceSuggestion = ACP::Types::Unstable::NesSuggestion::Searchandreplace

ACP::Types::Unstable::NesSearchAndReplaceSuggestion = ACP::Types::Unstable::NesSuggestion::Searchandreplace
