# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::NesContextCapabilities
  # @dynamic recent_files
  attr_reader :recent_files #: ACP::Types::Unstable::NesRecentFilesCapabilities?

  # @dynamic related_snippets
  attr_reader :related_snippets #: ACP::Types::Unstable::NesRelatedSnippetsCapabilities?

  # @dynamic edit_history
  attr_reader :edit_history #: ACP::Types::Unstable::NesEditHistoryCapabilities?

  # @dynamic user_actions
  attr_reader :user_actions #: ACP::Types::Unstable::NesUserActionsCapabilities?

  # @dynamic open_files
  attr_reader :open_files #: ACP::Types::Unstable::NesOpenFilesCapabilities?

  # @dynamic diagnostics
  attr_reader :diagnostics #: ACP::Types::Unstable::NesDiagnosticsCapabilities?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs recent_files: ACP::Types::Unstable::NesRecentFilesCapabilities?
  # @rbs related_snippets: ACP::Types::Unstable::NesRelatedSnippetsCapabilities?
  # @rbs edit_history: ACP::Types::Unstable::NesEditHistoryCapabilities?
  # @rbs user_actions: ACP::Types::Unstable::NesUserActionsCapabilities?
  # @rbs open_files: ACP::Types::Unstable::NesOpenFilesCapabilities?
  # @rbs diagnostics: ACP::Types::Unstable::NesDiagnosticsCapabilities?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(
    recent_files: nil,
    related_snippets: nil,
    edit_history: nil,
    user_actions: nil,
    open_files: nil,
    diagnostics: nil,
    meta: nil
  )
    @recent_files = recent_files
    @related_snippets = related_snippets
    @edit_history = edit_history
    @user_actions = user_actions
    @open_files = open_files
    @diagnostics = diagnostics
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::NesContextCapabilities
  def self.from_h(hash)
    new(
      recent_files: ACP::Types::Check.object(
        hash['recentFiles'],
        'recentFiles',
        ACP::Types::Unstable::NesRecentFilesCapabilities,
        allow_nil: true
      ),
      related_snippets: ACP::Types::Check.object(
        hash['relatedSnippets'],
        'relatedSnippets',
        ACP::Types::Unstable::NesRelatedSnippetsCapabilities,
        allow_nil: true
      ),
      edit_history: ACP::Types::Check.object(
        hash['editHistory'],
        'editHistory',
        ACP::Types::Unstable::NesEditHistoryCapabilities,
        allow_nil: true
      ),
      user_actions: ACP::Types::Check.object(
        hash['userActions'],
        'userActions',
        ACP::Types::Unstable::NesUserActionsCapabilities,
        allow_nil: true
      ),
      open_files: ACP::Types::Check.object(
        hash['openFiles'],
        'openFiles',
        ACP::Types::Unstable::NesOpenFilesCapabilities,
        allow_nil: true
      ),
      diagnostics: ACP::Types::Check.object(
        hash['diagnostics'],
        'diagnostics',
        ACP::Types::Unstable::NesDiagnosticsCapabilities,
        allow_nil: true
      ),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'recentFiles' => recent_files&.to_h,
      'relatedSnippets' => related_snippets&.to_h,
      'editHistory' => edit_history&.to_h,
      'userActions' => user_actions&.to_h,
      'openFiles' => open_files&.to_h,
      'diagnostics' => diagnostics&.to_h,
      '_meta' => meta
    }.compact
  end
end
