# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::NesRelatedSnippet
  # @dynamic uri
  attr_reader :uri #: String

  # @dynamic excerpts
  attr_reader :excerpts #: Array[ACP::Types::Unstable::NesExcerpt]

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs uri: String
  # @rbs excerpts: Array[ACP::Types::Unstable::NesExcerpt]
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(uri:, excerpts:, meta: nil)
    @uri = uri
    @excerpts = excerpts
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::NesRelatedSnippet
  def self.from_h(hash)
    excerpts = ACP::Types::Check.array(ACP::Types::Check.key(hash, 'excerpts'), 'excerpts') do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::Unstable::NesExcerpt)
    end
    new(uri: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'uri'), 'uri'), excerpts:, meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'uri' => uri, 'excerpts' => excerpts.map(&:to_h), '_meta' => meta }.compact
  end
end
