# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::NesEditHistoryEntry
  # @dynamic uri
  attr_reader :uri #: String

  # @dynamic diff
  attr_reader :diff #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs uri: String
  # @rbs diff: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(uri:, diff:, meta: nil)
    @uri = uri
    @diff = diff
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::NesEditHistoryEntry
  def self.from_h(hash)
    new(
      uri: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'uri'), 'uri'),
      diff: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'diff'), 'diff'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'uri' => uri, 'diff' => diff, '_meta' => meta }.compact
  end
end
