# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::NesTextEdit
  # @dynamic range
  attr_reader :range #: ACP::Types::Unstable::Range

  # @dynamic new_text
  attr_reader :new_text #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs range: ACP::Types::Unstable::Range
  # @rbs new_text: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(range:, new_text:, meta: nil)
    @range = range
    @new_text = new_text
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::NesTextEdit
  def self.from_h(hash)
    new(
      range: ACP::Types::Check.object(ACP::Types::Check.key(hash, 'range'), 'range', ACP::Types::Unstable::Range),
      new_text: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'newText'), 'newText'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'range' => range.to_h, 'newText' => new_text, '_meta' => meta }.compact
  end
end
