# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::NesDiagnostic
  # @dynamic uri
  attr_reader :uri #: String

  # @dynamic range
  attr_reader :range #: ACP::Types::Unstable::Range

  # @dynamic severity
  attr_reader :severity #: String

  # @dynamic message
  attr_reader :message #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs uri: String
  # @rbs range: ACP::Types::Unstable::Range
  # @rbs severity: String
  # @rbs message: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(uri:, range:, severity:, message:, meta: nil)
    @uri = uri
    @range = range
    @severity = severity
    @message = message
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::NesDiagnostic
  def self.from_h(hash)
    new(
      uri: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'uri'), 'uri'),
      range: ACP::Types::Check.object(ACP::Types::Check.key(hash, 'range'), 'range', ACP::Types::Unstable::Range),
      severity: ACP::Types::Check.enum(
        ACP::Types::Check.key(hash, 'severity'),
        'severity',
        %w[error warning information hint]
      ),
      message: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'message'), 'message'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'uri' => uri, 'range' => range.to_h, 'severity' => severity, 'message' => message, '_meta' => meta }.compact
  end
end
