# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::NesEditSuggestion
  # @dynamic id
  attr_reader :id #: String

  # @dynamic uri
  attr_reader :uri #: String

  # @dynamic edits
  attr_reader :edits #: Array[ACP::Types::Unstable::NesTextEdit]

  # @dynamic cursor_position
  attr_reader :cursor_position #: ACP::Types::Unstable::Position?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs id: String
  # @rbs uri: String
  # @rbs edits: Array[ACP::Types::Unstable::NesTextEdit]
  # @rbs cursor_position: ACP::Types::Unstable::Position?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(id:, uri:, edits:, cursor_position: nil, meta: nil)
    @id = id
    @uri = uri
    @edits = edits
    @cursor_position = cursor_position
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::NesEditSuggestion
  def self.from_h(hash)
    edits = ACP::Types::Check.array(ACP::Types::Check.key(hash, 'edits'), 'edits') do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::Unstable::NesTextEdit)
    end
    new(
      id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'id'), 'id'),
      uri: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'uri'), 'uri'),
      edits:,
      cursor_position: ACP::Types::Check.object(
        hash['cursorPosition'],
        'cursorPosition',
        ACP::Types::Unstable::Position,
        allow_nil: true
      ),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'id' => id,
      'uri' => uri,
      'edits' => edits.map(&:to_h),
      'cursorPosition' => cursor_position&.to_h,
      '_meta' => meta
    }.compact
  end
end
