# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::NesDocumentEventCapabilities
  # @dynamic did_open
  attr_reader :did_open #: ACP::Types::Unstable::NesDocumentDidOpenCapabilities?

  # @dynamic did_change
  attr_reader :did_change #: ACP::Types::Unstable::NesDocumentDidChangeCapabilities?

  # @dynamic did_close
  attr_reader :did_close #: ACP::Types::Unstable::NesDocumentDidCloseCapabilities?

  # @dynamic did_save
  attr_reader :did_save #: ACP::Types::Unstable::NesDocumentDidSaveCapabilities?

  # @dynamic did_focus
  attr_reader :did_focus #: ACP::Types::Unstable::NesDocumentDidFocusCapabilities?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs did_open: ACP::Types::Unstable::NesDocumentDidOpenCapabilities?
  # @rbs did_change: ACP::Types::Unstable::NesDocumentDidChangeCapabilities?
  # @rbs did_close: ACP::Types::Unstable::NesDocumentDidCloseCapabilities?
  # @rbs did_save: ACP::Types::Unstable::NesDocumentDidSaveCapabilities?
  # @rbs did_focus: ACP::Types::Unstable::NesDocumentDidFocusCapabilities?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(did_open: nil, did_change: nil, did_close: nil, did_save: nil, did_focus: nil, meta: nil)
    @did_open = did_open
    @did_change = did_change
    @did_close = did_close
    @did_save = did_save
    @did_focus = did_focus
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::NesDocumentEventCapabilities
  def self.from_h(hash)
    new(
      did_open: ACP::Types::Check.object(
        hash['didOpen'],
        'didOpen',
        ACP::Types::Unstable::NesDocumentDidOpenCapabilities,
        allow_nil: true
      ),
      did_change: ACP::Types::Check.object(
        hash['didChange'],
        'didChange',
        ACP::Types::Unstable::NesDocumentDidChangeCapabilities,
        allow_nil: true
      ),
      did_close: ACP::Types::Check.object(
        hash['didClose'],
        'didClose',
        ACP::Types::Unstable::NesDocumentDidCloseCapabilities,
        allow_nil: true
      ),
      did_save: ACP::Types::Check.object(
        hash['didSave'],
        'didSave',
        ACP::Types::Unstable::NesDocumentDidSaveCapabilities,
        allow_nil: true
      ),
      did_focus: ACP::Types::Check.object(
        hash['didFocus'],
        'didFocus',
        ACP::Types::Unstable::NesDocumentDidFocusCapabilities,
        allow_nil: true
      ),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'didOpen' => did_open&.to_h,
      'didChange' => did_change&.to_h,
      'didClose' => did_close&.to_h,
      'didSave' => did_save&.to_h,
      'didFocus' => did_focus&.to_h,
      '_meta' => meta
    }.compact
  end
end
