# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

module ACP::Types::Unstable::NesSuggestion
  # @rbs!
  #   type t = ACP::Types::Unstable::NesSuggestion::Edit
  #          | ACP::Types::Unstable::NesSuggestion::Jump
  #          | ACP::Types::Unstable::NesSuggestion::Rename
  #          | ACP::Types::Unstable::NesSuggestion::Searchandreplace
  #          | Hash[String, untyped]

  # @rbs hash: Hash[String, untyped]
  # @rbs return: t
  def self.from_h(hash)
    case hash['kind']
    when 'edit' then ACP::Types::Unstable::NesSuggestion::Edit.from_h(hash)
    when 'jump' then ACP::Types::Unstable::NesSuggestion::Jump.from_h(hash)
    when 'rename' then ACP::Types::Unstable::NesSuggestion::Rename.from_h(hash)
    when 'searchAndReplace' then ACP::Types::Unstable::NesSuggestion::Searchandreplace.from_h(hash)
    else hash
    end
  end
end
