# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::NesRecentFile
  # @dynamic uri
  attr_reader :uri #: String

  # @dynamic language_id
  attr_reader :language_id #: String

  # @dynamic text
  attr_reader :text #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs uri: String
  # @rbs language_id: String
  # @rbs text: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(uri:, language_id:, text:, meta: nil)
    @uri = uri
    @language_id = language_id
    @text = text
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::NesRecentFile
  def self.from_h(hash)
    new(
      uri: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'uri'), 'uri'),
      language_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'languageId'), 'languageId'),
      text: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'text'), 'text'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'uri' => uri, 'languageId' => language_id, 'text' => text, '_meta' => meta }.compact
  end
end
