# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

module ACP::Types::Unstable::PlanUpdateContent
  # @rbs!
  #   type t = ACP::Types::Unstable::PlanUpdateContent::Items
  #          | ACP::Types::Unstable::PlanUpdateContent::File
  #          | ACP::Types::Unstable::PlanUpdateContent::Markdown
  #          | Hash[String, untyped]

  # @rbs hash: Hash[String, untyped]
  # @rbs return: t
  def self.from_h(hash)
    case hash['type']
    when 'items' then ACP::Types::Unstable::PlanUpdateContent::Items.from_h(hash)
    when 'file' then ACP::Types::Unstable::PlanUpdateContent::File.from_h(hash)
    when 'markdown' then ACP::Types::Unstable::PlanUpdateContent::Markdown.from_h(hash)
    else hash
    end
  end
end
