# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::PlanItems
  # @dynamic plan_id
  attr_reader :plan_id #: String

  # @dynamic entries
  attr_reader :entries #: Array[ACP::Types::PlanEntry]

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs plan_id: String
  # @rbs entries: Array[ACP::Types::PlanEntry]
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(plan_id:, entries:, meta: nil)
    @plan_id = plan_id
    @entries = entries
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::PlanItems
  def self.from_h(hash)
    entries = ACP::Types::Check.array(ACP::Types::Check.key(hash, 'entries'), 'entries') do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::PlanEntry)
    end
    new(
      plan_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'planId'), 'planId'),
      entries:,
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'planId' => plan_id, 'entries' => entries.map(&:to_h), '_meta' => meta }.compact
  end
end
