# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

module ACP::Types::Unstable::PositionEncodingKind
  UTF_16 = 'utf-16'
  UTF_32 = 'utf-32'
  UTF_8 = 'utf-8'
end
