# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::Position
  # @dynamic line
  attr_reader :line #: Integer

  # @dynamic character
  attr_reader :character #: Integer

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs line: Integer
  # @rbs character: Integer
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(line:, character:, meta: nil)
    @line = line
    @character = character
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::Position
  def self.from_h(hash)
    new(
      line: ACP::Types::Check.integer(ACP::Types::Check.key(hash, 'line'), 'line', min: 0),
      character: ACP::Types::Check.integer(ACP::Types::Check.key(hash, 'character'), 'character', min: 0),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'line' => line, 'character' => character, '_meta' => meta }.compact
  end
end
