# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::ProviderCurrentConfig
  # @dynamic api_type
  attr_reader :api_type #: String

  # @dynamic base_url
  attr_reader :base_url #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs api_type: String
  # @rbs base_url: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(api_type:, base_url:, meta: nil)
    @api_type = api_type
    @base_url = base_url
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::ProviderCurrentConfig
  def self.from_h(hash)
    new(
      api_type: ACP::Types::Check.key(hash, 'apiType'),
      base_url: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'baseUrl'), 'baseUrl'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'apiType' => api_type, 'baseUrl' => base_url, '_meta' => meta }.compact
  end
end
