# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::ProviderInfo
  # @dynamic provider_id
  attr_reader :provider_id #: String

  # @dynamic supported
  attr_reader :supported #: Array[String]

  # @dynamic required
  attr_reader :required #: bool

  # @dynamic current
  attr_reader :current #: ACP::Types::Unstable::ProviderCurrentConfig?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs provider_id: String
  # @rbs supported: Array[String]
  # @rbs required: bool
  # @rbs current: ACP::Types::Unstable::ProviderCurrentConfig?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(provider_id:, supported:, required:, current: nil, meta: nil)
    @provider_id = provider_id
    @supported = supported
    @required = required
    @current = current
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::ProviderInfo
  def self.from_h(hash)
    new(
      provider_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'providerId'), 'providerId'),
      supported: ACP::Types::Check.key(hash, 'supported'),
      required: ACP::Types::Check.boolean(ACP::Types::Check.key(hash, 'required'), 'required'),
      current: ACP::Types::Check.object(
        hash['current'],
        'current',
        ACP::Types::Unstable::ProviderCurrentConfig,
        allow_nil: true
      ),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'providerId' => provider_id,
      'supported' => supported,
      'required' => required,
      'current' => current&.to_h,
      '_meta' => meta
    }.compact
  end
end
