# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::Range
  # @dynamic start
  attr_reader :start #: ACP::Types::Unstable::Position

  # @dynamic end_
  attr_reader :end_ #: ACP::Types::Unstable::Position

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs start: ACP::Types::Unstable::Position
  # @rbs end_: ACP::Types::Unstable::Position
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(start:, end_:, meta: nil)
    @start = start
    @end_ = end_
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::Range
  def self.from_h(hash)
    new(
      start: ACP::Types::Check.object(ACP::Types::Check.key(hash, 'start'), 'start', ACP::Types::Unstable::Position),
      end_: ACP::Types::Check.object(ACP::Types::Check.key(hash, 'end'), 'end', ACP::Types::Unstable::Position),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'start' => start.to_h, 'end' => end_.to_h, '_meta' => meta }.compact
  end
end
