# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::RejectNesNotification
  # @dynamic session_id
  attr_reader :session_id #: String

  # @dynamic id
  attr_reader :id #: String

  # @dynamic reason
  attr_reader :reason #: String?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs session_id: String
  # @rbs id: String
  # @rbs reason: String?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(session_id:, id:, reason: nil, meta: nil)
    @session_id = session_id
    @id = id
    @reason = reason
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::RejectNesNotification
  def self.from_h(hash)
    new(
      session_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'sessionId'), 'sessionId'),
      id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'id'), 'id'),
      reason: ACP::Types::Check.enum(
        hash['reason'],
        'reason',
        %w[rejected ignored replaced cancelled],
        allow_nil: true
      ),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'sessionId' => session_id, 'id' => id, 'reason' => reason, '_meta' => meta }.compact
  end
end
