# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

module ACP::Types::Unstable::SessionUpdate
  # @rbs!
  #   type t = ACP::Types::Unstable::SessionUpdate::UserMessageChunk
  #          | ACP::Types::Unstable::SessionUpdate::AgentMessageChunk
  #          | ACP::Types::Unstable::SessionUpdate::AgentThoughtChunk
  #          | ACP::Types::Unstable::SessionUpdate::ToolCall
  #          | ACP::Types::Unstable::SessionUpdate::ToolCallUpdate
  #          | ACP::Types::Unstable::SessionUpdate::Plan
  #          | ACP::Types::Unstable::SessionUpdate::PlanUpdate
  #          | ACP::Types::Unstable::SessionUpdate::PlanRemoved
  #          | ACP::Types::Unstable::SessionUpdate::AvailableCommandsUpdate
  #          | ACP::Types::Unstable::SessionUpdate::CurrentModeUpdate
  #          | ACP::Types::Unstable::SessionUpdate::ConfigOptionUpdate
  #          | ACP::Types::Unstable::SessionUpdate::SessionInfoUpdate
  #          | ACP::Types::Unstable::SessionUpdate::UsageUpdate
  #          | ACP::Types::Unstable::SessionUpdate::Notice
  #          | ACP::Types::Unstable::SessionUpdate::CompactionUpdate
  #          | ACP::Types::Unstable::SessionUpdate::CompactionSummaryChunk
  #          | ACP::Types::Unstable::SessionUpdate::SubagentUpdate
  #          | ACP::Types::Unstable::SessionUpdate::SessionMessage
  #          | ACP::Types::Unstable::SessionUpdate::SessionMessageChunk
  #          | Hash[String, untyped]

  # @rbs hash: Hash[String, untyped]
  # @rbs return: t
  def self.from_h(hash)
    case hash['sessionUpdate']
    when 'user_message_chunk' then ACP::Types::Unstable::SessionUpdate::UserMessageChunk.from_h(hash)
    when 'agent_message_chunk' then ACP::Types::Unstable::SessionUpdate::AgentMessageChunk.from_h(hash)
    when 'agent_thought_chunk' then ACP::Types::Unstable::SessionUpdate::AgentThoughtChunk.from_h(hash)
    when 'tool_call' then ACP::Types::Unstable::SessionUpdate::ToolCall.from_h(hash)
    when 'tool_call_update' then ACP::Types::Unstable::SessionUpdate::ToolCallUpdate.from_h(hash)
    when 'plan' then ACP::Types::Unstable::SessionUpdate::Plan.from_h(hash)
    when 'plan_update' then ACP::Types::Unstable::SessionUpdate::PlanUpdate.from_h(hash)
    when 'plan_removed' then ACP::Types::Unstable::SessionUpdate::PlanRemoved.from_h(hash)
    when 'available_commands_update' then ACP::Types::Unstable::SessionUpdate::AvailableCommandsUpdate.from_h(hash)
    when 'current_mode_update' then ACP::Types::Unstable::SessionUpdate::CurrentModeUpdate.from_h(hash)
    when 'config_option_update' then ACP::Types::Unstable::SessionUpdate::ConfigOptionUpdate.from_h(hash)
    when 'session_info_update' then ACP::Types::Unstable::SessionUpdate::SessionInfoUpdate.from_h(hash)
    when 'usage_update' then ACP::Types::Unstable::SessionUpdate::UsageUpdate.from_h(hash)
    when 'notice' then ACP::Types::Unstable::SessionUpdate::Notice.from_h(hash)
    when 'compaction_update' then ACP::Types::Unstable::SessionUpdate::CompactionUpdate.from_h(hash)
    when 'compaction_summary_chunk' then ACP::Types::Unstable::SessionUpdate::CompactionSummaryChunk.from_h(hash)
    when 'subagent_update' then ACP::Types::Unstable::SessionUpdate::SubagentUpdate.from_h(hash)
    when 'session_message' then ACP::Types::Unstable::SessionUpdate::SessionMessage.from_h(hash)
    when 'session_message_chunk' then ACP::Types::Unstable::SessionUpdate::SessionMessageChunk.from_h(hash)
    else hash
    end
  end
end
