# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::SessionCapabilities
  # @dynamic list
  attr_reader :list #: ACP::Types::SessionListCapabilities?

  # @dynamic delete
  attr_reader :delete #: ACP::Types::SessionDeleteCapabilities?

  # @dynamic additional_directories
  attr_reader :additional_directories #: ACP::Types::SessionAdditionalDirectoriesCapabilities?

  # @dynamic fork
  attr_reader :fork #: ACP::Types::Unstable::SessionForkCapabilities?

  # @dynamic resume
  attr_reader :resume #: ACP::Types::SessionResumeCapabilities?

  # @dynamic close
  attr_reader :close #: ACP::Types::SessionCloseCapabilities?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs list: ACP::Types::SessionListCapabilities?
  # @rbs delete: ACP::Types::SessionDeleteCapabilities?
  # @rbs additional_directories: ACP::Types::SessionAdditionalDirectoriesCapabilities?
  # @rbs fork: ACP::Types::Unstable::SessionForkCapabilities?
  # @rbs resume: ACP::Types::SessionResumeCapabilities?
  # @rbs close: ACP::Types::SessionCloseCapabilities?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(list: nil, delete: nil, additional_directories: nil, fork: nil, resume: nil, close: nil, meta: nil)
    @list = list
    @delete = delete
    @additional_directories = additional_directories
    @fork = fork
    @resume = resume
    @close = close
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::SessionCapabilities
  def self.from_h(hash)
    new(
      list: ACP::Types::Check.object(hash['list'], 'list', ACP::Types::SessionListCapabilities, allow_nil: true),
      delete: ACP::Types::Check.object(
        hash['delete'],
        'delete',
        ACP::Types::SessionDeleteCapabilities,
        allow_nil: true
      ),
      additional_directories: ACP::Types::Check.object(
        hash['additionalDirectories'],
        'additionalDirectories',
        ACP::Types::SessionAdditionalDirectoriesCapabilities,
        allow_nil: true
      ),
      fork: ACP::Types::Check.object(
        hash['fork'],
        'fork',
        ACP::Types::Unstable::SessionForkCapabilities,
        allow_nil: true
      ),
      resume: ACP::Types::Check.object(
        hash['resume'],
        'resume',
        ACP::Types::SessionResumeCapabilities,
        allow_nil: true
      ),
      close: ACP::Types::Check.object(hash['close'], 'close', ACP::Types::SessionCloseCapabilities, allow_nil: true),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'list' => list&.to_h,
      'delete' => delete&.to_h,
      'additionalDirectories' => additional_directories&.to_h,
      'fork' => fork&.to_h,
      'resume' => resume&.to_h,
      'close' => close&.to_h,
      '_meta' => meta
    }.compact
  end
end
