# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::SetProviderRequest
  # @dynamic provider_id
  attr_reader :provider_id #: String

  # @dynamic api_type
  attr_reader :api_type #: String

  # @dynamic base_url
  attr_reader :base_url #: String

  # @dynamic headers
  attr_reader :headers #: Hash[String, String]?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs provider_id: String
  # @rbs api_type: String
  # @rbs base_url: String
  # @rbs headers: Hash[String, String]?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(provider_id:, api_type:, base_url:, headers: nil, meta: nil)
    @provider_id = provider_id
    @api_type = api_type
    @base_url = base_url
    @headers = headers
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::SetProviderRequest
  def self.from_h(hash)
    headers = ACP::Types::Check.hash(hash['headers'], 'headers', allow_nil: true) do |value, path|
      ACP::Types::Check.string(value, path)
    end
    new(
      provider_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'providerId'), 'providerId'),
      api_type: ACP::Types::Check.key(hash, 'apiType'),
      base_url: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'baseUrl'), 'baseUrl'),
      headers:,
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'providerId' => provider_id,
      'apiType' => api_type,
      'baseUrl' => base_url,
      'headers' => headers,
      '_meta' => meta
    }.compact
  end
end
