# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::StartNesRequest
  # @dynamic workspace_uri
  attr_reader :workspace_uri #: String?

  # @dynamic workspace_folders
  attr_reader :workspace_folders #: Array[ACP::Types::Unstable::WorkspaceFolder]?

  # @dynamic repository
  attr_reader :repository #: ACP::Types::Unstable::NesRepository?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs workspace_uri: String?
  # @rbs workspace_folders: Array[ACP::Types::Unstable::WorkspaceFolder]?
  # @rbs repository: ACP::Types::Unstable::NesRepository?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(workspace_uri: nil, workspace_folders: nil, repository: nil, meta: nil)
    @workspace_uri = workspace_uri
    @workspace_folders = workspace_folders
    @repository = repository
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::StartNesRequest
  def self.from_h(hash)
    workspace_folders = ACP::Types::Check.array(
      hash['workspaceFolders'],
      'workspaceFolders',
      allow_nil: true
    ) do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::Unstable::WorkspaceFolder)
    end
    new(
      workspace_uri: ACP::Types::Check.string(hash['workspaceUri'], 'workspaceUri', allow_nil: true),
      workspace_folders:,
      repository: ACP::Types::Check.object(
        hash['repository'],
        'repository',
        ACP::Types::Unstable::NesRepository,
        allow_nil: true
      ),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'workspaceUri' => workspace_uri,
      'workspaceFolders' => workspace_folders&.map(&:to_h),
      'repository' => repository&.to_h,
      '_meta' => meta
    }.compact
  end
end
