# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

module ACP::Types::Unstable::StateUpdate
  # @rbs!
  #   type t = ACP::Types::Unstable::StateUpdate::Running
  #          | ACP::Types::Unstable::StateUpdate::Idle
  #          | ACP::Types::Unstable::StateUpdate::RequiresAction
  #          | ACP::Types::Unstable::StateUpdate::Unknown
  #          | Hash[String, untyped]

  # @rbs hash: Hash[String, untyped]
  # @rbs return: t
  def self.from_h(hash)
    case hash['state']
    when 'running' then ACP::Types::Unstable::StateUpdate::Running.from_h(hash)
    when 'idle' then ACP::Types::Unstable::StateUpdate::Idle.from_h(hash)
    when 'requires_action' then ACP::Types::Unstable::StateUpdate::RequiresAction.from_h(hash)
    when 'unknown' then ACP::Types::Unstable::StateUpdate::Unknown.from_h(hash)
    else hash
    end
  end
end
