# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::SubagentSessionCapabilities
  # @dynamic cancel
  attr_reader :cancel #: ACP::Types::Unstable::SessionCancelCapabilities?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs cancel: ACP::Types::Unstable::SessionCancelCapabilities?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(cancel: nil, meta: nil)
    @cancel = cancel
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::SubagentSessionCapabilities
  def self.from_h(hash)
    new(
      cancel: ACP::Types::Check.object(
        hash['cancel'],
        'cancel',
        ACP::Types::Unstable::SessionCancelCapabilities,
        allow_nil: true
      ),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'cancel' => cancel&.to_h, '_meta' => meta }.compact
  end
end
