# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::SuggestNesRequest
  # @dynamic session_id
  attr_reader :session_id #: String

  # @dynamic uri
  attr_reader :uri #: String

  # @dynamic version
  attr_reader :version #: Integer

  # @dynamic position
  attr_reader :position #: ACP::Types::Unstable::Position

  # @dynamic selection
  attr_reader :selection #: ACP::Types::Unstable::Range?

  # @dynamic trigger_kind
  attr_reader :trigger_kind #: String

  # @dynamic context
  attr_reader :context #: ACP::Types::Unstable::NesSuggestContext?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs session_id: String
  # @rbs uri: String
  # @rbs version: Integer
  # @rbs position: ACP::Types::Unstable::Position
  # @rbs selection: ACP::Types::Unstable::Range?
  # @rbs trigger_kind: String
  # @rbs context: ACP::Types::Unstable::NesSuggestContext?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(session_id:, uri:, version:, position:, trigger_kind:, selection: nil, context: nil, meta: nil)
    @session_id = session_id
    @uri = uri
    @version = version
    @position = position
    @selection = selection
    @trigger_kind = trigger_kind
    @context = context
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::SuggestNesRequest
  def self.from_h(hash)
    new(
      session_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'sessionId'), 'sessionId'),
      uri: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'uri'), 'uri'),
      version: ACP::Types::Check.integer(ACP::Types::Check.key(hash, 'version'), 'version'),
      position: ACP::Types::Check.object(
        ACP::Types::Check.key(hash, 'position'),
        'position',
        ACP::Types::Unstable::Position
      ),
      selection: ACP::Types::Check.object(hash['selection'], 'selection', ACP::Types::Unstable::Range, allow_nil: true),
      trigger_kind: ACP::Types::Check.enum(
        ACP::Types::Check.key(hash, 'triggerKind'),
        'triggerKind',
        %w[automatic diagnostic manual]
      ),
      context: ACP::Types::Check.object(
        hash['context'],
        'context',
        ACP::Types::Unstable::NesSuggestContext,
        allow_nil: true
      ),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'sessionId' => session_id,
      'uri' => uri,
      'version' => version,
      'position' => position.to_h,
      'triggerKind' => trigger_kind,
      'selection' => selection&.to_h,
      'context' => context&.to_h,
      '_meta' => meta
    }.compact
  end
end
