# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::SuggestNesResponse
  # @dynamic suggestions
  attr_reader :suggestions #: Array[ACP::Types::Unstable::NesSuggestion::t]

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs suggestions: Array[ACP::Types::Unstable::NesSuggestion::t]
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(suggestions:, meta: nil)
    @suggestions = suggestions
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::SuggestNesResponse
  def self.from_h(hash)
    suggestions = ACP::Types::Check.array(ACP::Types::Check.key(hash, 'suggestions'), 'suggestions') do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::Unstable::NesSuggestion)
    end
    new(suggestions:, meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'suggestions' => suggestions.map(&:to_h), '_meta' => meta }.compact
  end
end
