# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::TextDocumentContentChangeEvent
  # @dynamic range
  attr_reader :range #: ACP::Types::Unstable::Range?

  # @dynamic text
  attr_reader :text #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs range: ACP::Types::Unstable::Range?
  # @rbs text: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(text:, range: nil, meta: nil)
    @range = range
    @text = text
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::TextDocumentContentChangeEvent
  def self.from_h(hash)
    new(
      range: ACP::Types::Check.object(hash['range'], 'range', ACP::Types::Unstable::Range, allow_nil: true),
      text: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'text'), 'text'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'text' => text, 'range' => range&.to_h, '_meta' => meta }.compact
  end
end
