# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::Usage
  # @dynamic total_tokens
  attr_reader :total_tokens #: Integer

  # @dynamic input_tokens
  attr_reader :input_tokens #: Integer

  # @dynamic output_tokens
  attr_reader :output_tokens #: Integer

  # @dynamic thought_tokens
  attr_reader :thought_tokens #: Integer?

  # @dynamic cached_read_tokens
  attr_reader :cached_read_tokens #: Integer?

  # @dynamic cached_write_tokens
  attr_reader :cached_write_tokens #: Integer?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs total_tokens: Integer
  # @rbs input_tokens: Integer
  # @rbs output_tokens: Integer
  # @rbs thought_tokens: Integer?
  # @rbs cached_read_tokens: Integer?
  # @rbs cached_write_tokens: Integer?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(
    total_tokens:,
    input_tokens:,
    output_tokens:,
    thought_tokens: nil,
    cached_read_tokens: nil,
    cached_write_tokens: nil,
    meta: nil
  )
    @total_tokens = total_tokens
    @input_tokens = input_tokens
    @output_tokens = output_tokens
    @thought_tokens = thought_tokens
    @cached_read_tokens = cached_read_tokens
    @cached_write_tokens = cached_write_tokens
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::Usage
  def self.from_h(hash)
    new(
      total_tokens: ACP::Types::Check.integer(ACP::Types::Check.key(hash, 'totalTokens'), 'totalTokens', min: 0),
      input_tokens: ACP::Types::Check.integer(ACP::Types::Check.key(hash, 'inputTokens'), 'inputTokens', min: 0),
      output_tokens: ACP::Types::Check.integer(ACP::Types::Check.key(hash, 'outputTokens'), 'outputTokens', min: 0),
      thought_tokens: ACP::Types::Check.integer(hash['thoughtTokens'], 'thoughtTokens', min: 0, allow_nil: true),
      cached_read_tokens: ACP::Types::Check.integer(
        hash['cachedReadTokens'],
        'cachedReadTokens',
        min: 0,
        allow_nil: true
      ),
      cached_write_tokens: ACP::Types::Check.integer(
        hash['cachedWriteTokens'],
        'cachedWriteTokens',
        min: 0,
        allow_nil: true
      ),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'totalTokens' => total_tokens,
      'inputTokens' => input_tokens,
      'outputTokens' => output_tokens,
      'thoughtTokens' => thought_tokens,
      'cachedReadTokens' => cached_read_tokens,
      'cachedWriteTokens' => cached_write_tokens,
      '_meta' => meta
    }.compact
  end
end
