# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::WorkspaceFolder
  # @dynamic uri
  attr_reader :uri #: String

  # @dynamic name
  attr_reader :name #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs uri: String
  # @rbs name: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(uri:, name:, meta: nil)
    @uri = uri
    @name = name
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::WorkspaceFolder
  def self.from_h(hash)
    new(
      uri: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'uri'), 'uri'),
      name: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'name'), 'name'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'uri' => uri, 'name' => name, '_meta' => meta }.compact
  end
end
