# frozen_string_literal: true

require 'test_helper'
require_relative 'fixtures'

describe TypeGenerator::Emit do
  it 'renders an object class with its accessors, initialize, from_h, and to_h' do
    assert_equal <<~RUBY, FixtureSchemas::FILES.fetch('note.rb')
      # frozen_string_literal: true

      # Generated by bin/types from schema/schema.json. Do not edit.

      class ACP::Types::Note
        # @dynamic text
        attr_reader :text #: String

        # @rbs text: String
        # @rbs return: void
        def initialize(text:)
          @text = text
          freeze
        end

        # @rbs hash: Hash[String, untyped]
        # @rbs return: ACP::Types::Note
        def self.from_h(hash)
          new(text: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'text'), 'text'))
        end

        # @rbs return: Hash[String, untyped]
        def to_h
          { 'text' => text }
        end
      end
    RUBY
  end

  it 'reports parse failures at absolute paths through nested guards' do
    # The emitted classes are evaluated so the guard threading can be exercised
    # against the real Check module.
    Object.module_eval(FixtureSchemas::FILES.fetch('step.rb'))
    Object.module_eval(FixtureSchemas::FILES.fetch('widget_request.rb'))

    error = assert_raises(ACP::Types::ParseError) do
      ACP::Types::WidgetRequest.from_h({ 'label' => 'w', 'steps' => [{ 'index' => 'nope' }] })
    end

    assert_equal 'steps[0].index: expected Integer, got String', error.message
  end
end
