# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

module ACP::Types::SessionConfigOption::Kind
  # @rbs!
  #   type t = ACP::Types::SessionConfigOption::Kind::Select
  #          | ACP::Types::SessionConfigOption::Kind::Boolean
  #          | Hash[String, untyped]

  # @rbs hash: Hash[String, untyped]
  # @rbs return: t
  def self.from_h(hash)
    case hash['type']
    when 'select' then ACP::Types::SessionConfigOption::Kind::Select.from_h(hash)
    when 'boolean' then ACP::Types::SessionConfigOption::Kind::Boolean.from_h(hash)
    else hash
    end
  end
end
