# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::MultiSelectItems::StringMultiSelectItems
  # @dynamic enum
  attr_reader :enum #: Array[String]

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs enum: Array[String]
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(enum:, meta: nil)
    @enum = enum
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::MultiSelectItems::StringMultiSelectItems
  def self.from_h(hash)
    enum = ACP::Types::Check.array(ACP::Types::Check.key(hash, 'enum'), 'enum') do |item, path|
      ACP::Types::Check.string(item, path)
    end
    new(enum:, meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'type' => 'string', 'enum' => enum, '_meta' => meta }.compact
  end
end
