# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::RequestPermissionOutcome::Cancelled
  # @rbs return: void
  def initialize
    freeze
  end

  # @rbs _hash: Hash[String, untyped]
  # @rbs return: ACP::Types::RequestPermissionOutcome::Cancelled
  def self.from_h(_hash)
    new
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'outcome' => 'cancelled' }
  end
end
