# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::MessageMcpResponse::Error
  # @dynamic error
  attr_reader :error #: ACP::Types::Unstable::McpError

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs error: ACP::Types::Unstable::McpError
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(error:, meta: nil)
    @error = error
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::MessageMcpResponse::Error
  def self.from_h(hash)
    new(
      error: ACP::Types::Check.object(ACP::Types::Check.key(hash, 'error'), 'error', ACP::Types::Unstable::McpError),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'error' => error.to_h, '_meta' => meta }.compact
  end
end
