# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ToolCallContent::Terminal
  # @dynamic terminal_id
  attr_reader :terminal_id #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs terminal_id: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(terminal_id:, meta: nil)
    @terminal_id = terminal_id
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ToolCallContent::Terminal
  def self.from_h(hash)
    new(
      terminal_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'terminalId'), 'terminalId'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'type' => 'terminal', 'terminalId' => terminal_id, '_meta' => meta }.compact
  end
end
