# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ElicitationPropertySchema::IntegerPropertySchema
  # @dynamic title
  attr_reader :title #: String?

  # @dynamic description
  attr_reader :description #: String?

  # @dynamic minimum
  attr_reader :minimum #: Integer?

  # @dynamic maximum
  attr_reader :maximum #: Integer?

  # @dynamic default
  attr_reader :default #: Integer?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs title: String?
  # @rbs description: String?
  # @rbs minimum: Integer?
  # @rbs maximum: Integer?
  # @rbs default: Integer?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(title: nil, description: nil, minimum: nil, maximum: nil, default: nil, meta: nil)
    @title = title
    @description = description
    @minimum = minimum
    @maximum = maximum
    @default = default
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ElicitationPropertySchema::IntegerPropertySchema
  def self.from_h(hash)
    new(
      title: hash['title'],
      description: hash['description'],
      minimum: hash['minimum'],
      maximum: hash['maximum'],
      default: hash['default'],
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'type' => 'integer',
      'title' => title,
      'description' => description,
      'minimum' => minimum,
      'maximum' => maximum,
      'default' => default,
      '_meta' => meta
    }.compact
  end
end
