# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ElicitationPropertySchema::MultiSelectPropertySchema
  # @dynamic title
  attr_reader :title #: String?

  # @dynamic description
  attr_reader :description #: String?

  # @dynamic min_items
  attr_reader :min_items #: Integer?

  # @dynamic max_items
  attr_reader :max_items #: Integer?

  # @dynamic items
  attr_reader :items #: ACP::Types::MultiSelectItems::t

  # @dynamic default
  attr_reader :default #: Array[String]?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs title: String?
  # @rbs description: String?
  # @rbs min_items: Integer?
  # @rbs max_items: Integer?
  # @rbs items: ACP::Types::MultiSelectItems::t
  # @rbs default: Array[String]?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(items:, title: nil, description: nil, min_items: nil, max_items: nil, default: nil, meta: nil)
    @title = title
    @description = description
    @min_items = min_items
    @max_items = max_items
    @items = items
    @default = default
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ElicitationPropertySchema::MultiSelectPropertySchema
  def self.from_h(hash)
    new(
      title: hash['title'],
      description: hash['description'],
      min_items: hash['minItems'],
      max_items: hash['maxItems'],
      items: ACP::Types::MultiSelectItems.from_h(hash.fetch('items')),
      default: hash['default'],
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'type' => 'array',
      'items' => items.to_h,
      'title' => title,
      'description' => description,
      'minItems' => min_items,
      'maxItems' => max_items,
      'default' => default,
      '_meta' => meta
    }.compact
  end
end
