# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ElicitationPropertySchema::MultiSelectPropertySchema
  # @dynamic title
  attr_reader :title #: String?

  # @dynamic description
  attr_reader :description #: String?

  # @dynamic min_items
  attr_reader :min_items #: Integer?

  # @dynamic max_items
  attr_reader :max_items #: Integer?

  # @dynamic items
  attr_reader :items #: ACP::Types::MultiSelectItems::t

  # @dynamic default
  attr_reader :default #: Array[String]?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs title: String?
  # @rbs description: String?
  # @rbs min_items: Integer?
  # @rbs max_items: Integer?
  # @rbs items: ACP::Types::MultiSelectItems::t
  # @rbs default: Array[String]?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(items:, title: nil, description: nil, min_items: nil, max_items: nil, default: nil, meta: nil)
    @title = title
    @description = description
    @min_items = min_items
    @max_items = max_items
    @items = items
    @default = default
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ElicitationPropertySchema::MultiSelectPropertySchema
  def self.from_h(hash)
    default = ACP::Types::Check.array(hash['default'], 'default', allow_nil: true) do |item, path|
      ACP::Types::Check.string(item, path)
    end
    new(
      title: ACP::Types::Check.string(hash['title'], 'title', allow_nil: true),
      description: ACP::Types::Check.string(hash['description'], 'description', allow_nil: true),
      min_items: ACP::Types::Check.integer(hash['minItems'], 'minItems', min: 0, allow_nil: true),
      max_items: ACP::Types::Check.integer(hash['maxItems'], 'maxItems', min: 0, allow_nil: true),
      items: ACP::Types::Check.object(ACP::Types::Check.key(hash, 'items'), 'items', ACP::Types::MultiSelectItems),
      default:,
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'type' => 'array',
      'items' => items.to_h,
      'title' => title,
      'description' => description,
      'minItems' => min_items,
      'maxItems' => max_items,
      'default' => default,
      '_meta' => meta
    }.compact
  end
end
