# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ElicitationPropertySchema::NumberPropertySchema
  # @dynamic title
  attr_reader :title #: String?

  # @dynamic description
  attr_reader :description #: String?

  # @dynamic minimum
  attr_reader :minimum #: Numeric?

  # @dynamic maximum
  attr_reader :maximum #: Numeric?

  # @dynamic default
  attr_reader :default #: Numeric?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs title: String?
  # @rbs description: String?
  # @rbs minimum: Numeric?
  # @rbs maximum: Numeric?
  # @rbs default: Numeric?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(title: nil, description: nil, minimum: nil, maximum: nil, default: nil, meta: nil)
    @title = title
    @description = description
    @minimum = minimum
    @maximum = maximum
    @default = default
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ElicitationPropertySchema::NumberPropertySchema
  def self.from_h(hash)
    new(
      title: ACP::Types::Check.string(hash['title'], 'title', allow_nil: true),
      description: ACP::Types::Check.string(hash['description'], 'description', allow_nil: true),
      minimum: ACP::Types::Check.number(hash['minimum'], 'minimum', allow_nil: true),
      maximum: ACP::Types::Check.number(hash['maximum'], 'maximum', allow_nil: true),
      default: ACP::Types::Check.number(hash['default'], 'default', allow_nil: true),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'type' => 'number',
      'title' => title,
      'description' => description,
      'minimum' => minimum,
      'maximum' => maximum,
      'default' => default,
      '_meta' => meta
    }.compact
  end
end
