# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ContentBlock::Audio
  # @dynamic annotations
  attr_reader :annotations #: ACP::Types::Annotations?

  # @dynamic data
  attr_reader :data #: String

  # @dynamic mime_type
  attr_reader :mime_type #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs annotations: ACP::Types::Annotations?
  # @rbs data: String
  # @rbs mime_type: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(data:, mime_type:, annotations: nil, meta: nil)
    @annotations = annotations
    @data = data
    @mime_type = mime_type
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ContentBlock::Audio
  def self.from_h(hash)
    new(
      annotations: hash['annotations']&.then { |value| ACP::Types::Annotations.from_h(value) },
      data: hash.fetch('data'),
      mime_type: hash.fetch('mimeType'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'type' => 'audio',
      'data' => data,
      'mimeType' => mime_type,
      'annotations' => annotations&.to_h,
      '_meta' => meta
    }.compact
  end
end
