# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ContentBlock::Image
  # @dynamic annotations
  attr_reader :annotations #: ACP::Types::Annotations?

  # @dynamic data
  attr_reader :data #: String

  # @dynamic mime_type
  attr_reader :mime_type #: String

  # @dynamic uri
  attr_reader :uri #: String?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs annotations: ACP::Types::Annotations?
  # @rbs data: String
  # @rbs mime_type: String
  # @rbs uri: String?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(data:, mime_type:, annotations: nil, uri: nil, meta: nil)
    @annotations = annotations
    @data = data
    @mime_type = mime_type
    @uri = uri
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ContentBlock::Image
  def self.from_h(hash)
    new(
      annotations: ACP::Types::Check.object(
        hash['annotations'],
        'annotations',
        ACP::Types::Annotations,
        allow_nil: true
      ),
      data: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'data'), 'data'),
      mime_type: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'mimeType'), 'mimeType'),
      uri: ACP::Types::Check.string(hash['uri'], 'uri', allow_nil: true),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'type' => 'image',
      'data' => data,
      'mimeType' => mime_type,
      'annotations' => annotations&.to_h,
      'uri' => uri,
      '_meta' => meta
    }.compact
  end
end
