# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ContentBlock::ResourceLink
  # @dynamic annotations
  attr_reader :annotations #: ACP::Types::Annotations?

  # @dynamic description
  attr_reader :description #: String?

  # @dynamic mime_type
  attr_reader :mime_type #: String?

  # @dynamic name
  attr_reader :name #: String

  # @dynamic size
  attr_reader :size #: Integer?

  # @dynamic title
  attr_reader :title #: String?

  # @dynamic uri
  attr_reader :uri #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs annotations: ACP::Types::Annotations?
  # @rbs description: String?
  # @rbs mime_type: String?
  # @rbs name: String
  # @rbs size: Integer?
  # @rbs title: String?
  # @rbs uri: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(name:, uri:, annotations: nil, description: nil, mime_type: nil, size: nil, title: nil, meta: nil)
    @annotations = annotations
    @description = description
    @mime_type = mime_type
    @name = name
    @size = size
    @title = title
    @uri = uri
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ContentBlock::ResourceLink
  def self.from_h(hash)
    new(
      annotations: hash['annotations']&.then { |value| ACP::Types::Annotations.from_h(value) },
      description: hash['description'],
      mime_type: hash['mimeType'],
      name: hash.fetch('name'),
      size: hash['size'],
      title: hash['title'],
      uri: hash.fetch('uri'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'type' => 'resource_link',
      'name' => name,
      'uri' => uri,
      'annotations' => annotations&.to_h,
      'description' => description,
      'mimeType' => mime_type,
      'size' => size,
      'title' => title,
      '_meta' => meta
    }.compact
  end
end
