# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ContentBlock::Resource
  # @dynamic annotations
  attr_reader :annotations #: ACP::Types::Annotations?

  # @dynamic resource
  attr_reader :resource #: ACP::Types::EmbeddedResourceResource::t

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs annotations: ACP::Types::Annotations?
  # @rbs resource: ACP::Types::EmbeddedResourceResource::t
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(resource:, annotations: nil, meta: nil)
    @annotations = annotations
    @resource = resource
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ContentBlock::Resource
  def self.from_h(hash)
    new(
      annotations: hash['annotations']&.then { |value| ACP::Types::Annotations.from_h(value) },
      resource: ACP::Types::EmbeddedResourceResource.from_h(hash.fetch('resource')),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'type' => 'resource', 'resource' => resource.to_h, 'annotations' => annotations&.to_h, '_meta' => meta }.compact
  end
end
