# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ContentBlock::Text
  # @dynamic annotations
  attr_reader :annotations #: ACP::Types::Annotations?

  # @dynamic text
  attr_reader :text #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs annotations: ACP::Types::Annotations?
  # @rbs text: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(text:, annotations: nil, meta: nil)
    @annotations = annotations
    @text = text
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ContentBlock::Text
  def self.from_h(hash)
    new(
      annotations: hash['annotations']&.then { |value| ACP::Types::Annotations.from_h(value) },
      text: hash.fetch('text'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'type' => 'text', 'text' => text, 'annotations' => annotations&.to_h, '_meta' => meta }.compact
  end
end
