# frozen_string_literal: true

# Turns the vendored ACP JSON Schema into the frozen value classes under
# lib/acp/types. `files` is pure; the Rakefile does the writing.
module TypeGenerator
  extend self

  NAMESPACE = 'ACP::Types'
  UNSTABLE_NAMESPACE = "#{NAMESPACE}::Unstable".freeze
  HEADER = <<~TEXT
    # frozen_string_literal: true

    # Generated by bin/types from schema/schema.json. Do not edit.
  TEXT
  UNSTABLE_HEADER = <<~TEXT
    # frozen_string_literal: true

    # Generated by bin/types from schema/schema.unstable.json. Do not edit.
    # Unstable: not part of the ACP spec, may change or disappear at any point.
  TEXT
  MAX_LINE_LENGTH = 120

  # schemars flattens these Rust enums into their parent object without naming
  # the field that holds them, so the names follow the Rust SDK's.
  FLATTENED_UNION_ATTRS = {
    'CreateElicitationRequest' => 'mode',
    'CreateElicitationResponse' => 'action',
    'ElicitationFormMode' => 'scope',
    'ElicitationUrlMode' => 'scope',
    'SessionConfigOption' => 'kind',
    'SetSessionConfigOptionRequest' => 'value'
  }.freeze

  # The schema can't mark where null differs from absent; these fields document "Set to null to clear".
  CLEARABLE = { 'SessionInfoUpdate' => %w[title updatedAt] }.freeze

  ALIASES = {
    'SessionListRequest' => 'ListSessionsRequest',
    'SessionListResponse' => 'ListSessionsResponse',
    'SessionLoadRequest' => 'LoadSessionRequest',
    'SessionNewRequest' => 'NewSessionRequest',
    'SessionPromptRequest' => 'PromptRequest'
  }.freeze

  # Ruby reserved words can't be local variables or plain identifiers in the
  # generated from_h/to_h bodies, so their attrs get a trailing underscore;
  # the JSON key stays as the schema spells it.
  RUBY_KEYWORDS = %w[
    __ENCODING__ __LINE__ __FILE__ BEGIN END alias and begin break case class
    def defined? do else elsif end ensure false for if in module next nil not
    or redo rescue retry return self super then true undef unless until when
    while yield
  ].freeze

  PRIMITIVES = { 'boolean' => 'bool', 'integer' => 'Integer', 'number' => 'Numeric', 'string' => 'String' }.freeze

  # Ruby classes a primitive union accepts, in the schema's variant order.
  RUBY_CLASSES = {
    'boolean' => %w[TrueClass FalseClass],
    'integer' => %w[Integer],
    'number' => %w[Numeric],
    'string' => %w[String]
  }.freeze

  CHECK = 'ACP::Types::Check'

  # A variant class named after one of these would shadow it in the RBS of its
  # union's namespace, where the generated signatures refer to it unqualified.
  CORE_CLASSES = %w[Array Hash Integer Numeric String].freeze

  RAW_HASH = 'Hash[String, untyped]'

  TYPELESS_PROPERTY_KEYS = %w[type $ref allOf anyOf].freeze

  class Type
    attr_reader :rbs, :from, :to, :check

    # `check` describes how from_h validates the value, as a tagged array the
    # `guard` case turns into a Check call: [:string], [:boolean],
    # [:integer, min, max], [:number, min, max], [:enum, values],
    # [:one_of, classes], [:hash, inner], [:array, inner], [:object, const] or
    # [:objects, const]. nil means the value passes through unvalidated.
    def initialize(rbs:, from: nil, to: nil, nullable: false, check: nil)
      @rbs = rbs
      @from = from
      @to = to
      @nullable = nullable
      @check = check
      freeze
    end

    def nullable? = @nullable
  end

  class Field
    attr_reader :json, :attr, :type

    # A flattened field has no JSON key: schemars merges its union variant's properties into the parent.
    def initialize(attr:, type:, required:, nullable:, json: nil, clearable: false, flattened: false)
      @json = json
      @attr = attr
      @type = type
      @required = required
      @nullable = nullable
      @clearable = clearable
      @flattened = flattened
      freeze
    end

    def required? = @required
    def nullable? = @nullable
    def clearable? = @clearable
    def flattened? = @flattened
    def nilable? = !required? || nullable?
  end

  # The defs of one generation pass. In the unstable pass `twins` marks the
  # defs generated under the unstable namespace; every other def resolves to
  # the identical stable class.
  class Schema
    attr_reader :header

    def initialize(defs, header: HEADER, twins: nil)
      @defs = defs
      @header = header
      @twins = twins
      freeze
    end

    def fetch(name) = @defs.fetch(name)
    def const(name) = "#{@twins&.include?(name) ? UNSTABLE_NAMESPACE : NAMESPACE}::#{name}"
    def generated?(name) = @twins.nil? || @twins.include?(name)
  end

  class Dispatch
    attr_reader :tag, :tagged, :untagged

    def initialize(tag:, tagged:, untagged:)
      @tag = tag
      @tagged = tagged
      @untagged = untagged
      freeze
    end
  end

  def files(schema, unstable_schema = nil)
    defs = schema.fetch('$defs')
    roots = defs.select { |_, definition| definition.key?('x-method') }.keys
    stable = reachable(defs, roots, [])
             .flat_map { |name| definition_files(Schema.new(defs), name) }
             .concat(ALIASES.map { |name, target| alias_file(name, target) })
             .sort
             .to_h
    return stable unless unstable_schema

    stable.merge(unstable_files(defs, unstable_schema))
  end

  private

  # The unstable pass generates the defs the stable schema does not already
  # cover: defs unique to the unstable schema and shared defs whose unstable
  # form differs (extra fields or union variants). Identical defs resolve to
  # the stable classes, so the stable namespace is byte-identical whether or
  # not a caller opts in.
  def unstable_files(defs, unstable_schema)
    unstable_defs = unstable_schema.fetch('$defs')
    twins = unstable_defs.reject { |name, definition| defs[name] == definition }.keys
    roots = unstable_defs.select { |_, definition| definition.key?('x-method') }.keys
    schema = Schema.new(unstable_defs, header: UNSTABLE_HEADER, twins:)
    generated = reachable(unstable_defs, roots, []).flat_map { |name| definition_files(schema, name) }.sort.to_h
    generated.merge(opt_in_file(generated.keys))
  end

  # lib/acp/types/unstable.rb is the opt-in: the only entry into
  # lib/acp/types/unstable, which Zeitwerk ignores so nothing loads until a
  # caller requires this file.
  def opt_in_file(paths)
    requires = paths.map { |path| "require_relative '#{path.delete_suffix('.rb')}'" }
    { 'unstable.rb' => <<~RUBY }
      # frozen_string_literal: true

      # Generated by bin/types from schema/schema.unstable.json. Do not edit.
      #
      # Callers opt into the unstable types with `require 'acp/types/unstable'`.
      # Zeitwerk ignores lib/acp/types/unstable, so referencing
      # ACP::Types::Unstable without this require raises NameError.
      # These types are not part of the ACP spec and may change or disappear at
      # any point; the stable ACP::Types namespace is unaffected.

      module ACP::Types::Unstable
      end

      #{requires.join("\n")}
    RUBY
  end

  def reachable(defs, pending, seen)
    return seen if pending.empty?

    name, *rest = pending
    return reachable(defs, rest, seen) if seen.include?(name)

    reachable(defs, rest + refs(defs.fetch(name)), seen + [name])
  end

  def refs(node)
    case node
    when Hash then node.flat_map { |key, value| key == '$ref' ? [ref_name(value)] : refs(value) }
    when Array then node.flat_map { |value| refs(value) }
    else []
    end
  end

  def ref_name(ref) = ref.delete_prefix('#/$defs/')

  def const(name) = "#{NAMESPACE}::#{name}"

  def path(const)
    "#{const.delete_prefix("#{NAMESPACE}::").split('::').map { |part| snake(part) }.join('/')}.rb"
  end

  def snake(name) = name.delete_prefix('_').gsub(/([a-z\d])([A-Z])/, '\1_\2').downcase

  def camel(name) = name.split(/[^a-zA-Z\d]/).map(&:capitalize).join

  def variants(definition) = definition['oneOf'] || definition['anyOf']

  def kind(definition)
    options = variants(definition)
    if definition.key?('properties') then :object
    elsif options.nil? then :primitive
    elsif options.all? { |option| option.key?('const') || (!object_like?(option) && option.key?('title')) } &&
          options.any? { |option| option.key?('const') }
      :enum
    elsif options.all? { |option| option['type'] == 'array' } then :array_union
    elsif options.none? { |option| object_like?(option) } then :primitive_union
    else :union
    end
  end

  def object_like?(schema) = schema.key?('properties') || schema.key?('allOf') || schema['type'] == 'object'

  def definition_files(defs, name)
    return [] unless defs.generated?(name)

    definition = defs.fetch(name)
    case kind(definition)
    when :object then object_files(defs, name)
    when :union then union_files(defs, defs.const(name), definition)
    when :array_union then [array_union_file(defs, defs.const(name), definition)]
    when :enum then [enum_file(defs, defs.const(name), definition)]
    else []
    end
  end

  def resolve(defs, schema)
    if (ref = schema['$ref']) then resolve_ref(defs, ref_name(ref))
    elsif (options = schema['allOf'] || schema['anyOf'])
      resolve(defs, options.find { |option| option['type'] != 'null' })
    else
      resolve_inline(defs, schema)
    end
  end

  def resolve_inline(defs, schema)
    case Array(schema['type']) - ['null']
    in ['array']
      item = resolve(defs, schema.fetch('items'))
      Type.new(
        rbs: "Array[#{item.rbs}]",
        from: elementwise(:map, item.from),
        to: elementwise(:map, item.to),
        check: item.check && [:array, item.check]
      )
    in ['object']
      values = schema['additionalProperties']
      return Type.new(rbs: RAW_HASH) unless values.is_a?(Hash)

      value = resolve(defs, values)
      Type.new(
        rbs: "Hash[String, #{value.rbs}]",
        from: elementwise(:transform_values, value.from),
        to: elementwise(:transform_values, value.to),
        check: value.check && [:hash, value.check]
      )
    in [type] then Type.new(rbs: PRIMITIVES.fetch(type), check: primitive_check(schema, type))
    in [] then Type.new(rbs: 'untyped')
    end
  end

  def primitive_check(schema, type)
    case type
    when 'boolean' then [:boolean]
    when 'integer' then [:integer, schema['minimum'], schema['maximum']]
    when 'number' then [:number, schema['minimum'], schema['maximum']]
    else [:string]
    end
  end

  def resolve_ref(defs, name)
    definition = defs.fetch(name)
    case kind(definition)
    when :object
      klass = defs.const(name)
      Type.new(rbs: klass, from: [:call, "#{klass}.from_h"], to: [:send, 'to_h'], check: [:object, klass])
    when :union
      klass = defs.const(name)
      Type.new(rbs: "#{klass}::t", from: [:call, "#{klass}.from_h"], to: [:send, 'to_h'], check: [:object, klass])
    when :array_union
      klass = defs.const(name)
      Type.new(
        rbs: "#{klass}::t",
        from: [:call, "#{klass}.from_a"],
        to: [:map, [:send, 'to_h']],
        check: [:objects, klass]
      )
    when :enum
      options = variants(definition)
      rbs = PRIMITIVES.fetch(options.first.fetch('type'))
      # An open enum's non-const variant accepts unknown values; a closed one
      # rejects them.
      check = [:enum, options.map { |option| option.fetch('const') }] if options.all? { |option| option.key?('const') }
      Type.new(rbs:, check:)
    when :primitive_union
      options = variants(definition)
      types = options.map { |option| option['type'] == 'null' ? 'nil' : resolve(defs, option).rbs }
      non_null = options.reject { |option| option['type'] == 'null' }
      classes = non_null.flat_map { |option| RUBY_CLASSES.fetch(option.fetch('type'), %w[Array]) }
      # A typed-array variant's items are checked by one_of after the Array
      # class matches, so the spec passes the inner item check, not [:array, ...].
      items = non_null.filter_map { |option| resolve(defs, option).check[1] if option['type'] == 'array' }.first
      Type.new(rbs: types.join(' | '), nullable: types.include?('nil'), check: [:one_of, classes, items])
    else resolve(defs, definition)
    end
  end

  def elementwise(method, conversion) = conversion && [method, conversion]

  # Conversions stay tagged arrays rather than POROs: they only exist to be pattern-matched here, and array patterns
  # match the nested shapes (`[:map, [:send, 'to_h']]`) directly.
  def convert(conversion, expression, nilable)
    dot = nilable ? '&.' : '.'
    case conversion
    in nil then expression
    in [:call, callee] if nilable then "#{expression}&.then { |value| #{callee}(value) }"
    in [:call, callee] then "#{callee}(#{expression})"
    in [:send, method] then "#{expression}#{dot}#{method}"
    in [:map | :transform_values => method, [:send, inner]] then "#{expression}#{dot}#{method}(&:#{inner})"
    in [:map | :transform_values => method, inner]
      "#{expression}#{dot}#{method} { |item| #{convert(inner, 'item', false)} }"
    end
  end

  def optional(rbs)
    return rbs if rbs == 'untyped' || rbs.split(' | ').include?('nil')

    rbs.include?('|') ? "(#{rbs})?" : "#{rbs}?"
  end

  def fields(defs, schema, except: [], clearable: [])
    required = schema.fetch('required', [])
    schema.fetch('properties', {}).except(*except).map do |json, property|
      type = resolve(defs, property)
      # A property with no declared type accepts any JSON value, null included,
      # so its nil must survive the optional fields' compaction in to_h.
      untyped = TYPELESS_PROPERTY_KEYS.none? { |key| property.key?(key) }
      nullable = untyped || type.nullable? || Array(property['type']).include?('null') ||
                 Array(property['anyOf']).any? { |option| option['type'] == 'null' }
      Field.new(
        json:,
        attr: RUBY_KEYWORDS.include?(snake(json)) ? "#{snake(json)}_" : snake(json),
        type:,
        required: required.include?(json),
        nullable:,
        clearable: clearable.include?(json)
      )
    end
  end

  def object_fields(defs, name)
    definition = defs.fetch(name)
    plain = fields(defs, definition, clearable: CLEARABLE.fetch(name, []))
    return plain unless variants(definition)

    union = flattened_union(defs, name)
    flattened = Field.new(
      attr: FLATTENED_UNION_ATTRS.fetch(name),
      flattened: true,
      required: true,
      nullable: false,
      type: Type.new(rbs: "#{union}::t", from: [:call, "#{union}.from_h"], to: [:send, 'to_h'])
    )
    [*plain, flattened]
  end

  def object_files(defs, name)
    definition = defs.fetch(name)
    class_file = class_file(defs, defs.const(name), object_fields(defs, name))
    return [class_file] unless variants(definition)

    [class_file, *union_files(defs, flattened_union(defs, name), definition)]
  end

  def flattened_union(defs, name) = "#{defs.const(name)}::#{camel(FLATTENED_UNION_ATTRS.fetch(name))}"

  def class_file(defs, const, fields, tag: nil)
    sections = [
      *fields.map { |field| attr_reader(field) },
      initialize_method(fields),
      from_h_method(const, fields),
      to_h_method(fields, tag)
    ]
    [path(const), source("class #{const}", sections, defs.header)]
  end

  def source(opening, sections, header)
    body = sections.map { |lines| indent(lines, 2).join("\n") }.join("\n\n")
    "#{header}\n#{opening}\n#{body}\nend\n"
  end

  def indent(lines, depth) = lines.map { |line| "#{' ' * depth}#{line}" }

  def rbs_type(field)
    return field.type.rbs unless field.nilable?

    field.clearable? ? "#{optional(field.type.rbs)} | :unset" : optional(field.type.rbs)
  end

  def attr_reader(field)
    ["# @dynamic #{field.attr}", "attr_reader :#{field.attr} #: #{rbs_type(field)}"]
  end

  def initialize_method(fields)
    required, optional = fields.partition(&:required?)
    defaults = optional.map { |field| "#{field.attr}: #{field.clearable? ? ':unset' : 'nil'}" }
    params = [*required.map { |field| "#{field.attr}:" }, *defaults]
    [
      *fields.map { |field| "# @rbs #{field.attr}: #{rbs_type(field)}" },
      '# @rbs return: void',
      *call('def initialize', params, 2),
      *fields.map { |field| "  @#{field.attr} = #{field.attr}" },
      '  freeze',
      'end'
    ]
  end

  # A do...end in a keyword-argument position binds its block to `new`, so
  # fields whose guard takes a block are assigned to locals first.
  def from_h_method(const, fields)
    param = fields.empty? ? '_hash' : 'hash'
    expressions = fields.to_h { |field| [field, from_expression(field)] }
    blocky, _plain = fields.partition { |field| piece_block(expressions.fetch(field)) }
    args = fields.map do |field|
      expression = expressions.fetch(field)
      [field.attr, piece_block(expression) ? nil : expression]
    end
    temps = blocky.map { |field| render(expressions.fetch(field), 4, "#{field.attr} = ") }
    [
      "# @rbs #{param}: #{RAW_HASH}",
      "# @rbs return: #{const}",
      "def self.from_h(#{param})",
      *temps.flat_map { |lines| indent(lines, 2) },
      *indent(new_call(args, 4), 2),
      'end'
    ]
  end

  def new_call(args, column)
    return ['new'] if args.empty?

    single = "new(#{args.map { |name, expr| new_arg(name, expr) }.join(', ')})"
    return [single] if column + single.length <= MAX_LINE_LENGTH

    lines = args.each_with_index.flat_map do |(name, expr), index|
      comma = index == args.size - 1 ? '' : ','
      if expr.nil?
        indent(["#{name}:"], 2).tap { |arg_lines| arg_lines[-1] += comma }
      else
        indent(render(expr, column + 2, "#{name}: ", comma), 2)
      end
    end
    ['new(', *lines, ')']
  end

  def new_arg(name, expr)
    expr.nil? ? "#{name}:" : "#{name}: #{inline(expr)}"
  end

  def arg_comma(size, index)
    index == size - 1 ? '' : ','
  end

  def from_expression(field)
    return convert(field.type.from, 'hash', false) if field.flattened?

    source =
      if field.required?
        ["#{CHECK}.key", ['hash', "'#{field.json}'"], nil, nil]
      elsif field.clearable?
        "hash.fetch('#{field.json}', :unset)"
      else
        "hash['#{field.json}']"
      end
    unless field.type.check
      return convert(field.type.from, source.is_a?(String) ? source : inline(source), field.nilable?)
    end

    guard(field.type.check, source, "'#{field.json}'", field.nilable?, field.clearable?)
  end

  # Builds the guard call for a resolved type as a piece: [callee, args,
  # block, cast]. Top-level guards take the field path as a string; guards
  # nested in a container take the block's `path` parameter, so the Check
  # module can report absolute paths.
  def guard(spec, source, path, nilable, clearable)
    opts = guard_options(nilable, clearable)
    case spec
    in [:string] then ["#{CHECK}.string", [source, path, *opts], nil, nil]
    in [:boolean] then ["#{CHECK}.boolean", [source, path, *opts], nil, nil]
    in [:integer, min, max] then ["#{CHECK}.integer", [source, path, *bounds(min, max), *opts], nil, nil]
    in [:number, min, max] then ["#{CHECK}.number", [source, path, *bounds(min, max), *opts], nil, nil]
    in [:enum, values] then ["#{CHECK}.enum", [source, path, enum_values(values), *opts], nil, nil]
    in [:one_of, classes, items]
      block = items ? ['item, path', guard(items, 'item', 'path', false, false)] : nil
      ["#{CHECK}.one_of", [source, path, "[#{classes.join(', ')}]", *opts], block, nil]
    in [:hash, value]
      ["#{CHECK}.hash", [source, path, *opts], ['value, path', guard(value, 'value', 'path', false, false)], nil]
    in [:array, item]
      ["#{CHECK}.array", [source, path, *opts], ['item, path', guard(item, 'item', 'path', false, false)], nil]
    in [:object, const] then ["#{CHECK}.object", [source, path, const, *opts], nil, nil]
    in [:objects, const] then ["#{CHECK}.objects", [source, path, const, *opts], nil, nil]
    end
  end

  def guard_options(nilable, clearable)
    { allow_nil: nilable, allow_unset: clearable }.select { |_, set| set }.map { |name, _| "#{name}: true" }
  end

  def bounds(min, max)
    { min: min, max: max }.select { |_, value| value }.map { |name, value| "#{name}: #{numeric(value)}" }
  end

  def numeric(value) = value.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\1_').reverse

  def enum_values(values)
    words = values.all?(String) && values.size > 1 && values.all? { |value| value.match?(/\A[\w-]+\z/) }
    return "%w[#{values.join(' ')}]" if words

    "[#{values.map { |value| enum_value(value) }.join(', ')}]"
  end

  def enum_value(value)
    return numeric(value) if value.is_a?(Integer)

    "'#{value.gsub('\\', '\\\\\\\\').gsub("'", "\\\\'")}'"
  end

  def inline(piece)
    return piece if piece.is_a?(String)

    callee, args, block, cast = piece
    rendered = "#{callee}(#{args.map { |arg| inline(arg) }.join(', ')})"
    rendered += " { |#{block[0]}| #{inline(block[1])} }" if block
    rendered += " #{cast}" if cast
    rendered
  end

  def piece_block(piece) = piece.is_a?(Array) ? piece[2] : nil

  # Renders a piece or plain expression as one or more lines. `column` is the
  # final column the first line starts at, `suffix` (e.g. an argument comma)
  # closes the last line; nested lines indent by two.
  def render(piece, column, prefix = '', suffix = '')
    line = "#{prefix}#{inline(piece)}#{suffix}"
    return [line] if column + line.length <= MAX_LINE_LENGTH || piece.is_a?(String)

    callee, args, block, cast = piece
    tail = cast ? " #{cast}" : ''
    rendered_args = args.map { |arg| inline(arg) }.join(', ')
    head = args.empty? ? "#{prefix}#{callee}" : "#{prefix}#{callee}(#{rendered_args})"
    if block && column + "#{head} do |#{block[0]}|".length <= MAX_LINE_LENGTH
      return ["#{head} do |#{block[0]}|", *indent(render(block[1], column + 2), 2), "end#{tail}#{suffix}"]
    end

    lines = args.each_with_index.flat_map do |arg, index|
      indent(render(arg, column + 2, '', arg_comma(args.size, index)), 2)
    end
    return ["#{prefix}#{callee}(", *lines, ")#{tail}#{suffix}"] unless block

    body = indent(render(block[1], column + 2), 2)
    ["#{prefix}#{callee}(", *lines, ") do |#{block[0]}|", *body, "end#{tail}#{suffix}"]
  end

  def to_h_method(fields, tag)
    entry = ->(field) { "'#{field.json}' => #{convert(field.type.to, field.attr, field.nilable?)}" }
    flattened, plain = fields.partition(&:flattened?)
    clearable, settled = plain.partition(&:clearable?)
    required, optional = settled.partition(&:required?)
    nullable, present = required.partition(&:nullable?)
    entries = [*(tag && "'#{tag[0]}' => '#{tag[1]}'"), *(optional.empty? ? required : present + optional).map(&entry)]
    suffix = [
      ('.compact' unless optional.empty?),
      (".merge(#{nullable.map(&entry).join(', ')})" unless optional.empty? || nullable.empty?),
      (".merge({ #{clearable.map(&entry).join(', ')} }.reject { |_, value| value == :unset })" unless clearable.empty?),
      *flattened.map { |field| ".merge(#{field.attr}.to_h)" }
    ].join
    ["# @rbs return: #{RAW_HASH}", 'def to_h', *indent(hash_literal(entries, suffix, 4), 2), 'end']
  end

  def call(prefix, args, column)
    return [prefix] if args.empty?

    single = "#{prefix}(#{args.join(', ')})"
    return [single] if column + single.length <= MAX_LINE_LENGTH

    lines = args.each_with_index.map do |arg, index|
      "#{arg}#{',' unless index == args.size - 1}"
    end
    ["#{prefix}(", *indent(lines, 2), ')']
  end

  def hash_literal(entries, suffix, column)
    single = entries.empty? ? "{}#{suffix}" : "{ #{entries.join(', ')} }#{suffix}"
    return [single] if column + single.length <= MAX_LINE_LENGTH

    ['{', *entries.map { |entry| "  #{entry}," }.tap { |lines| lines[-1] = lines[-1].chomp(',') }, "}#{suffix}"]
  end

  def discriminator(options)
    options.flat_map { |option| option.fetch('properties', {}).select { |_, schema| schema.key?('const') }.keys }
           .uniq
           .then { |keys| keys.size > 1 ? raise("Ambiguous discriminator: #{keys}") : keys.first }
  end

  def union_files(defs, union, definition)
    options = variants(definition).reject { |option| option.key?('not') }
    tag = discriminator(options)
    tagged, untagged = options.partition { |option| tag && option.dig('properties', tag, 'const') }
    tagged_names = variant_names(tagged, tag)
    tag_values = tagged.map { |option| option.dig('properties', tag, 'const') }
    tagged_consts = tagged_names.map { |name| "#{union}::#{name}" }
    tagged_classes = tagged.zip(tagged_consts, tag_values).map do |option, variant, value|
      class_file(defs, variant, variant_fields(defs, option, tag), tag: [tag, value])
    end
    untagged_consts = untagged.map { |option| untagged_const(defs, union, option) }
    untagged_classes = untagged.zip(untagged_consts).filter_map do |option, variant|
      class_file(defs, variant, variant_fields(defs, option, tag)) if variant.start_with?("#{union}::")
    end
    dispatch = Dispatch.new(
      tag:,
      tagged: tag_values.zip(tagged_consts),
      untagged: untagged_consts.zip(unique_keys(untagged.map { |option| required_keys(defs, option) }))
    )
    [union_file(defs, union, dispatch), *tagged_classes, *untagged_classes]
  end

  def variant_names(options, tag)
    names = options.map { |option| camel(option.dig('properties', tag, 'const')) }
    return names unless names.intersect?(CORE_CLASSES)

    options.map { |option| variant_ref(option) }
  end

  def variant_ref(option) = option['allOf']&.first&.then { |schema| ref_name(schema.fetch('$ref')) }

  def variant_fields(defs, option, tag)
    inline = fields(defs, option, except: [tag].compact)
    ref = variant_ref(option)
    ref ? inline + object_fields(defs, ref) : inline
  end

  def untagged_const(defs, union, option)
    ref = variant_ref(option)
    return defs.const(ref) if ref && !option.key?('properties') && kind(defs.fetch(ref)) == :object

    "#{union}::#{camel(option.fetch('title'))}"
  end

  def required_keys(defs, option)
    ref = variant_ref(option)
    option.fetch('required', []) + (ref ? defs.fetch(ref).fetch('required', []) : [])
  end

  def unique_keys(key_sets)
    key_sets.each_with_index.map do |keys, index|
      others = key_sets.reject.with_index { |_, other| other == index }.flatten
      (keys - others).first or raise "No distinguishing key among #{key_sets}"
    end
  end

  def union_file(defs, union, dispatch)
    variants = [*dispatch.tagged.map(&:last), *dispatch.untagged.map(&:first), RAW_HASH]
    from_h = [
      "# @rbs hash: #{RAW_HASH}",
      '# @rbs return: t',
      'def self.from_h(hash)',
      *indent(dispatch_body(dispatch), 2),
      'end'
    ]
    [path(union), source("module #{union}", [type_alias(variants), from_h], defs.header)]
  end

  def type_alias(types)
    ['# @rbs!', "#   type t = #{types.first}", *types.drop(1).map { |type| "#          | #{type}" }]
  end

  def dispatch_body(dispatch)
    unless dispatch.tag
      branches = dispatch.untagged.map { |variant, key| ["hash.key?('#{key}')", ["#{variant}.from_h(hash)"]] }
      return key_dispatch(branches, 'hash')
    end

    raise "Several untagged variants alongside #{dispatch.tag}" if dispatch.untagged.size > 1

    [
      "case hash['#{dispatch.tag}']",
      *dispatch.tagged.map { |value, variant| "when '#{value}' then #{variant}.from_h(hash)" },
      *dispatch.untagged.map { |variant, _| "when nil then #{variant}.from_h(hash)" },
      'else hash',
      'end'
    ]
  end

  def key_dispatch(branches, fallback)
    [
      *branches.each_with_index.flat_map do |(condition, result), index|
        ["#{index.zero? ? 'if' : 'elsif'} #{condition}", *indent(result, 2)]
      end,
      'else',
      "  #{fallback}",
      'end'
    ]
  end

  def array_union_file(defs, union, definition)
    items = variants(definition).map { |option| ref_name(option.fetch('items').fetch('$ref')) }
    keys = unique_keys(items.map { |name| defs.fetch(name).fetch('required', []) })
    branches = items.zip(keys).map do |name, key|
      [
        "items.all? { |item| item.key?('#{key}') }",
        # The index segment makes a variant's parse failure report its position,
        # and the cast keeps Steep from checking the branch against the first
        # member of `t` only.
        render(
          ['items.each_with_index.map', [],
           ['item, index', ["#{CHECK}.object", ['item', '[index]', defs.const(name)], nil, nil]],
           "#: Array[#{defs.const(name)}]"],
          6
        )
      ]
    end
    from_a = [
      "# @rbs items: Array[#{RAW_HASH}]",
      '# @rbs return: t',
      'def self.from_a(items)',
      *indent(key_dispatch(branches, 'items'), 2),
      'end'
    ]
    types = [*items.map { |name| "Array[#{defs.const(name)}]" }, "Array[#{RAW_HASH}]"]
    [path(union), source("module #{union}", [type_alias(types), from_a], defs.header)]
  end

  def enum_file(defs, const, definition)
    constants = variants(definition).select { |option| option.key?('const') }.map do |option|
      value = option.fetch('const')
      name = (value.is_a?(String) ? value : option.fetch('title')).upcase.gsub(/[^A-Z\d]+/, '_')
      "#{name} = #{value.is_a?(String) ? "'#{value}'" : value}"
    end
    [path(const), source("module #{const}", [constants], defs.header)]
  end

  def alias_file(name, target)
    rbs = "# @rbs!\n#   class #{const(name)} = #{const(target)}\n"
    [path(const(name)), "#{HEADER}\n#{rbs}\n#{const(name)} = #{const(target)}\n"]
  end
end
