# frozen_string_literal: true

# Turns the vendored ACP JSON Schema into the frozen value classes under
# lib/acp/types. `files` is pure; the Rakefile does the writing. The stages
# share the POROs and schema-wide constants declared here: Plan decides which
# defs exist and which files they become, Resolve turns schema JSON into
# Type/Field, Emit renders those as Ruby source, and Unions emits the union,
# array-union, and enum strategies.
module TypeGenerator
  extend self

  NAMESPACE = 'ACP::Types'
  UNSTABLE_NAMESPACE = "#{NAMESPACE}::Unstable".freeze
  HEADER = <<~TEXT
    # frozen_string_literal: true

    # Generated by bin/types from schema/schema.json. Do not edit.
  TEXT
  UNSTABLE_HEADER = <<~TEXT
    # frozen_string_literal: true

    # Generated by bin/types from schema/schema.unstable.json. Do not edit.
    # Unstable: not part of the ACP spec, may change or disappear at any point.
  TEXT
  MAX_LINE_LENGTH = 120

  # schemars flattens these Rust enums into their parent object without naming
  # the field that holds them, so the names follow the Rust SDK's.
  FLATTENED_UNION_ATTRS = {
    'CreateElicitationRequest' => 'mode',
    'CreateElicitationResponse' => 'action',
    'ElicitationFormMode' => 'scope',
    'ElicitationUrlMode' => 'scope',
    'SessionConfigOption' => 'kind',
    'SetSessionConfigOptionRequest' => 'value'
  }.freeze

  # The schema can't mark where null differs from absent; these fields document "Set to null to clear".
  CLEARABLE = { 'SessionInfoUpdate' => %w[title updatedAt] }.freeze

  ALIASES = {
    'SessionListRequest' => 'ListSessionsRequest',
    'SessionListResponse' => 'ListSessionsResponse',
    'SessionLoadRequest' => 'LoadSessionRequest',
    'SessionNewRequest' => 'NewSessionRequest',
    'SessionPromptRequest' => 'PromptRequest'
  }.freeze

  # Ruby reserved words can't be local variables or plain identifiers in the
  # generated from_h/to_h bodies, so their attrs get a trailing underscore;
  # the JSON key stays as the schema spells it.
  RUBY_KEYWORDS = %w[
    __ENCODING__ __LINE__ __FILE__ BEGIN END alias and begin break case class
    def defined? do else elsif end ensure false for if in module next nil not
    or redo rescue retry return self super then true undef unless until when
    while yield
  ].freeze

  PRIMITIVES = { 'boolean' => 'bool', 'integer' => 'Integer', 'number' => 'Numeric', 'string' => 'String' }.freeze

  # Ruby classes a primitive union accepts, in the schema's variant order.
  RUBY_CLASSES = {
    'boolean' => %w[TrueClass FalseClass],
    'integer' => %w[Integer],
    'number' => %w[Numeric],
    'string' => %w[String]
  }.freeze

  CHECK = 'ACP::Types::Check'

  # A variant class named after one of these would shadow it in the RBS of its
  # union's namespace, where the generated signatures refer to it unqualified.
  CORE_CLASSES = %w[Array Hash Integer Numeric String].freeze

  RAW_HASH = 'Hash[String, untyped]'

  TYPELESS_PROPERTY_KEYS = %w[type $ref allOf anyOf].freeze

  class Type
    attr_reader :rbs, :from, :to, :check

    # `check` describes how from_h validates the value, as a tagged array the
    # `guard` case turns into a Check call: [:string], [:boolean],
    # [:integer, min, max], [:number, min, max], [:enum, values],
    # [:one_of, classes], [:hash, inner], [:array, inner], [:object, const] or
    # [:objects, const]. nil means the value passes through unvalidated.
    def initialize(rbs:, from: nil, to: nil, nullable: false, check: nil)
      @rbs = rbs
      @from = from
      @to = to
      @nullable = nullable
      @check = check
      freeze
    end

    def nullable? = @nullable
  end

  class Field
    attr_reader :json, :attr, :type

    # A flattened field has no JSON key: schemars merges its union variant's properties into the parent.
    def initialize(attr:, type:, required:, nullable:, json: nil, clearable: false, flattened: false)
      @json = json
      @attr = attr
      @type = type
      @required = required
      @nullable = nullable
      @clearable = clearable
      @flattened = flattened
      freeze
    end

    def required? = @required
    def nullable? = @nullable
    def clearable? = @clearable
    def flattened? = @flattened
    def nilable? = !required? || nullable?
  end

  # The defs of one generation pass. In the unstable pass `twins` marks the
  # defs generated under the unstable namespace; every other def resolves to
  # the identical stable class.
  class Schema
    attr_reader :header

    def initialize(defs, header: HEADER, twins: nil)
      @defs = defs
      @header = header
      @twins = twins
      freeze
    end

    def fetch(name) = @defs.fetch(name)
    def const(name) = "#{@twins&.include?(name) ? UNSTABLE_NAMESPACE : NAMESPACE}::#{name}"
    def generated?(name) = @twins.nil? || @twins.include?(name)
  end

  class Dispatch
    attr_reader :tag, :tagged, :untagged

    def initialize(tag:, tagged:, untagged:)
      @tag = tag
      @tagged = tagged
      @untagged = untagged
      freeze
    end
  end

  def files(schema, unstable_schema = nil) = Plan.files(schema, unstable_schema)
end

# The stages open `TypeGenerator::Plan`-style namespaces, so the hub module
# above must exist before they load.
require_relative 'type_generator/emit'
require_relative 'type_generator/plan'
require_relative 'type_generator/resolve'
require_relative 'type_generator/unions'
