# frozen_string_literal: true

# Turns the vendored ACP JSON Schema into the frozen value classes under
# lib/acp/types. `files` is pure; the Rakefile does the writing.
module TypeGenerator
  extend self

  NAMESPACE = 'ACP::Types'
  HEADER = "# frozen_string_literal: true\n\n# Generated by bin/types from schema/schema.json. Do not edit.\n"
  MAX_LINE_LENGTH = 120

  # schemars flattens these Rust enums into their parent object without naming
  # the field that holds them, so the names follow the Rust SDK's.
  FLATTENED_UNION_ATTRS = {
    'CreateElicitationRequest' => 'mode',
    'CreateElicitationResponse' => 'action',
    'ElicitationFormMode' => 'scope',
    'ElicitationUrlMode' => 'scope',
    'SessionConfigOption' => 'kind',
    'SetSessionConfigOptionRequest' => 'value'
  }.freeze

  # The schema can't mark where null differs from absent; these fields document "Set to null to clear".
  CLEARABLE = { 'SessionInfoUpdate' => %w[title updatedAt] }.freeze

  ALIASES = {
    'SessionListRequest' => 'ListSessionsRequest',
    'SessionListResponse' => 'ListSessionsResponse',
    'SessionLoadRequest' => 'LoadSessionRequest',
    'SessionNewRequest' => 'NewSessionRequest',
    'SessionPromptRequest' => 'PromptRequest'
  }.freeze

  PRIMITIVES = { 'boolean' => 'bool', 'integer' => 'Integer', 'number' => 'Numeric', 'string' => 'String' }.freeze

  # A variant class named after one of these would shadow it in the RBS of its
  # union's namespace, where the generated signatures refer to it unqualified.
  CORE_CLASSES = %w[Array Hash Integer Numeric String].freeze

  RAW_HASH = 'Hash[String, untyped]'

  def files(schema)
    defs = schema.fetch('$defs')
    roots = defs.select { |_, definition| definition.key?('x-method') }.keys
    reachable(defs, roots, [])
      .flat_map { |name| definition_files(defs, name) }
      .concat(ALIASES.map { |name, target| alias_file(name, target) })
      .sort
      .to_h
  end

  private

  def reachable(defs, pending, seen)
    return seen if pending.empty?

    name, *rest = pending
    return reachable(defs, rest, seen) if seen.include?(name)

    reachable(defs, rest + refs(defs.fetch(name)), seen + [name])
  end

  def refs(node)
    case node
    when Hash then node.flat_map { |key, value| key == '$ref' ? [ref_name(value)] : refs(value) }
    when Array then node.flat_map { |value| refs(value) }
    else []
    end
  end

  def ref_name(ref) = ref.delete_prefix('#/$defs/')

  def const(name) = "#{NAMESPACE}::#{name}"

  def path(const)
    "#{const.delete_prefix("#{NAMESPACE}::").split('::').map { |part| snake(part) }.join('/')}.rb"
  end

  def snake(name) = name.delete_prefix('_').gsub(/([a-z\d])([A-Z])/, '\1_\2').downcase

  def camel(name) = name.split(/[^a-zA-Z\d]/).map(&:capitalize).join

  def variants(definition) = definition['oneOf'] || definition['anyOf']

  def kind(definition)
    options = variants(definition)
    if definition.key?('properties') then :object
    elsif options.nil? then :primitive
    elsif options.all? { |option| option.key?('const') || (!object_like?(option) && option.key?('title')) } &&
          options.any? { |option| option.key?('const') }
      :enum
    elsif options.all? { |option| option['type'] == 'array' } then :array_union
    elsif options.none? { |option| object_like?(option) } then :primitive_union
    else :union
    end
  end

  def object_like?(schema) = schema.key?('properties') || schema.key?('allOf') || schema['type'] == 'object'

  def definition_files(defs, name)
    definition = defs.fetch(name)
    case kind(definition)
    when :object then object_files(defs, name)
    when :union then union_files(defs, const(name), definition)
    when :array_union then [array_union_file(defs, const(name), definition)]
    when :enum then [enum_file(const(name), definition)]
    else []
    end
  end

  def resolve(defs, schema)
    if (ref = schema['$ref']) then resolve_ref(defs, ref_name(ref))
    elsif (options = schema['allOf'] || schema['anyOf'])
      resolve(defs, options.find { |option| option['type'] != 'null' })
    else
      resolve_inline(defs, schema)
    end
  end

  def resolve_inline(defs, schema)
    case Array(schema['type']) - ['null']
    in ['array']
      item = resolve(defs, schema.fetch('items'))
      { rbs: "Array[#{item[:rbs]}]", from: elementwise(:map, item[:from]), to: elementwise(:map, item[:to]) }
    in ['object']
      values = schema['additionalProperties']
      return { rbs: RAW_HASH } unless values.is_a?(Hash)

      value = resolve(defs, values)
      { rbs: "Hash[String, #{value[:rbs]}]",
        from: elementwise(:transform_values, value[:from]),
        to: elementwise(:transform_values, value[:to]) }
    in [type] then { rbs: PRIMITIVES.fetch(type) }
    in [] then { rbs: 'untyped' }
    end
  end

  def resolve_ref(defs, name)
    definition = defs.fetch(name)
    case kind(definition)
    when :object then { rbs: const(name), from: [:call, "#{const(name)}.from_h"], to: [:send, 'to_h'] }
    when :union then { rbs: "#{const(name)}::t", from: [:call, "#{const(name)}.from_h"], to: [:send, 'to_h'] }
    when :array_union
      { rbs: "#{const(name)}::t", from: [:call, "#{const(name)}.from_a"], to: [:map, [:send, 'to_h']] }
    when :enum then { rbs: PRIMITIVES.fetch(variants(definition).first.fetch('type')) }
    when :primitive_union
      types = variants(definition).map { |option| option['type'] == 'null' ? 'nil' : resolve(defs, option)[:rbs] }
      { rbs: types.join(' | '), nullable: types.include?('nil') }
    else resolve(defs, definition)
    end
  end

  def elementwise(method, conversion) = conversion && [method, conversion]

  def convert(conversion, expression, nilable)
    dot = nilable ? '&.' : '.'
    case conversion
    in nil then expression
    in [:call, callee] if nilable then "#{expression}&.then { |value| #{callee}(value) }"
    in [:call, callee] then "#{callee}(#{expression})"
    in [:send, method] then "#{expression}#{dot}#{method}"
    in [:map | :transform_values => method, [:send, inner]] then "#{expression}#{dot}#{method}(&:#{inner})"
    in [:map | :transform_values => method, inner]
      "#{expression}#{dot}#{method} { |item| #{convert(inner, 'item', false)} }"
    end
  end

  def optional(rbs)
    return rbs if rbs == 'untyped' || rbs.split(' | ').include?('nil')

    rbs.include?('|') ? "(#{rbs})?" : "#{rbs}?"
  end

  def fields(defs, schema, except: [], clearable: [])
    required = schema.fetch('required', [])
    schema.fetch('properties', {}).except(*except).map do |json, property|
      type = resolve(defs, property)
      nullable = type[:nullable] || Array(property['type']).include?('null') ||
                 Array(property['anyOf']).any? { |option| option['type'] == 'null' }
      { json:, attr: snake(json), type:, required: required.include?(json), nullable:,
        clearable: clearable.include?(json) }
    end
  end

  def object_fields(defs, name)
    definition = defs.fetch(name)
    plain = fields(defs, definition, clearable: CLEARABLE.fetch(name, []))
    return plain unless variants(definition)

    union = flattened_union(name)
    flattened = {
      attr: FLATTENED_UNION_ATTRS.fetch(name), flattened: true, required: true, nullable: false,
      type: { rbs: "#{union}::t", from: [:call, "#{union}.from_h"], to: [:send, 'to_h'] }
    }
    [*plain, flattened]
  end

  def object_files(defs, name)
    definition = defs.fetch(name)
    class_file = class_file(const(name), object_fields(defs, name))
    return [class_file] unless variants(definition)

    [class_file, *union_files(defs, flattened_union(name), definition)]
  end

  def flattened_union(name) = "#{const(name)}::#{camel(FLATTENED_UNION_ATTRS.fetch(name))}"

  def class_file(const, fields, tag: nil)
    sections = [
      *fields.map { |field| attr_reader(field) },
      initialize_method(fields),
      from_h_method(const, fields),
      to_h_method(fields, tag)
    ]
    [path(const), source("class #{const}", sections)]
  end

  def source(opening, sections)
    body = sections.map { |lines| indent(lines, 2).join("\n") }.join("\n\n")
    "#{HEADER}\n#{opening}\n#{body}\nend\n"
  end

  def indent(lines, depth) = lines.map { |line| "#{' ' * depth}#{line}" }

  def rbs_type(field)
    return field[:type][:rbs] unless nilable?(field)

    field[:clearable] ? "#{optional(field[:type][:rbs])} | :unset" : optional(field[:type][:rbs])
  end

  def attr_reader(field)
    ["# @dynamic #{field[:attr]}", "attr_reader :#{field[:attr]} #: #{rbs_type(field)}"]
  end

  def initialize_method(fields)
    required, optional = fields.partition { |field| field[:required] }
    defaults = optional.map { |field| "#{field[:attr]}: #{field[:clearable] ? ':unset' : 'nil'}" }
    params = [*required.map { |field| "#{field[:attr]}:" }, *defaults]
    [
      *fields.map { |field| "# @rbs #{field[:attr]}: #{rbs_type(field)}" },
      '# @rbs return: void',
      *call('def initialize', params, 2),
      *fields.map { |field| "  @#{field[:attr]} = #{field[:attr]}" },
      '  freeze',
      'end'
    ]
  end

  def from_h_method(const, fields)
    param = fields.empty? ? '_hash' : 'hash'
    args = fields.map { |field| "#{field[:attr]}: #{from_expression(field)}" }
    [
      "# @rbs #{param}: #{RAW_HASH}",
      "# @rbs return: #{const}",
      "def self.from_h(#{param})",
      *indent(call('new', args, 4), 2),
      'end'
    ]
  end

  def from_expression(field)
    source =
      if field[:flattened]
        'hash'
      elsif field[:required]
        "hash.fetch('#{field[:json]}')"
      elsif field[:clearable]
        "hash.fetch('#{field[:json]}', :unset)"
      else
        "hash['#{field[:json]}']"
      end
    convert(field[:type][:from], source, nilable?(field))
  end

  def nilable?(field) = !field[:required] || field[:nullable]

  def to_h_method(fields, tag)
    entry = ->(field) { "'#{field[:json]}' => #{convert(field[:type][:to], field[:attr], nilable?(field))}" }
    flattened, plain = fields.partition { |field| field[:flattened] }
    clearable, settled = plain.partition { |field| field[:clearable] }
    optional, required = settled.partition { |field| !field[:required] }
    nullable, present = required.partition { |field| field[:nullable] }
    entries = [*(tag && "'#{tag[0]}' => '#{tag[1]}'"), *(optional.empty? ? required : present + optional).map(&entry)]
    suffix = [
      ('.compact' unless optional.empty?),
      (".merge(#{nullable.map(&entry).join(', ')})" unless optional.empty? || nullable.empty?),
      (".merge({ #{clearable.map(&entry).join(', ')} }.reject { |_, value| value == :unset })" unless clearable.empty?),
      *flattened.map { |field| ".merge(#{field[:attr]}.to_h)" }
    ].join
    ["# @rbs return: #{RAW_HASH}", 'def to_h', *indent(hash_literal(entries, suffix, 4), 2), 'end']
  end

  def call(prefix, args, column)
    return [prefix] if args.empty?

    single = "#{prefix}(#{args.join(', ')})"
    return [single] if column + single.length <= MAX_LINE_LENGTH

    lines = args.each_with_index.flat_map do |arg, index|
      block_lines("#{arg}#{',' unless index == args.size - 1}", column + 2)
    end
    ["#{prefix}(", *indent(lines, 2), ')']
  end

  def block_lines(line, column)
    match = line.match(/\A(.+) \{ (\|\w+\|) (.+) \}(,?)\z/)
    return [line] if match.nil? || column + line.length <= MAX_LINE_LENGTH

    ["#{match[1]} do #{match[2]}", "  #{match[3]}", "end#{match[4]}"]
  end

  def hash_literal(entries, suffix, column)
    single = entries.empty? ? "{}#{suffix}" : "{ #{entries.join(', ')} }#{suffix}"
    return [single] if column + single.length <= MAX_LINE_LENGTH

    ['{', *entries.map { |entry| "  #{entry}," }.tap { |lines| lines[-1] = lines[-1].chomp(',') }, "}#{suffix}"]
  end

  def discriminator(options)
    options.flat_map { |option| option.fetch('properties', {}).select { |_, schema| schema.key?('const') }.keys }
           .uniq
           .then { |keys| keys.size > 1 ? raise("Ambiguous discriminator: #{keys}") : keys.first }
  end

  def union_files(defs, union, definition)
    options = variants(definition).reject { |option| option.key?('not') }
    tag = discriminator(options)
    tagged, untagged = options.partition { |option| tag && option.dig('properties', tag, 'const') }
    tagged_names = variant_names(tagged, tag)
    tag_values = tagged.map { |option| option.dig('properties', tag, 'const') }
    tagged_consts = tagged_names.map { |name| "#{union}::#{name}" }
    tagged_classes = tagged.zip(tagged_consts, tag_values).map do |option, variant, value|
      class_file(variant, variant_fields(defs, option, tag), tag: [tag, value])
    end
    untagged_consts = untagged.map { |option| untagged_const(defs, union, option) }
    untagged_classes = untagged.zip(untagged_consts).filter_map do |option, variant|
      class_file(variant, variant_fields(defs, option, tag)) if variant.start_with?("#{union}::")
    end
    dispatch = {
      tag:,
      tagged: tag_values.zip(tagged_consts),
      untagged: untagged_consts.zip(unique_keys(untagged.map { |option| required_keys(defs, option) }))
    }
    [union_file(union, dispatch), *tagged_classes, *untagged_classes]
  end

  def variant_names(options, tag)
    names = options.map { |option| camel(option.dig('properties', tag, 'const')) }
    return names unless names.intersect?(CORE_CLASSES)

    options.map { |option| variant_ref(option) }
  end

  def variant_ref(option) = option['allOf']&.first&.then { |schema| ref_name(schema.fetch('$ref')) }

  def variant_fields(defs, option, tag)
    inline = fields(defs, option, except: [tag].compact)
    ref = variant_ref(option)
    ref ? inline + object_fields(defs, ref) : inline
  end

  def untagged_const(defs, union, option)
    ref = variant_ref(option)
    return const(ref) if ref && !option.key?('properties') && kind(defs.fetch(ref)) == :object

    "#{union}::#{camel(option.fetch('title'))}"
  end

  def required_keys(defs, option)
    ref = variant_ref(option)
    option.fetch('required', []) + (ref ? defs.fetch(ref).fetch('required', []) : [])
  end

  def unique_keys(key_sets)
    key_sets.each_with_index.map do |keys, index|
      others = key_sets.reject.with_index { |_, other| other == index }.flatten
      (keys - others).first or raise "No distinguishing key among #{key_sets}"
    end
  end

  def union_file(union, dispatch)
    variants = [*dispatch[:tagged].map(&:last), *dispatch[:untagged].map(&:first), RAW_HASH]
    from_h = [
      "# @rbs hash: #{RAW_HASH}",
      '# @rbs return: t',
      'def self.from_h(hash)',
      *indent(dispatch_body(dispatch), 2),
      'end'
    ]
    [path(union), source("module #{union}", [type_alias(variants), from_h])]
  end

  def type_alias(types)
    ['# @rbs!', "#   type t = #{types.first}", *types.drop(1).map { |type| "#          | #{type}" }]
  end

  def dispatch_body(dispatch)
    unless dispatch[:tag]
      branches = dispatch[:untagged].map { |variant, key| ["hash.key?('#{key}')", "#{variant}.from_h(hash)"] }
      return key_dispatch(branches, 'hash')
    end

    raise "Several untagged variants alongside #{dispatch[:tag]}" if dispatch[:untagged].size > 1

    [
      "case hash['#{dispatch[:tag]}']",
      *dispatch[:tagged].map { |value, variant| "when '#{value}' then #{variant}.from_h(hash)" },
      *dispatch[:untagged].map { |variant, _| "when nil then #{variant}.from_h(hash)" },
      'else hash',
      'end'
    ]
  end

  def key_dispatch(branches, fallback)
    [
      *branches.each_with_index.flat_map do |(condition, result), index|
        ["#{index.zero? ? 'if' : 'elsif'} #{condition}", "  #{result}"]
      end,
      'else',
      "  #{fallback}",
      'end'
    ]
  end

  def array_union_file(defs, union, definition)
    items = variants(definition).map { |option| ref_name(option.fetch('items').fetch('$ref')) }
    keys = unique_keys(items.map { |name| defs.fetch(name).fetch('required', []) })
    branches = items.zip(keys).map do |name, key|
      [
        "items.all? { |item| item.key?('#{key}') }",
        # Steep checks every branch against the first member of `t` otherwise.
        "items.map { |item| #{const(name)}.from_h(item) } #: Array[#{const(name)}]"
      ]
    end
    from_a = [
      "# @rbs items: Array[#{RAW_HASH}]",
      '# @rbs return: t',
      'def self.from_a(items)',
      *indent(key_dispatch(branches, 'items'), 2),
      'end'
    ]
    types = [*items.map { |name| "Array[#{const(name)}]" }, "Array[#{RAW_HASH}]"]
    [path(union), source("module #{union}", [type_alias(types), from_a])]
  end

  def enum_file(const, definition)
    constants = variants(definition).select { |option| option.key?('const') }.map do |option|
      value = option.fetch('const')
      name = (value.is_a?(String) ? value : option.fetch('title')).upcase.gsub(/[^A-Z\d]+/, '_')
      "#{name} = #{value.is_a?(String) ? "'#{value}'" : value}"
    end
    [path(const), source("module #{const}", [constants])]
  end

  def alias_file(name, target)
    rbs = "# @rbs!\n#   class #{const(name)} = #{const(target)}\n"
    [path(const(name)), "#{HEADER}\n#{rbs}\n#{const(name)} = #{const(target)}\n"]
  end
end
