# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::McpServer::Sse
  # @dynamic name
  attr_reader :name #: String

  # @dynamic url
  attr_reader :url #: String

  # @dynamic headers
  attr_reader :headers #: Array[ACP::Types::HttpHeader]

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs name: String
  # @rbs url: String
  # @rbs headers: Array[ACP::Types::HttpHeader]
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(name:, url:, headers:, meta: nil)
    @name = name
    @url = url
    @headers = headers
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::McpServer::Sse
  def self.from_h(hash)
    new(
      name: hash.fetch('name'),
      url: hash.fetch('url'),
      headers: hash.fetch('headers').map { |item| ACP::Types::HttpHeader.from_h(item) },
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'type' => 'sse', 'name' => name, 'url' => url, 'headers' => headers.map(&:to_h), '_meta' => meta }.compact
  end
end
