# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::McpServer::Http
  # @dynamic name
  attr_reader :name #: String

  # @dynamic url
  attr_reader :url #: String

  # @dynamic headers
  attr_reader :headers #: Array[ACP::Types::HttpHeader]

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs name: String
  # @rbs url: String
  # @rbs headers: Array[ACP::Types::HttpHeader]
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(name:, url:, headers:, meta: nil)
    @name = name
    @url = url
    @headers = headers
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::McpServer::Http
  def self.from_h(hash)
    headers = ACP::Types::Check.array(ACP::Types::Check.key(hash, 'headers'), 'headers') do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::HttpHeader)
    end
    new(
      name: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'name'), 'name'),
      url: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'url'), 'url'),
      headers:,
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'type' => 'http', 'name' => name, 'url' => url, 'headers' => headers.map(&:to_h), '_meta' => meta }.compact
  end
end
