# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::PlanUpdateContent::File
  # @dynamic plan_id
  attr_reader :plan_id #: String

  # @dynamic uri
  attr_reader :uri #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs plan_id: String
  # @rbs uri: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(plan_id:, uri:, meta: nil)
    @plan_id = plan_id
    @uri = uri
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::PlanUpdateContent::File
  def self.from_h(hash)
    new(
      plan_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'planId'), 'planId'),
      uri: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'uri'), 'uri'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'type' => 'file', 'planId' => plan_id, 'uri' => uri, '_meta' => meta }.compact
  end
end
