# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::PlanUpdateContent::Markdown
  # @dynamic plan_id
  attr_reader :plan_id #: String

  # @dynamic content
  attr_reader :content #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs plan_id: String
  # @rbs content: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(plan_id:, content:, meta: nil)
    @plan_id = plan_id
    @content = content
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::PlanUpdateContent::Markdown
  def self.from_h(hash)
    new(
      plan_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'planId'), 'planId'),
      content: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'content'), 'content'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'type' => 'markdown', 'planId' => plan_id, 'content' => content, '_meta' => meta }.compact
  end
end
