# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

module ACP::Types::SetSessionConfigOptionRequest::Value
  # @rbs!
  #   type t = ACP::Types::SetSessionConfigOptionRequest::Value::Boolean
  #          | ACP::Types::SetSessionConfigOptionRequest::Value::ValueId
  #          | Hash[String, untyped]

  # @rbs hash: Hash[String, untyped]
  # @rbs return: t
  def self.from_h(hash)
    case hash['type']
    when 'boolean' then ACP::Types::SetSessionConfigOptionRequest::Value::Boolean.from_h(hash)
    when nil then ACP::Types::SetSessionConfigOptionRequest::Value::ValueId.from_h(hash)
    else hash
    end
  end
end
