# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::AgentCapabilities
  # @dynamic load_session
  attr_reader :load_session #: bool?

  # @dynamic prompt_capabilities
  attr_reader :prompt_capabilities #: ACP::Types::PromptCapabilities?

  # @dynamic mcp_capabilities
  attr_reader :mcp_capabilities #: ACP::Types::McpCapabilities?

  # @dynamic session_capabilities
  attr_reader :session_capabilities #: ACP::Types::SessionCapabilities?

  # @dynamic auth
  attr_reader :auth #: ACP::Types::AgentAuthCapabilities?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs load_session: bool?
  # @rbs prompt_capabilities: ACP::Types::PromptCapabilities?
  # @rbs mcp_capabilities: ACP::Types::McpCapabilities?
  # @rbs session_capabilities: ACP::Types::SessionCapabilities?
  # @rbs auth: ACP::Types::AgentAuthCapabilities?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(
    load_session: nil,
    prompt_capabilities: nil,
    mcp_capabilities: nil,
    session_capabilities: nil,
    auth: nil,
    meta: nil
  )
    @load_session = load_session
    @prompt_capabilities = prompt_capabilities
    @mcp_capabilities = mcp_capabilities
    @session_capabilities = session_capabilities
    @auth = auth
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::AgentCapabilities
  def self.from_h(hash)
    new(
      load_session: ACP::Types::Check.boolean(hash['loadSession'], 'loadSession', allow_nil: true),
      prompt_capabilities: ACP::Types::Check.object(
        hash['promptCapabilities'],
        'promptCapabilities',
        ACP::Types::PromptCapabilities,
        allow_nil: true
      ),
      mcp_capabilities: ACP::Types::Check.object(
        hash['mcpCapabilities'],
        'mcpCapabilities',
        ACP::Types::McpCapabilities,
        allow_nil: true
      ),
      session_capabilities: ACP::Types::Check.object(
        hash['sessionCapabilities'],
        'sessionCapabilities',
        ACP::Types::SessionCapabilities,
        allow_nil: true
      ),
      auth: ACP::Types::Check.object(hash['auth'], 'auth', ACP::Types::AgentAuthCapabilities, allow_nil: true),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'loadSession' => load_session,
      'promptCapabilities' => prompt_capabilities&.to_h,
      'mcpCapabilities' => mcp_capabilities&.to_h,
      'sessionCapabilities' => session_capabilities&.to_h,
      'auth' => auth&.to_h,
      '_meta' => meta
    }.compact
  end
end
