# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::AgentAuthCapabilities
  # @dynamic logout
  attr_reader :logout #: ACP::Types::LogoutCapabilities?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs logout: ACP::Types::LogoutCapabilities?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(logout: nil, meta: nil)
    @logout = logout
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::AgentAuthCapabilities
  def self.from_h(hash)
    new(logout: hash['logout']&.then { |value| ACP::Types::LogoutCapabilities.from_h(value) }, meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'logout' => logout&.to_h, '_meta' => meta }.compact
  end
end
