# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::Annotations
  # @dynamic audience
  attr_reader :audience #: Array[String]?

  # @dynamic last_modified
  attr_reader :last_modified #: String?

  # @dynamic priority
  attr_reader :priority #: Numeric?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs audience: Array[String]?
  # @rbs last_modified: String?
  # @rbs priority: Numeric?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(audience: nil, last_modified: nil, priority: nil, meta: nil)
    @audience = audience
    @last_modified = last_modified
    @priority = priority
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Annotations
  def self.from_h(hash)
    new(
      audience: hash['audience'],
      last_modified: hash['lastModified'],
      priority: hash['priority'],
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'audience' => audience, 'lastModified' => last_modified, 'priority' => priority, '_meta' => meta }.compact
  end
end
