# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::Annotations
  # @dynamic audience
  attr_reader :audience #: Array[String]?

  # @dynamic last_modified
  attr_reader :last_modified #: String?

  # @dynamic priority
  attr_reader :priority #: Numeric?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs audience: Array[String]?
  # @rbs last_modified: String?
  # @rbs priority: Numeric?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(audience: nil, last_modified: nil, priority: nil, meta: nil)
    @audience = audience
    @last_modified = last_modified
    @priority = priority
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Annotations
  def self.from_h(hash)
    audience = ACP::Types::Check.array(hash['audience'], 'audience', allow_nil: true) do |item, path|
      ACP::Types::Check.enum(item, path, %w[assistant user])
    end
    new(
      audience:,
      last_modified: ACP::Types::Check.string(hash['lastModified'], 'lastModified', allow_nil: true),
      priority: ACP::Types::Check.number(hash['priority'], 'priority', allow_nil: true),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'audience' => audience, 'lastModified' => last_modified, 'priority' => priority, '_meta' => meta }.compact
  end
end
