# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::AuthMethodTerminal
  # @dynamic id
  attr_reader :id #: String

  # @dynamic name
  attr_reader :name #: String

  # @dynamic description
  attr_reader :description #: String?

  # @dynamic args
  attr_reader :args #: Array[String]?

  # @dynamic env
  attr_reader :env #: Hash[String, String]?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs id: String
  # @rbs name: String
  # @rbs description: String?
  # @rbs args: Array[String]?
  # @rbs env: Hash[String, String]?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(id:, name:, description: nil, args: nil, env: nil, meta: nil)
    @id = id
    @name = name
    @description = description
    @args = args
    @env = env
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::AuthMethodTerminal
  def self.from_h(hash)
    new(
      id: hash.fetch('id'),
      name: hash.fetch('name'),
      description: hash['description'],
      args: hash['args'],
      env: hash['env'],
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'id' => id, 'name' => name, 'description' => description, 'args' => args, 'env' => env, '_meta' => meta }.compact
  end
end
