# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::AuthCapabilities
  # @dynamic terminal
  attr_reader :terminal #: bool?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs terminal: bool?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(terminal: nil, meta: nil)
    @terminal = terminal
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::AuthCapabilities
  def self.from_h(hash)
    new(terminal: ACP::Types::Check.boolean(hash['terminal'], 'terminal', allow_nil: true), meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'terminal' => terminal, '_meta' => meta }.compact
  end
end
