# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

module ACP::Types::AuthMethod
  # @rbs!
  #   type t = ACP::Types::AuthMethod::Terminal
  #          | ACP::Types::AuthMethodAgent
  #          | Hash[String, untyped]

  # @rbs hash: Hash[String, untyped]
  # @rbs return: t
  def self.from_h(hash)
    case hash['type']
    when 'terminal' then ACP::Types::AuthMethod::Terminal.from_h(hash)
    when nil then ACP::Types::AuthMethodAgent.from_h(hash)
    else hash
    end
  end
end
