# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::AuthenticateRequest
  # @dynamic method_id
  attr_reader :method_id #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs method_id: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(method_id:, meta: nil)
    @method_id = method_id
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::AuthenticateRequest
  def self.from_h(hash)
    new(method_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'methodId'), 'methodId'), meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'methodId' => method_id, '_meta' => meta }.compact
  end
end
