# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

# @rbs!
#   class ACP::Types::AuthMethodTerminal = ACP::Types::AuthMethod::Terminal

ACP::Types::AuthMethodTerminal = ACP::Types::AuthMethod::Terminal
