# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

module ACP::Types::AvailableCommandInput
  # @rbs!
  #   type t = ACP::Types::UnstructuredCommandInput
  #          | Hash[String, untyped]

  # @rbs hash: Hash[String, untyped]
  # @rbs return: t
  def self.from_h(hash)
    if hash.key?('hint')
      ACP::Types::UnstructuredCommandInput.from_h(hash)
    else
      hash
    end
  end
end
