# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::AvailableCommand
  # @dynamic name
  attr_reader :name #: String

  # @dynamic description
  attr_reader :description #: String

  # @dynamic input
  attr_reader :input #: ACP::Types::AvailableCommandInput::t?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs name: String
  # @rbs description: String
  # @rbs input: ACP::Types::AvailableCommandInput::t?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(name:, description:, input: nil, meta: nil)
    @name = name
    @description = description
    @input = input
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::AvailableCommand
  def self.from_h(hash)
    new(
      name: hash.fetch('name'),
      description: hash.fetch('description'),
      input: hash['input']&.then { |value| ACP::Types::AvailableCommandInput.from_h(value) },
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'name' => name, 'description' => description, 'input' => input&.to_h, '_meta' => meta }.compact
  end
end
