# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::BlobResourceContents
  # @dynamic blob
  attr_reader :blob #: String

  # @dynamic mime_type
  attr_reader :mime_type #: String?

  # @dynamic uri
  attr_reader :uri #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs blob: String
  # @rbs mime_type: String?
  # @rbs uri: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(blob:, uri:, mime_type: nil, meta: nil)
    @blob = blob
    @mime_type = mime_type
    @uri = uri
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::BlobResourceContents
  def self.from_h(hash)
    new(
      blob: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'blob'), 'blob'),
      mime_type: ACP::Types::Check.string(hash['mimeType'], 'mimeType', allow_nil: true),
      uri: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'uri'), 'uri'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'blob' => blob, 'uri' => uri, 'mimeType' => mime_type, '_meta' => meta }.compact
  end
end
