# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::BooleanPropertySchema
  # @dynamic title
  attr_reader :title #: String?

  # @dynamic description
  attr_reader :description #: String?

  # @dynamic default
  attr_reader :default #: bool?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs title: String?
  # @rbs description: String?
  # @rbs default: bool?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(title: nil, description: nil, default: nil, meta: nil)
    @title = title
    @description = description
    @default = default
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::BooleanPropertySchema
  def self.from_h(hash)
    new(
      title: ACP::Types::Check.string(hash['title'], 'title', allow_nil: true),
      description: ACP::Types::Check.string(hash['description'], 'description', allow_nil: true),
      default: ACP::Types::Check.boolean(hash['default'], 'default', allow_nil: true),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'title' => title, 'description' => description, 'default' => default, '_meta' => meta }.compact
  end
end
