# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::CancelRequestNotification
  # @dynamic request_id
  attr_reader :request_id #: nil | Integer | String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs request_id: nil | Integer | String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(request_id:, meta: nil)
    @request_id = request_id
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::CancelRequestNotification
  def self.from_h(hash)
    new(request_id: hash.fetch('requestId'), meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { '_meta' => meta }.compact.merge('requestId' => request_id)
  end
end
