# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ClientCapabilities
  # @dynamic fs
  attr_reader :fs #: ACP::Types::FileSystemCapabilities?

  # @dynamic terminal
  attr_reader :terminal #: bool?

  # @dynamic session
  attr_reader :session #: ACP::Types::ClientSessionCapabilities?

  # @dynamic auth
  attr_reader :auth #: ACP::Types::AuthCapabilities?

  # @dynamic elicitation
  attr_reader :elicitation #: ACP::Types::ElicitationCapabilities?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs fs: ACP::Types::FileSystemCapabilities?
  # @rbs terminal: bool?
  # @rbs session: ACP::Types::ClientSessionCapabilities?
  # @rbs auth: ACP::Types::AuthCapabilities?
  # @rbs elicitation: ACP::Types::ElicitationCapabilities?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(fs: nil, terminal: nil, session: nil, auth: nil, elicitation: nil, meta: nil)
    @fs = fs
    @terminal = terminal
    @session = session
    @auth = auth
    @elicitation = elicitation
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ClientCapabilities
  def self.from_h(hash)
    new(
      fs: ACP::Types::Check.object(hash['fs'], 'fs', ACP::Types::FileSystemCapabilities, allow_nil: true),
      terminal: ACP::Types::Check.boolean(hash['terminal'], 'terminal', allow_nil: true),
      session: ACP::Types::Check.object(
        hash['session'],
        'session',
        ACP::Types::ClientSessionCapabilities,
        allow_nil: true
      ),
      auth: ACP::Types::Check.object(hash['auth'], 'auth', ACP::Types::AuthCapabilities, allow_nil: true),
      elicitation: ACP::Types::Check.object(
        hash['elicitation'],
        'elicitation',
        ACP::Types::ElicitationCapabilities,
        allow_nil: true
      ),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'fs' => fs&.to_h,
      'terminal' => terminal,
      'session' => session&.to_h,
      'auth' => auth&.to_h,
      'elicitation' => elicitation&.to_h,
      '_meta' => meta
    }.compact
  end
end
