# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ClientSessionCapabilities
  # @dynamic config_options
  attr_reader :config_options #: ACP::Types::SessionConfigOptionsCapabilities?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs config_options: ACP::Types::SessionConfigOptionsCapabilities?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(config_options: nil, meta: nil)
    @config_options = config_options
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ClientSessionCapabilities
  def self.from_h(hash)
    new(
      config_options: hash['configOptions']&.then do |value|
        ACP::Types::SessionConfigOptionsCapabilities.from_h(value)
      end,
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'configOptions' => config_options&.to_h, '_meta' => meta }.compact
  end
end
