# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::CloseSessionRequest
  # @dynamic session_id
  attr_reader :session_id #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs session_id: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(session_id:, meta: nil)
    @session_id = session_id
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::CloseSessionRequest
  def self.from_h(hash)
    new(session_id: hash.fetch('sessionId'), meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'sessionId' => session_id, '_meta' => meta }.compact
  end
end
