# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::CompleteElicitationNotification
  # @dynamic elicitation_id
  attr_reader :elicitation_id #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs elicitation_id: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(elicitation_id:, meta: nil)
    @elicitation_id = elicitation_id
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::CompleteElicitationNotification
  def self.from_h(hash)
    new(elicitation_id: hash.fetch('elicitationId'), meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'elicitationId' => elicitation_id, '_meta' => meta }.compact
  end
end
