# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ConfigOptionUpdate
  # @dynamic config_options
  attr_reader :config_options #: Array[ACP::Types::SessionConfigOption]

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs config_options: Array[ACP::Types::SessionConfigOption]
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(config_options:, meta: nil)
    @config_options = config_options
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ConfigOptionUpdate
  def self.from_h(hash)
    new(
      config_options: hash.fetch('configOptions').map { |item| ACP::Types::SessionConfigOption.from_h(item) },
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'configOptions' => config_options.map(&:to_h), '_meta' => meta }.compact
  end
end
