# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

# @rbs!
#   class ACP::Types::Content = ACP::Types::ToolCallContent::Content

ACP::Types::Content = ACP::Types::ToolCallContent::Content
