# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::Content
  # @dynamic content
  attr_reader :content #: ACP::Types::ContentBlock::t

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs content: ACP::Types::ContentBlock::t
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(content:, meta: nil)
    @content = content
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Content
  def self.from_h(hash)
    new(content: ACP::Types::ContentBlock.from_h(hash.fetch('content')), meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'content' => content.to_h, '_meta' => meta }.compact
  end
end
