# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

module ACP::Types::ContentBlock
  # @rbs!
  #   type t = ACP::Types::ContentBlock::Text
  #          | ACP::Types::ContentBlock::Image
  #          | ACP::Types::ContentBlock::Audio
  #          | ACP::Types::ContentBlock::ResourceLink
  #          | ACP::Types::ContentBlock::Resource
  #          | Hash[String, untyped]

  # @rbs hash: Hash[String, untyped]
  # @rbs return: t
  def self.from_h(hash)
    case hash['type']
    when 'text' then ACP::Types::ContentBlock::Text.from_h(hash)
    when 'image' then ACP::Types::ContentBlock::Image.from_h(hash)
    when 'audio' then ACP::Types::ContentBlock::Audio.from_h(hash)
    when 'resource_link' then ACP::Types::ContentBlock::ResourceLink.from_h(hash)
    when 'resource' then ACP::Types::ContentBlock::Resource.from_h(hash)
    else hash
    end
  end
end
