# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::Cost
  # @dynamic amount
  attr_reader :amount #: Numeric

  # @dynamic currency
  attr_reader :currency #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs amount: Numeric
  # @rbs currency: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(amount:, currency:, meta: nil)
    @amount = amount
    @currency = currency
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Cost
  def self.from_h(hash)
    new(
      amount: ACP::Types::Check.number(ACP::Types::Check.key(hash, 'amount'), 'amount'),
      currency: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'currency'), 'currency'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'amount' => amount, 'currency' => currency, '_meta' => meta }.compact
  end
end
