# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::CreateTerminalRequest
  # @dynamic session_id
  attr_reader :session_id #: String

  # @dynamic command
  attr_reader :command #: String

  # @dynamic args
  attr_reader :args #: Array[String]?

  # @dynamic env
  attr_reader :env #: Array[ACP::Types::EnvVariable]?

  # @dynamic cwd
  attr_reader :cwd #: String?

  # @dynamic output_byte_limit
  attr_reader :output_byte_limit #: Integer?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs session_id: String
  # @rbs command: String
  # @rbs args: Array[String]?
  # @rbs env: Array[ACP::Types::EnvVariable]?
  # @rbs cwd: String?
  # @rbs output_byte_limit: Integer?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(session_id:, command:, args: nil, env: nil, cwd: nil, output_byte_limit: nil, meta: nil)
    @session_id = session_id
    @command = command
    @args = args
    @env = env
    @cwd = cwd
    @output_byte_limit = output_byte_limit
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::CreateTerminalRequest
  def self.from_h(hash)
    new(
      session_id: hash.fetch('sessionId'),
      command: hash.fetch('command'),
      args: hash['args'],
      env: hash['env']&.map { |item| ACP::Types::EnvVariable.from_h(item) },
      cwd: hash['cwd'],
      output_byte_limit: hash['outputByteLimit'],
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'sessionId' => session_id,
      'command' => command,
      'args' => args,
      'env' => env&.map(&:to_h),
      'cwd' => cwd,
      'outputByteLimit' => output_byte_limit,
      '_meta' => meta
    }.compact
  end
end
