# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::CreateElicitationResponse
  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @dynamic action
  attr_reader :action #: ACP::Types::CreateElicitationResponse::Action::t

  # @rbs meta: Hash[String, untyped]?
  # @rbs action: ACP::Types::CreateElicitationResponse::Action::t
  # @rbs return: void
  def initialize(action:, meta: nil)
    @meta = meta
    @action = action
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::CreateElicitationResponse
  def self.from_h(hash)
    new(meta: hash['_meta'], action: ACP::Types::CreateElicitationResponse::Action.from_h(hash))
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { '_meta' => meta }.compact.merge(action.to_h)
  end
end
