# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::CreateElicitationRequest
  # @dynamic message
  attr_reader :message #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @dynamic mode
  attr_reader :mode #: ACP::Types::CreateElicitationRequest::Mode::t

  # @rbs message: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs mode: ACP::Types::CreateElicitationRequest::Mode::t
  # @rbs return: void
  def initialize(message:, mode:, meta: nil)
    @message = message
    @meta = meta
    @mode = mode
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::CreateElicitationRequest
  def self.from_h(hash)
    new(
      message: hash.fetch('message'),
      meta: hash['_meta'],
      mode: ACP::Types::CreateElicitationRequest::Mode.from_h(hash)
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'message' => message, '_meta' => meta }.compact.merge(mode.to_h)
  end
end
