# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

# @rbs!
#   class ACP::Types::CurrentModeUpdate = ACP::Types::SessionUpdate::CurrentModeUpdate

ACP::Types::CurrentModeUpdate = ACP::Types::SessionUpdate::CurrentModeUpdate
