# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::Diff
  # @dynamic path
  attr_reader :path #: String

  # @dynamic old_text
  attr_reader :old_text #: String?

  # @dynamic new_text
  attr_reader :new_text #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs path: String
  # @rbs old_text: String?
  # @rbs new_text: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(path:, new_text:, old_text: nil, meta: nil)
    @path = path
    @old_text = old_text
    @new_text = new_text
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Diff
  def self.from_h(hash)
    new(
      path: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'path'), 'path'),
      old_text: ACP::Types::Check.string(hash['oldText'], 'oldText', allow_nil: true),
      new_text: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'newText'), 'newText'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'path' => path, 'newText' => new_text, 'oldText' => old_text, '_meta' => meta }.compact
  end
end
