# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ElicitationUrlMode
  # @dynamic elicitation_id
  attr_reader :elicitation_id #: String

  # @dynamic url
  attr_reader :url #: String

  # @dynamic scope
  attr_reader :scope #: ACP::Types::ElicitationUrlMode::Scope::t

  # @rbs elicitation_id: String
  # @rbs url: String
  # @rbs scope: ACP::Types::ElicitationUrlMode::Scope::t
  # @rbs return: void
  def initialize(elicitation_id:, url:, scope:)
    @elicitation_id = elicitation_id
    @url = url
    @scope = scope
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ElicitationUrlMode
  def self.from_h(hash)
    new(
      elicitation_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'elicitationId'), 'elicitationId'),
      url: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'url'), 'url'),
      scope: ACP::Types::ElicitationUrlMode::Scope.from_h(hash)
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'elicitationId' => elicitation_id, 'url' => url }.merge(scope.to_h)
  end
end
