# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ElicitationSessionScope
  # @dynamic session_id
  attr_reader :session_id #: String

  # @dynamic tool_call_id
  attr_reader :tool_call_id #: String?

  # @rbs session_id: String
  # @rbs tool_call_id: String?
  # @rbs return: void
  def initialize(session_id:, tool_call_id: nil)
    @session_id = session_id
    @tool_call_id = tool_call_id
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ElicitationSessionScope
  def self.from_h(hash)
    new(session_id: hash.fetch('sessionId'), tool_call_id: hash['toolCallId'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'sessionId' => session_id, 'toolCallId' => tool_call_id }.compact
  end
end
