# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ElicitationSchema
  # @dynamic type
  attr_reader :type #: String?

  # @dynamic title
  attr_reader :title #: String?

  # @dynamic properties
  attr_reader :properties #: Hash[String, ACP::Types::ElicitationPropertySchema::t]?

  # @dynamic required
  attr_reader :required #: Array[String]?

  # @dynamic description
  attr_reader :description #: String?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs type: String?
  # @rbs title: String?
  # @rbs properties: Hash[String, ACP::Types::ElicitationPropertySchema::t]?
  # @rbs required: Array[String]?
  # @rbs description: String?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(type: nil, title: nil, properties: nil, required: nil, description: nil, meta: nil)
    @type = type
    @title = title
    @properties = properties
    @required = required
    @description = description
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ElicitationSchema
  def self.from_h(hash)
    properties = ACP::Types::Check.hash(hash['properties'], 'properties', allow_nil: true) do |value, path|
      ACP::Types::Check.object(value, path, ACP::Types::ElicitationPropertySchema)
    end
    required = ACP::Types::Check.array(hash['required'], 'required', allow_nil: true) do |item, path|
      ACP::Types::Check.string(item, path)
    end
    new(
      type: ACP::Types::Check.enum(hash['type'], 'type', ['object'], allow_nil: true),
      title: ACP::Types::Check.string(hash['title'], 'title', allow_nil: true),
      properties:,
      required:,
      description: ACP::Types::Check.string(hash['description'], 'description', allow_nil: true),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'type' => type,
      'title' => title,
      'properties' => properties&.transform_values(&:to_h),
      'required' => required,
      'description' => description,
      '_meta' => meta
    }.compact
  end
end
