# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

# @rbs!
#   class ACP::Types::ElicitationFormMode = ACP::Types::CreateElicitationRequest::Mode::Form

ACP::Types::ElicitationFormMode = ACP::Types::CreateElicitationRequest::Mode::Form
