# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

# @rbs!
#   class ACP::Types::ElicitationAcceptAction = ACP::Types::CreateElicitationResponse::Action::Accept

ACP::Types::ElicitationAcceptAction = ACP::Types::CreateElicitationResponse::Action::Accept
