# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

# @rbs!
#   class ACP::Types::ElicitationUrlMode = ACP::Types::CreateElicitationRequest::Mode::Url

ACP::Types::ElicitationUrlMode = ACP::Types::CreateElicitationRequest::Mode::Url
