# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ElicitationFormMode
  # @dynamic requested_schema
  attr_reader :requested_schema #: ACP::Types::ElicitationSchema

  # @dynamic scope
  attr_reader :scope #: ACP::Types::ElicitationFormMode::Scope::t

  # @rbs requested_schema: ACP::Types::ElicitationSchema
  # @rbs scope: ACP::Types::ElicitationFormMode::Scope::t
  # @rbs return: void
  def initialize(requested_schema:, scope:)
    @requested_schema = requested_schema
    @scope = scope
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ElicitationFormMode
  def self.from_h(hash)
    new(
      requested_schema: ACP::Types::Check.object(
        ACP::Types::Check.key(hash, 'requestedSchema'),
        'requestedSchema',
        ACP::Types::ElicitationSchema
      ),
      scope: ACP::Types::ElicitationFormMode::Scope.from_h(hash)
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'requestedSchema' => requested_schema.to_h }.merge(scope.to_h)
  end
end
