# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ElicitationCapabilities
  # @dynamic form
  attr_reader :form #: ACP::Types::ElicitationFormCapabilities?

  # @dynamic url
  attr_reader :url #: ACP::Types::ElicitationUrlCapabilities?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs form: ACP::Types::ElicitationFormCapabilities?
  # @rbs url: ACP::Types::ElicitationUrlCapabilities?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(form: nil, url: nil, meta: nil)
    @form = form
    @url = url
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ElicitationCapabilities
  def self.from_h(hash)
    new(
      form: hash['form']&.then { |value| ACP::Types::ElicitationFormCapabilities.from_h(value) },
      url: hash['url']&.then { |value| ACP::Types::ElicitationUrlCapabilities.from_h(value) },
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'form' => form&.to_h, 'url' => url&.to_h, '_meta' => meta }.compact
  end
end
