# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

module ACP::Types::ElicitationPropertySchema
  # @rbs!
  #   type t = ACP::Types::ElicitationPropertySchema::StringPropertySchema
  #          | ACP::Types::ElicitationPropertySchema::NumberPropertySchema
  #          | ACP::Types::ElicitationPropertySchema::IntegerPropertySchema
  #          | ACP::Types::ElicitationPropertySchema::BooleanPropertySchema
  #          | ACP::Types::ElicitationPropertySchema::MultiSelectPropertySchema
  #          | Hash[String, untyped]

  # @rbs hash: Hash[String, untyped]
  # @rbs return: t
  def self.from_h(hash)
    case hash['type']
    when 'string' then ACP::Types::ElicitationPropertySchema::StringPropertySchema.from_h(hash)
    when 'number' then ACP::Types::ElicitationPropertySchema::NumberPropertySchema.from_h(hash)
    when 'integer' then ACP::Types::ElicitationPropertySchema::IntegerPropertySchema.from_h(hash)
    when 'boolean' then ACP::Types::ElicitationPropertySchema::BooleanPropertySchema.from_h(hash)
    when 'array' then ACP::Types::ElicitationPropertySchema::MultiSelectPropertySchema.from_h(hash)
    else hash
    end
  end
end
