# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ElicitationRequestScope
  # @dynamic request_id
  attr_reader :request_id #: nil | Integer | String

  # @rbs request_id: nil | Integer | String
  # @rbs return: void
  def initialize(request_id:)
    @request_id = request_id
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ElicitationRequestScope
  def self.from_h(hash)
    new(request_id: hash.fetch('requestId'))
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'requestId' => request_id }
  end
end
