# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

module ACP::Types::EmbeddedResourceResource
  # @rbs!
  #   type t = ACP::Types::TextResourceContents
  #          | ACP::Types::BlobResourceContents
  #          | Hash[String, untyped]

  # @rbs hash: Hash[String, untyped]
  # @rbs return: t
  def self.from_h(hash)
    if hash.key?('text')
      ACP::Types::TextResourceContents.from_h(hash)
    elsif hash.key?('blob')
      ACP::Types::BlobResourceContents.from_h(hash)
    else
      hash
    end
  end
end
