# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

# @rbs!
#   class ACP::Types::EmbeddedResource = ACP::Types::ContentBlock::Resource

ACP::Types::EmbeddedResource = ACP::Types::ContentBlock::Resource
