# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::EnumOption
  # @dynamic const
  attr_reader :const #: String

  # @dynamic title
  attr_reader :title #: String

  # @dynamic description
  attr_reader :description #: String?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs const: String
  # @rbs title: String
  # @rbs description: String?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(const:, title:, description: nil, meta: nil)
    @const = const
    @title = title
    @description = description
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::EnumOption
  def self.from_h(hash)
    new(const: hash.fetch('const'), title: hash.fetch('title'), description: hash['description'], meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'const' => const, 'title' => title, 'description' => description, '_meta' => meta }.compact
  end
end
