# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::FileSystemCapabilities
  # @dynamic read_text_file
  attr_reader :read_text_file #: bool?

  # @dynamic write_text_file
  attr_reader :write_text_file #: bool?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs read_text_file: bool?
  # @rbs write_text_file: bool?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(read_text_file: nil, write_text_file: nil, meta: nil)
    @read_text_file = read_text_file
    @write_text_file = write_text_file
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::FileSystemCapabilities
  def self.from_h(hash)
    new(read_text_file: hash['readTextFile'], write_text_file: hash['writeTextFile'], meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'readTextFile' => read_text_file, 'writeTextFile' => write_text_file, '_meta' => meta }.compact
  end
end
