# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::HttpHeader
  # @dynamic name
  attr_reader :name #: String

  # @dynamic value
  attr_reader :value #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs name: String
  # @rbs value: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(name:, value:, meta: nil)
    @name = name
    @value = value
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::HttpHeader
  def self.from_h(hash)
    new(name: hash.fetch('name'), value: hash.fetch('value'), meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'name' => name, 'value' => value, '_meta' => meta }.compact
  end
end
