# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

# @rbs!
#   class ACP::Types::ImageContent = ACP::Types::ContentBlock::Image

ACP::Types::ImageContent = ACP::Types::ContentBlock::Image
