# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::Implementation
  # @dynamic name
  attr_reader :name #: String

  # @dynamic title
  attr_reader :title #: String?

  # @dynamic version
  attr_reader :version #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs name: String
  # @rbs title: String?
  # @rbs version: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(name:, version:, title: nil, meta: nil)
    @name = name
    @title = title
    @version = version
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Implementation
  def self.from_h(hash)
    new(
      name: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'name'), 'name'),
      title: ACP::Types::Check.string(hash['title'], 'title', allow_nil: true),
      version: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'version'), 'version'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'name' => name, 'version' => version, 'title' => title, '_meta' => meta }.compact
  end
end
