# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::InitializeResponse
  # @dynamic protocol_version
  attr_reader :protocol_version #: Integer

  # @dynamic agent_capabilities
  attr_reader :agent_capabilities #: ACP::Types::AgentCapabilities?

  # @dynamic auth_methods
  attr_reader :auth_methods #: Array[ACP::Types::AuthMethod::t]?

  # @dynamic agent_info
  attr_reader :agent_info #: ACP::Types::Implementation?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs protocol_version: Integer
  # @rbs agent_capabilities: ACP::Types::AgentCapabilities?
  # @rbs auth_methods: Array[ACP::Types::AuthMethod::t]?
  # @rbs agent_info: ACP::Types::Implementation?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(protocol_version:, agent_capabilities: nil, auth_methods: nil, agent_info: nil, meta: nil)
    @protocol_version = protocol_version
    @agent_capabilities = agent_capabilities
    @auth_methods = auth_methods
    @agent_info = agent_info
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::InitializeResponse
  def self.from_h(hash)
    auth_methods = ACP::Types::Check.array(hash['authMethods'], 'authMethods', allow_nil: true) do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::AuthMethod)
    end
    new(
      protocol_version: ACP::Types::Check.integer(
        ACP::Types::Check.key(hash, 'protocolVersion'),
        'protocolVersion',
        min: 0,
        max: 65_535
      ),
      agent_capabilities: ACP::Types::Check.object(
        hash['agentCapabilities'],
        'agentCapabilities',
        ACP::Types::AgentCapabilities,
        allow_nil: true
      ),
      auth_methods:,
      agent_info: ACP::Types::Check.object(hash['agentInfo'], 'agentInfo', ACP::Types::Implementation, allow_nil: true),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'protocolVersion' => protocol_version,
      'agentCapabilities' => agent_capabilities&.to_h,
      'authMethods' => auth_methods&.map(&:to_h),
      'agentInfo' => agent_info&.to_h,
      '_meta' => meta
    }.compact
  end
end
