# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::InitializeRequest
  # @dynamic protocol_version
  attr_reader :protocol_version #: Integer

  # @dynamic client_capabilities
  attr_reader :client_capabilities #: ACP::Types::ClientCapabilities?

  # @dynamic client_info
  attr_reader :client_info #: ACP::Types::Implementation?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs protocol_version: Integer
  # @rbs client_capabilities: ACP::Types::ClientCapabilities?
  # @rbs client_info: ACP::Types::Implementation?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(protocol_version:, client_capabilities: nil, client_info: nil, meta: nil)
    @protocol_version = protocol_version
    @client_capabilities = client_capabilities
    @client_info = client_info
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::InitializeRequest
  def self.from_h(hash)
    new(
      protocol_version: ACP::Types::Check.integer(
        ACP::Types::Check.key(hash, 'protocolVersion'),
        'protocolVersion',
        min: 0,
        max: 65_535
      ),
      client_capabilities: ACP::Types::Check.object(
        hash['clientCapabilities'],
        'clientCapabilities',
        ACP::Types::ClientCapabilities,
        allow_nil: true
      ),
      client_info: ACP::Types::Check.object(
        hash['clientInfo'],
        'clientInfo',
        ACP::Types::Implementation,
        allow_nil: true
      ),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'protocolVersion' => protocol_version,
      'clientCapabilities' => client_capabilities&.to_h,
      'clientInfo' => client_info&.to_h,
      '_meta' => meta
    }.compact
  end
end
