# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

# @rbs!
#   class ACP::Types::IntegerPropertySchema = ACP::Types::ElicitationPropertySchema::IntegerPropertySchema

ACP::Types::IntegerPropertySchema = ACP::Types::ElicitationPropertySchema::IntegerPropertySchema
