# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ListSessionsResponse
  # @dynamic sessions
  attr_reader :sessions #: Array[ACP::Types::SessionInfo]

  # @dynamic next_cursor
  attr_reader :next_cursor #: String?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs sessions: Array[ACP::Types::SessionInfo]
  # @rbs next_cursor: String?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(sessions:, next_cursor: nil, meta: nil)
    @sessions = sessions
    @next_cursor = next_cursor
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ListSessionsResponse
  def self.from_h(hash)
    new(
      sessions: hash.fetch('sessions').map { |item| ACP::Types::SessionInfo.from_h(item) },
      next_cursor: hash['nextCursor'],
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'sessions' => sessions.map(&:to_h), 'nextCursor' => next_cursor, '_meta' => meta }.compact
  end
end
