# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ListSessionsRequest
  # @dynamic cwd
  attr_reader :cwd #: String?

  # @dynamic cursor
  attr_reader :cursor #: String?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs cwd: String?
  # @rbs cursor: String?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(cwd: nil, cursor: nil, meta: nil)
    @cwd = cwd
    @cursor = cursor
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ListSessionsRequest
  def self.from_h(hash)
    new(
      cwd: ACP::Types::Check.string(hash['cwd'], 'cwd', allow_nil: true),
      cursor: ACP::Types::Check.string(hash['cursor'], 'cursor', allow_nil: true),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'cwd' => cwd, 'cursor' => cursor, '_meta' => meta }.compact
  end
end
