# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::LoadSessionRequest
  # @dynamic mcp_servers
  attr_reader :mcp_servers #: Array[ACP::Types::McpServer::t]

  # @dynamic cwd
  attr_reader :cwd #: String

  # @dynamic additional_directories
  attr_reader :additional_directories #: Array[String]?

  # @dynamic session_id
  attr_reader :session_id #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs mcp_servers: Array[ACP::Types::McpServer::t]
  # @rbs cwd: String
  # @rbs additional_directories: Array[String]?
  # @rbs session_id: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(mcp_servers:, cwd:, session_id:, additional_directories: nil, meta: nil)
    @mcp_servers = mcp_servers
    @cwd = cwd
    @additional_directories = additional_directories
    @session_id = session_id
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::LoadSessionRequest
  def self.from_h(hash)
    new(
      mcp_servers: hash.fetch('mcpServers').map { |item| ACP::Types::McpServer.from_h(item) },
      cwd: hash.fetch('cwd'),
      additional_directories: hash['additionalDirectories'],
      session_id: hash.fetch('sessionId'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'mcpServers' => mcp_servers.map(&:to_h),
      'cwd' => cwd,
      'sessionId' => session_id,
      'additionalDirectories' => additional_directories,
      '_meta' => meta
    }.compact
  end
end
