# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::LoadSessionResponse
  # @dynamic modes
  attr_reader :modes #: ACP::Types::SessionModeState?

  # @dynamic config_options
  attr_reader :config_options #: Array[ACP::Types::SessionConfigOption]?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs modes: ACP::Types::SessionModeState?
  # @rbs config_options: Array[ACP::Types::SessionConfigOption]?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(modes: nil, config_options: nil, meta: nil)
    @modes = modes
    @config_options = config_options
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::LoadSessionResponse
  def self.from_h(hash)
    config_options = ACP::Types::Check.array(hash['configOptions'], 'configOptions', allow_nil: true) do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::SessionConfigOption)
    end
    new(
      modes: ACP::Types::Check.object(hash['modes'], 'modes', ACP::Types::SessionModeState, allow_nil: true),
      config_options:,
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'modes' => modes&.to_h, 'configOptions' => config_options&.map(&:to_h), '_meta' => meta }.compact
  end
end
