# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

# @rbs!
#   class ACP::Types::McpServerSse = ACP::Types::McpServer::Sse

ACP::Types::McpServerSse = ACP::Types::McpServer::Sse
