# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::McpServerStdio
  # @dynamic name
  attr_reader :name #: String

  # @dynamic command
  attr_reader :command #: String

  # @dynamic args
  attr_reader :args #: Array[String]

  # @dynamic env
  attr_reader :env #: Array[ACP::Types::EnvVariable]

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs name: String
  # @rbs command: String
  # @rbs args: Array[String]
  # @rbs env: Array[ACP::Types::EnvVariable]
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(name:, command:, args:, env:, meta: nil)
    @name = name
    @command = command
    @args = args
    @env = env
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::McpServerStdio
  def self.from_h(hash)
    args = ACP::Types::Check.array(ACP::Types::Check.key(hash, 'args'), 'args') do |item, path|
      ACP::Types::Check.string(item, path)
    end
    env = ACP::Types::Check.array(ACP::Types::Check.key(hash, 'env'), 'env') do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::EnvVariable)
    end
    new(
      name: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'name'), 'name'),
      command: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'command'), 'command'),
      args:,
      env:,
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'name' => name, 'command' => command, 'args' => args, 'env' => env.map(&:to_h), '_meta' => meta }.compact
  end
end
