# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

module ACP::Types::McpServer
  # @rbs!
  #   type t = ACP::Types::McpServer::Http
  #          | ACP::Types::McpServer::Sse
  #          | ACP::Types::McpServerStdio
  #          | Hash[String, untyped]

  # @rbs hash: Hash[String, untyped]
  # @rbs return: t
  def self.from_h(hash)
    case hash['type']
    when 'http' then ACP::Types::McpServer::Http.from_h(hash)
    when 'sse' then ACP::Types::McpServer::Sse.from_h(hash)
    when nil then ACP::Types::McpServerStdio.from_h(hash)
    else hash
    end
  end
end
