# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

module ACP::Types::MultiSelectItems
  # @rbs!
  #   type t = ACP::Types::MultiSelectItems::StringMultiSelectItems
  #          | ACP::Types::TitledMultiSelectItems
  #          | Hash[String, untyped]

  # @rbs hash: Hash[String, untyped]
  # @rbs return: t
  def self.from_h(hash)
    case hash['type']
    when 'string' then ACP::Types::MultiSelectItems::StringMultiSelectItems.from_h(hash)
    when nil then ACP::Types::TitledMultiSelectItems.from_h(hash)
    else hash
    end
  end
end
