# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

# @rbs!
#   class ACP::Types::MultiSelectPropertySchema = ACP::Types::ElicitationPropertySchema::MultiSelectPropertySchema

ACP::Types::MultiSelectPropertySchema = ACP::Types::ElicitationPropertySchema::MultiSelectPropertySchema
