# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::NewSessionRequest
  # @dynamic cwd
  attr_reader :cwd #: String

  # @dynamic additional_directories
  attr_reader :additional_directories #: Array[String]?

  # @dynamic mcp_servers
  attr_reader :mcp_servers #: Array[ACP::Types::McpServer::t]

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs cwd: String
  # @rbs additional_directories: Array[String]?
  # @rbs mcp_servers: Array[ACP::Types::McpServer::t]
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(cwd:, mcp_servers:, additional_directories: nil, meta: nil)
    @cwd = cwd
    @additional_directories = additional_directories
    @mcp_servers = mcp_servers
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::NewSessionRequest
  def self.from_h(hash)
    additional_directories = ACP::Types::Check.array(
      hash['additionalDirectories'],
      'additionalDirectories',
      allow_nil: true
    ) do |item, path|
      ACP::Types::Check.string(item, path)
    end
    mcp_servers = ACP::Types::Check.array(ACP::Types::Check.key(hash, 'mcpServers'), 'mcpServers') do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::McpServer)
    end
    new(
      cwd: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'cwd'), 'cwd'),
      additional_directories:,
      mcp_servers:,
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'cwd' => cwd,
      'mcpServers' => mcp_servers.map(&:to_h),
      'additionalDirectories' => additional_directories,
      '_meta' => meta
    }.compact
  end
end
