# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

module ACP::Types::PermissionOptionKind
  ALLOW_ONCE = 'allow_once'
  ALLOW_ALWAYS = 'allow_always'
  REJECT_ONCE = 'reject_once'
  REJECT_ALWAYS = 'reject_always'
end
