# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::PermissionOption
  # @dynamic option_id
  attr_reader :option_id #: String

  # @dynamic name
  attr_reader :name #: String

  # @dynamic kind
  attr_reader :kind #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs option_id: String
  # @rbs name: String
  # @rbs kind: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(option_id:, name:, kind:, meta: nil)
    @option_id = option_id
    @name = name
    @kind = kind
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::PermissionOption
  def self.from_h(hash)
    new(
      option_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'optionId'), 'optionId'),
      name: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'name'), 'name'),
      kind: ACP::Types::Check.enum(
        ACP::Types::Check.key(hash, 'kind'),
        'kind',
        %w[allow_once allow_always reject_once reject_always]
      ),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'optionId' => option_id, 'name' => name, 'kind' => kind, '_meta' => meta }.compact
  end
end
