# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::PlanEntry
  # @dynamic content
  attr_reader :content #: String

  # @dynamic priority
  attr_reader :priority #: String

  # @dynamic status
  attr_reader :status #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs content: String
  # @rbs priority: String
  # @rbs status: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(content:, priority:, status:, meta: nil)
    @content = content
    @priority = priority
    @status = status
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::PlanEntry
  def self.from_h(hash)
    new(
      content: hash.fetch('content'),
      priority: hash.fetch('priority'),
      status: hash.fetch('status'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'content' => content, 'priority' => priority, 'status' => status, '_meta' => meta }.compact
  end
end
