# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::PlanEntry
  # @dynamic content
  attr_reader :content #: String

  # @dynamic priority
  attr_reader :priority #: String

  # @dynamic status
  attr_reader :status #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs content: String
  # @rbs priority: String
  # @rbs status: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(content:, priority:, status:, meta: nil)
    @content = content
    @priority = priority
    @status = status
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::PlanEntry
  def self.from_h(hash)
    new(
      content: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'content'), 'content'),
      priority: ACP::Types::Check.enum(ACP::Types::Check.key(hash, 'priority'), 'priority', %w[high medium low]),
      status: ACP::Types::Check.enum(
        ACP::Types::Check.key(hash, 'status'),
        'status',
        %w[pending in_progress completed]
      ),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'content' => content, 'priority' => priority, 'status' => status, '_meta' => meta }.compact
  end
end
