# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

module ACP::Types::PlanEntryStatus
  PENDING = 'pending'
  IN_PROGRESS = 'in_progress'
  COMPLETED = 'completed'
end
