# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

# @rbs!
#   class ACP::Types::Plan = ACP::Types::SessionUpdate::Plan

ACP::Types::Plan = ACP::Types::SessionUpdate::Plan
