# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::PromptCapabilities
  # @dynamic image
  attr_reader :image #: bool?

  # @dynamic audio
  attr_reader :audio #: bool?

  # @dynamic embedded_context
  attr_reader :embedded_context #: bool?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs image: bool?
  # @rbs audio: bool?
  # @rbs embedded_context: bool?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(image: nil, audio: nil, embedded_context: nil, meta: nil)
    @image = image
    @audio = audio
    @embedded_context = embedded_context
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::PromptCapabilities
  def self.from_h(hash)
    new(
      image: ACP::Types::Check.boolean(hash['image'], 'image', allow_nil: true),
      audio: ACP::Types::Check.boolean(hash['audio'], 'audio', allow_nil: true),
      embedded_context: ACP::Types::Check.boolean(hash['embeddedContext'], 'embeddedContext', allow_nil: true),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'image' => image, 'audio' => audio, 'embeddedContext' => embedded_context, '_meta' => meta }.compact
  end
end
