# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::PromptRequest
  # @dynamic session_id
  attr_reader :session_id #: String

  # @dynamic prompt
  attr_reader :prompt #: Array[ACP::Types::ContentBlock::t]

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs session_id: String
  # @rbs prompt: Array[ACP::Types::ContentBlock::t]
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(session_id:, prompt:, meta: nil)
    @session_id = session_id
    @prompt = prompt
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::PromptRequest
  def self.from_h(hash)
    new(
      session_id: hash.fetch('sessionId'),
      prompt: hash.fetch('prompt').map { |item| ACP::Types::ContentBlock.from_h(item) },
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'sessionId' => session_id, 'prompt' => prompt.map(&:to_h), '_meta' => meta }.compact
  end
end
