# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::PromptResponse
  # @dynamic stop_reason
  attr_reader :stop_reason #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs stop_reason: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(stop_reason:, meta: nil)
    @stop_reason = stop_reason
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::PromptResponse
  def self.from_h(hash)
    new(
      stop_reason: ACP::Types::Check.enum(
        ACP::Types::Check.key(hash, 'stopReason'),
        'stopReason',
        %w[end_turn max_tokens max_turn_requests refusal cancelled]
      ),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'stopReason' => stop_reason, '_meta' => meta }.compact
  end
end
