# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ReadTextFileResponse
  # @dynamic content
  attr_reader :content #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs content: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(content:, meta: nil)
    @content = content
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ReadTextFileResponse
  def self.from_h(hash)
    new(content: hash.fetch('content'), meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'content' => content, '_meta' => meta }.compact
  end
end
