# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ReadTextFileRequest
  # @dynamic session_id
  attr_reader :session_id #: String

  # @dynamic path
  attr_reader :path #: String

  # @dynamic line
  attr_reader :line #: Integer?

  # @dynamic limit
  attr_reader :limit #: Integer?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs session_id: String
  # @rbs path: String
  # @rbs line: Integer?
  # @rbs limit: Integer?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(session_id:, path:, line: nil, limit: nil, meta: nil)
    @session_id = session_id
    @path = path
    @line = line
    @limit = limit
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ReadTextFileRequest
  def self.from_h(hash)
    new(
      session_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'sessionId'), 'sessionId'),
      path: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'path'), 'path'),
      line: ACP::Types::Check.integer(hash['line'], 'line', min: 0, allow_nil: true),
      limit: ACP::Types::Check.integer(hash['limit'], 'limit', min: 0, allow_nil: true),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'sessionId' => session_id, 'path' => path, 'line' => line, 'limit' => limit, '_meta' => meta }.compact
  end
end
