# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::RequestPermissionRequest
  # @dynamic session_id
  attr_reader :session_id #: String

  # @dynamic tool_call
  attr_reader :tool_call #: ACP::Types::ToolCallUpdate

  # @dynamic options
  attr_reader :options #: Array[ACP::Types::PermissionOption]

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs session_id: String
  # @rbs tool_call: ACP::Types::ToolCallUpdate
  # @rbs options: Array[ACP::Types::PermissionOption]
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(session_id:, tool_call:, options:, meta: nil)
    @session_id = session_id
    @tool_call = tool_call
    @options = options
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::RequestPermissionRequest
  def self.from_h(hash)
    options = ACP::Types::Check.array(ACP::Types::Check.key(hash, 'options'), 'options') do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::PermissionOption)
    end
    new(
      session_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'sessionId'), 'sessionId'),
      tool_call: ACP::Types::Check.object(
        ACP::Types::Check.key(hash, 'toolCall'),
        'toolCall',
        ACP::Types::ToolCallUpdate
      ),
      options:,
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'sessionId' => session_id,
      'toolCall' => tool_call.to_h,
      'options' => options.map(&:to_h),
      '_meta' => meta
    }.compact
  end
end
