# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

module ACP::Types::RequestPermissionOutcome
  # @rbs!
  #   type t = ACP::Types::RequestPermissionOutcome::Cancelled
  #          | ACP::Types::RequestPermissionOutcome::Selected
  #          | Hash[String, untyped]

  # @rbs hash: Hash[String, untyped]
  # @rbs return: t
  def self.from_h(hash)
    case hash['outcome']
    when 'cancelled' then ACP::Types::RequestPermissionOutcome::Cancelled.from_h(hash)
    when 'selected' then ACP::Types::RequestPermissionOutcome::Selected.from_h(hash)
    else hash
    end
  end
end
