# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::RequestPermissionResponse
  # @dynamic outcome
  attr_reader :outcome #: ACP::Types::RequestPermissionOutcome::t

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs outcome: ACP::Types::RequestPermissionOutcome::t
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(outcome:, meta: nil)
    @outcome = outcome
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::RequestPermissionResponse
  def self.from_h(hash)
    new(
      outcome: ACP::Types::Check.object(
        ACP::Types::Check.key(hash, 'outcome'),
        'outcome',
        ACP::Types::RequestPermissionOutcome
      ),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'outcome' => outcome.to_h, '_meta' => meta }.compact
  end
end
