# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

# @rbs!
#   class ACP::Types::ResourceLink = ACP::Types::ContentBlock::ResourceLink

ACP::Types::ResourceLink = ACP::Types::ContentBlock::ResourceLink
