# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ResumeSessionRequest
  # @dynamic session_id
  attr_reader :session_id #: String

  # @dynamic cwd
  attr_reader :cwd #: String

  # @dynamic additional_directories
  attr_reader :additional_directories #: Array[String]?

  # @dynamic mcp_servers
  attr_reader :mcp_servers #: Array[ACP::Types::McpServer::t]?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs session_id: String
  # @rbs cwd: String
  # @rbs additional_directories: Array[String]?
  # @rbs mcp_servers: Array[ACP::Types::McpServer::t]?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(session_id:, cwd:, additional_directories: nil, mcp_servers: nil, meta: nil)
    @session_id = session_id
    @cwd = cwd
    @additional_directories = additional_directories
    @mcp_servers = mcp_servers
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ResumeSessionRequest
  def self.from_h(hash)
    new(
      session_id: hash.fetch('sessionId'),
      cwd: hash.fetch('cwd'),
      additional_directories: hash['additionalDirectories'],
      mcp_servers: hash['mcpServers']&.map { |item| ACP::Types::McpServer.from_h(item) },
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'sessionId' => session_id,
      'cwd' => cwd,
      'additionalDirectories' => additional_directories,
      'mcpServers' => mcp_servers&.map(&:to_h),
      '_meta' => meta
    }.compact
  end
end
