# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::SelectedPermissionOutcome
  # @dynamic option_id
  attr_reader :option_id #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs option_id: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(option_id:, meta: nil)
    @option_id = option_id
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::SelectedPermissionOutcome
  def self.from_h(hash)
    new(option_id: hash.fetch('optionId'), meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'optionId' => option_id, '_meta' => meta }.compact
  end
end
