# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

# @rbs!
#   class ACP::Types::SelectedPermissionOutcome = ACP::Types::RequestPermissionOutcome::Selected

ACP::Types::SelectedPermissionOutcome = ACP::Types::RequestPermissionOutcome::Selected
