# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

module ACP::Types::SessionConfigSelectOptions
  # @rbs!
  #   type t = Array[ACP::Types::SessionConfigSelectOption]
  #          | Array[ACP::Types::SessionConfigSelectGroup]
  #          | Array[Hash[String, untyped]]

  # @rbs items: Array[Hash[String, untyped]]
  # @rbs return: t
  def self.from_a(items)
    if items.all? { |item| item.key?('value') }
      items.each_with_index.map do |item, index|
        ACP::Types::Check.object(item, [index], ACP::Types::SessionConfigSelectOption)
      end #: Array[ACP::Types::SessionConfigSelectOption]
    elsif items.all? { |item| item.key?('group') }
      items.each_with_index.map do |item, index|
        ACP::Types::Check.object(item, [index], ACP::Types::SessionConfigSelectGroup)
      end #: Array[ACP::Types::SessionConfigSelectGroup]
    else
      items
    end
  end
end
