# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::SessionNotification
  # @dynamic session_id
  attr_reader :session_id #: String

  # @dynamic update
  attr_reader :update #: ACP::Types::SessionUpdate::t

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs session_id: String
  # @rbs update: ACP::Types::SessionUpdate::t
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(session_id:, update:, meta: nil)
    @session_id = session_id
    @update = update
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::SessionNotification
  def self.from_h(hash)
    new(
      session_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'sessionId'), 'sessionId'),
      update: ACP::Types::Check.object(ACP::Types::Check.key(hash, 'update'), 'update', ACP::Types::SessionUpdate),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'sessionId' => session_id, 'update' => update.to_h, '_meta' => meta }.compact
  end
end
