# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::SessionInfoUpdate
  # @dynamic title
  attr_reader :title #: String? | :unset

  # @dynamic updated_at
  attr_reader :updated_at #: String? | :unset

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs title: String? | :unset
  # @rbs updated_at: String? | :unset
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(title: :unset, updated_at: :unset, meta: nil)
    @title = title
    @updated_at = updated_at
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::SessionInfoUpdate
  def self.from_h(hash)
    new(
      title: ACP::Types::Check.string(hash.fetch('title', :unset), 'title', allow_nil: true, allow_unset: true),
      updated_at: ACP::Types::Check.string(
        hash.fetch('updatedAt', :unset),
        'updatedAt',
        allow_nil: true,
        allow_unset: true
      ),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      '_meta' => meta
    }.compact.merge({ 'title' => title, 'updatedAt' => updated_at }.reject { |_, value| value == :unset })
  end
end
