# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

# @rbs!
#   class ACP::Types::SessionConfigSelect = ACP::Types::SessionConfigOption::Kind::Select

ACP::Types::SessionConfigSelect = ACP::Types::SessionConfigOption::Kind::Select
