# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

# @rbs!
#   class ACP::Types::SessionListResponse = ACP::Types::ListSessionsResponse

ACP::Types::SessionListResponse = ACP::Types::ListSessionsResponse
