# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::SessionConfigOptionsCapabilities
  # @dynamic boolean
  attr_reader :boolean #: ACP::Types::BooleanConfigOptionCapabilities?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs boolean: ACP::Types::BooleanConfigOptionCapabilities?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(boolean: nil, meta: nil)
    @boolean = boolean
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::SessionConfigOptionsCapabilities
  def self.from_h(hash)
    new(
      boolean: hash['boolean']&.then { |value| ACP::Types::BooleanConfigOptionCapabilities.from_h(value) },
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'boolean' => boolean&.to_h, '_meta' => meta }.compact
  end
end
