# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

# @rbs!
#   class ACP::Types::SessionLoadRequest = ACP::Types::LoadSessionRequest

ACP::Types::SessionLoadRequest = ACP::Types::LoadSessionRequest
