# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::SessionConfigOption
  # @dynamic id
  attr_reader :id #: String

  # @dynamic name
  attr_reader :name #: String

  # @dynamic description
  attr_reader :description #: String?

  # @dynamic category
  attr_reader :category #: String?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @dynamic kind
  attr_reader :kind #: ACP::Types::SessionConfigOption::Kind::t

  # @rbs id: String
  # @rbs name: String
  # @rbs description: String?
  # @rbs category: String?
  # @rbs meta: Hash[String, untyped]?
  # @rbs kind: ACP::Types::SessionConfigOption::Kind::t
  # @rbs return: void
  def initialize(id:, name:, kind:, description: nil, category: nil, meta: nil)
    @id = id
    @name = name
    @description = description
    @category = category
    @meta = meta
    @kind = kind
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::SessionConfigOption
  def self.from_h(hash)
    new(
      id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'id'), 'id'),
      name: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'name'), 'name'),
      description: ACP::Types::Check.string(hash['description'], 'description', allow_nil: true),
      category: hash['category'],
      meta: hash['_meta'],
      kind: ACP::Types::SessionConfigOption::Kind.from_h(hash)
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'id' => id,
      'name' => name,
      'description' => description,
      'category' => category,
      '_meta' => meta
    }.compact.merge(kind.to_h)
  end
end
