# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

module ACP::Types::SessionConfigOptionCategory
  MODE = 'mode'
  MODEL = 'model'
  MODEL_CONFIG = 'model_config'
  THOUGHT_LEVEL = 'thought_level'
end
