# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

module ACP::Types::SessionUpdate
  # @rbs!
  #   type t = ACP::Types::SessionUpdate::UserMessageChunk
  #          | ACP::Types::SessionUpdate::AgentMessageChunk
  #          | ACP::Types::SessionUpdate::AgentThoughtChunk
  #          | ACP::Types::SessionUpdate::ToolCall
  #          | ACP::Types::SessionUpdate::ToolCallUpdate
  #          | ACP::Types::SessionUpdate::Plan
  #          | ACP::Types::SessionUpdate::AvailableCommandsUpdate
  #          | ACP::Types::SessionUpdate::CurrentModeUpdate
  #          | ACP::Types::SessionUpdate::ConfigOptionUpdate
  #          | ACP::Types::SessionUpdate::SessionInfoUpdate
  #          | ACP::Types::SessionUpdate::UsageUpdate
  #          | Hash[String, untyped]

  # @rbs hash: Hash[String, untyped]
  # @rbs return: t
  def self.from_h(hash)
    case hash['sessionUpdate']
    when 'user_message_chunk' then ACP::Types::SessionUpdate::UserMessageChunk.from_h(hash)
    when 'agent_message_chunk' then ACP::Types::SessionUpdate::AgentMessageChunk.from_h(hash)
    when 'agent_thought_chunk' then ACP::Types::SessionUpdate::AgentThoughtChunk.from_h(hash)
    when 'tool_call' then ACP::Types::SessionUpdate::ToolCall.from_h(hash)
    when 'tool_call_update' then ACP::Types::SessionUpdate::ToolCallUpdate.from_h(hash)
    when 'plan' then ACP::Types::SessionUpdate::Plan.from_h(hash)
    when 'available_commands_update' then ACP::Types::SessionUpdate::AvailableCommandsUpdate.from_h(hash)
    when 'current_mode_update' then ACP::Types::SessionUpdate::CurrentModeUpdate.from_h(hash)
    when 'config_option_update' then ACP::Types::SessionUpdate::ConfigOptionUpdate.from_h(hash)
    when 'session_info_update' then ACP::Types::SessionUpdate::SessionInfoUpdate.from_h(hash)
    when 'usage_update' then ACP::Types::SessionUpdate::UsageUpdate.from_h(hash)
    else hash
    end
  end
end
