# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::SessionCapabilities
  # @dynamic list
  attr_reader :list #: ACP::Types::SessionListCapabilities?

  # @dynamic delete
  attr_reader :delete #: ACP::Types::SessionDeleteCapabilities?

  # @dynamic additional_directories
  attr_reader :additional_directories #: ACP::Types::SessionAdditionalDirectoriesCapabilities?

  # @dynamic resume
  attr_reader :resume #: ACP::Types::SessionResumeCapabilities?

  # @dynamic close
  attr_reader :close #: ACP::Types::SessionCloseCapabilities?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs list: ACP::Types::SessionListCapabilities?
  # @rbs delete: ACP::Types::SessionDeleteCapabilities?
  # @rbs additional_directories: ACP::Types::SessionAdditionalDirectoriesCapabilities?
  # @rbs resume: ACP::Types::SessionResumeCapabilities?
  # @rbs close: ACP::Types::SessionCloseCapabilities?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(list: nil, delete: nil, additional_directories: nil, resume: nil, close: nil, meta: nil)
    @list = list
    @delete = delete
    @additional_directories = additional_directories
    @resume = resume
    @close = close
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::SessionCapabilities
  def self.from_h(hash)
    new(
      list: hash['list']&.then { |value| ACP::Types::SessionListCapabilities.from_h(value) },
      delete: hash['delete']&.then { |value| ACP::Types::SessionDeleteCapabilities.from_h(value) },
      additional_directories: hash['additionalDirectories']&.then do |value|
        ACP::Types::SessionAdditionalDirectoriesCapabilities.from_h(value)
      end,
      resume: hash['resume']&.then { |value| ACP::Types::SessionResumeCapabilities.from_h(value) },
      close: hash['close']&.then { |value| ACP::Types::SessionCloseCapabilities.from_h(value) },
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'list' => list&.to_h,
      'delete' => delete&.to_h,
      'additionalDirectories' => additional_directories&.to_h,
      'resume' => resume&.to_h,
      'close' => close&.to_h,
      '_meta' => meta
    }.compact
  end
end
