# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::SessionConfigBoolean
  # @dynamic current_value
  attr_reader :current_value #: bool

  # @rbs current_value: bool
  # @rbs return: void
  def initialize(current_value:)
    @current_value = current_value
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::SessionConfigBoolean
  def self.from_h(hash)
    new(current_value: hash.fetch('currentValue'))
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'currentValue' => current_value }
  end
end
