# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::SessionConfigSelect
  # @dynamic current_value
  attr_reader :current_value #: String

  # @dynamic options
  attr_reader :options #: ACP::Types::SessionConfigSelectOptions::t

  # @rbs current_value: String
  # @rbs options: ACP::Types::SessionConfigSelectOptions::t
  # @rbs return: void
  def initialize(current_value:, options:)
    @current_value = current_value
    @options = options
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::SessionConfigSelect
  def self.from_h(hash)
    new(
      current_value: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'currentValue'), 'currentValue'),
      options: ACP::Types::Check.objects(
        ACP::Types::Check.key(hash, 'options'),
        'options',
        ACP::Types::SessionConfigSelectOptions
      )
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'currentValue' => current_value, 'options' => options.map(&:to_h) }
  end
end
