# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::SessionInfo
  # @dynamic session_id
  attr_reader :session_id #: String

  # @dynamic cwd
  attr_reader :cwd #: String

  # @dynamic additional_directories
  attr_reader :additional_directories #: Array[String]?

  # @dynamic title
  attr_reader :title #: String?

  # @dynamic updated_at
  attr_reader :updated_at #: String?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs session_id: String
  # @rbs cwd: String
  # @rbs additional_directories: Array[String]?
  # @rbs title: String?
  # @rbs updated_at: String?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(session_id:, cwd:, additional_directories: nil, title: nil, updated_at: nil, meta: nil)
    @session_id = session_id
    @cwd = cwd
    @additional_directories = additional_directories
    @title = title
    @updated_at = updated_at
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::SessionInfo
  def self.from_h(hash)
    additional_directories = ACP::Types::Check.array(
      hash['additionalDirectories'],
      'additionalDirectories',
      allow_nil: true
    ) do |item, path|
      ACP::Types::Check.string(item, path)
    end
    new(
      session_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'sessionId'), 'sessionId'),
      cwd: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'cwd'), 'cwd'),
      additional_directories:,
      title: ACP::Types::Check.string(hash['title'], 'title', allow_nil: true),
      updated_at: ACP::Types::Check.string(hash['updatedAt'], 'updatedAt', allow_nil: true),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'sessionId' => session_id,
      'cwd' => cwd,
      'additionalDirectories' => additional_directories,
      'title' => title,
      'updatedAt' => updated_at,
      '_meta' => meta
    }.compact
  end
end
