# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

module ACP::Types::SessionConfigSelectOptions
  # @rbs!
  #   type t = Array[ACP::Types::SessionConfigSelectOption]
  #          | Array[ACP::Types::SessionConfigSelectGroup]
  #          | Array[Hash[String, untyped]]

  # @rbs items: Array[Hash[String, untyped]]
  # @rbs return: t
  def self.from_a(items)
    if items.all? { |item| item.key?('value') }
      items.map { |item| ACP::Types::SessionConfigSelectOption.from_h(item) } #: Array[ACP::Types::SessionConfigSelectOption]
    elsif items.all? { |item| item.key?('group') }
      items.map { |item| ACP::Types::SessionConfigSelectGroup.from_h(item) } #: Array[ACP::Types::SessionConfigSelectGroup]
    else
      items
    end
  end
end
