# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::SessionDeleteCapabilities
  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(meta: nil)
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::SessionDeleteCapabilities
  def self.from_h(hash)
    new(meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { '_meta' => meta }.compact
  end
end
