# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::SessionConfigSelectGroup
  # @dynamic group
  attr_reader :group #: String

  # @dynamic name
  attr_reader :name #: String

  # @dynamic options
  attr_reader :options #: Array[ACP::Types::SessionConfigSelectOption]

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs group: String
  # @rbs name: String
  # @rbs options: Array[ACP::Types::SessionConfigSelectOption]
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(group:, name:, options:, meta: nil)
    @group = group
    @name = name
    @options = options
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::SessionConfigSelectGroup
  def self.from_h(hash)
    options = ACP::Types::Check.array(ACP::Types::Check.key(hash, 'options'), 'options') do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::SessionConfigSelectOption)
    end
    new(
      group: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'group'), 'group'),
      name: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'name'), 'name'),
      options:,
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'group' => group, 'name' => name, 'options' => options.map(&:to_h), '_meta' => meta }.compact
  end
end
