# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::SessionConfigSelectOption
  # @dynamic value
  attr_reader :value #: String

  # @dynamic name
  attr_reader :name #: String

  # @dynamic description
  attr_reader :description #: String?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs value: String
  # @rbs name: String
  # @rbs description: String?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(value:, name:, description: nil, meta: nil)
    @value = value
    @name = name
    @description = description
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::SessionConfigSelectOption
  def self.from_h(hash)
    new(
      value: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'value'), 'value'),
      name: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'name'), 'name'),
      description: ACP::Types::Check.string(hash['description'], 'description', allow_nil: true),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'value' => value, 'name' => name, 'description' => description, '_meta' => meta }.compact
  end
end
