# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

# @rbs!
#   class ACP::Types::SessionInfoUpdate = ACP::Types::SessionUpdate::SessionInfoUpdate

ACP::Types::SessionInfoUpdate = ACP::Types::SessionUpdate::SessionInfoUpdate
