# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::SessionModeState
  # @dynamic current_mode_id
  attr_reader :current_mode_id #: String

  # @dynamic available_modes
  attr_reader :available_modes #: Array[ACP::Types::SessionMode]

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs current_mode_id: String
  # @rbs available_modes: Array[ACP::Types::SessionMode]
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(current_mode_id:, available_modes:, meta: nil)
    @current_mode_id = current_mode_id
    @available_modes = available_modes
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::SessionModeState
  def self.from_h(hash)
    new(
      current_mode_id: hash.fetch('currentModeId'),
      available_modes: hash.fetch('availableModes').map { |item| ACP::Types::SessionMode.from_h(item) },
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'currentModeId' => current_mode_id, 'availableModes' => available_modes.map(&:to_h), '_meta' => meta }.compact
  end
end
