# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::SetSessionModeRequest
  # @dynamic session_id
  attr_reader :session_id #: String

  # @dynamic mode_id
  attr_reader :mode_id #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs session_id: String
  # @rbs mode_id: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(session_id:, mode_id:, meta: nil)
    @session_id = session_id
    @mode_id = mode_id
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::SetSessionModeRequest
  def self.from_h(hash)
    new(
      session_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'sessionId'), 'sessionId'),
      mode_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'modeId'), 'modeId'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'sessionId' => session_id, 'modeId' => mode_id, '_meta' => meta }.compact
  end
end
