# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::SetSessionConfigOptionRequest
  # @dynamic session_id
  attr_reader :session_id #: String

  # @dynamic config_id
  attr_reader :config_id #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @dynamic value
  attr_reader :value #: ACP::Types::SetSessionConfigOptionRequest::Value::t

  # @rbs session_id: String
  # @rbs config_id: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs value: ACP::Types::SetSessionConfigOptionRequest::Value::t
  # @rbs return: void
  def initialize(session_id:, config_id:, value:, meta: nil)
    @session_id = session_id
    @config_id = config_id
    @meta = meta
    @value = value
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::SetSessionConfigOptionRequest
  def self.from_h(hash)
    new(
      session_id: hash.fetch('sessionId'),
      config_id: hash.fetch('configId'),
      meta: hash['_meta'],
      value: ACP::Types::SetSessionConfigOptionRequest::Value.from_h(hash)
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'sessionId' => session_id, 'configId' => config_id, '_meta' => meta }.compact.merge(value.to_h)
  end
end
