# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

module ACP::Types::StopReason
  END_TURN = 'end_turn'
  MAX_TOKENS = 'max_tokens'
  MAX_TURN_REQUESTS = 'max_turn_requests'
  REFUSAL = 'refusal'
  CANCELLED = 'cancelled'
end
