# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

# @rbs!
#   class ACP::Types::StringPropertySchema = ACP::Types::ElicitationPropertySchema::StringPropertySchema

ACP::Types::StringPropertySchema = ACP::Types::ElicitationPropertySchema::StringPropertySchema
