# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::StringMultiSelectItems
  # @dynamic enum
  attr_reader :enum #: Array[String]

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs enum: Array[String]
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(enum:, meta: nil)
    @enum = enum
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::StringMultiSelectItems
  def self.from_h(hash)
    new(enum: hash.fetch('enum'), meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'enum' => enum, '_meta' => meta }.compact
  end
end
