# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::StringPropertySchema
  # @dynamic title
  attr_reader :title #: String?

  # @dynamic description
  attr_reader :description #: String?

  # @dynamic min_length
  attr_reader :min_length #: Integer?

  # @dynamic max_length
  attr_reader :max_length #: Integer?

  # @dynamic pattern
  attr_reader :pattern #: String?

  # @dynamic format
  attr_reader :format #: String?

  # @dynamic default
  attr_reader :default #: String?

  # @dynamic enum
  attr_reader :enum #: Array[String]?

  # @dynamic one_of
  attr_reader :one_of #: Array[ACP::Types::EnumOption]?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs title: String?
  # @rbs description: String?
  # @rbs min_length: Integer?
  # @rbs max_length: Integer?
  # @rbs pattern: String?
  # @rbs format: String?
  # @rbs default: String?
  # @rbs enum: Array[String]?
  # @rbs one_of: Array[ACP::Types::EnumOption]?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(
    title: nil,
    description: nil,
    min_length: nil,
    max_length: nil,
    pattern: nil,
    format: nil,
    default: nil,
    enum: nil,
    one_of: nil,
    meta: nil
  )
    @title = title
    @description = description
    @min_length = min_length
    @max_length = max_length
    @pattern = pattern
    @format = format
    @default = default
    @enum = enum
    @one_of = one_of
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::StringPropertySchema
  def self.from_h(hash)
    enum = ACP::Types::Check.array(hash['enum'], 'enum', allow_nil: true) do |item, path|
      ACP::Types::Check.string(item, path)
    end
    one_of = ACP::Types::Check.array(hash['oneOf'], 'oneOf', allow_nil: true) do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::EnumOption)
    end
    new(
      title: ACP::Types::Check.string(hash['title'], 'title', allow_nil: true),
      description: ACP::Types::Check.string(hash['description'], 'description', allow_nil: true),
      min_length: ACP::Types::Check.integer(hash['minLength'], 'minLength', min: 0, allow_nil: true),
      max_length: ACP::Types::Check.integer(hash['maxLength'], 'maxLength', min: 0, allow_nil: true),
      pattern: ACP::Types::Check.string(hash['pattern'], 'pattern', allow_nil: true),
      format: ACP::Types::Check.enum(hash['format'], 'format', %w[email uri date date-time], allow_nil: true),
      default: ACP::Types::Check.string(hash['default'], 'default', allow_nil: true),
      enum:,
      one_of:,
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'title' => title,
      'description' => description,
      'minLength' => min_length,
      'maxLength' => max_length,
      'pattern' => pattern,
      'format' => format,
      'default' => default,
      'enum' => enum,
      'oneOf' => one_of&.map(&:to_h),
      '_meta' => meta
    }.compact
  end
end
