# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::StringPropertySchema
  # @dynamic title
  attr_reader :title #: String?

  # @dynamic description
  attr_reader :description #: String?

  # @dynamic min_length
  attr_reader :min_length #: Integer?

  # @dynamic max_length
  attr_reader :max_length #: Integer?

  # @dynamic pattern
  attr_reader :pattern #: String?

  # @dynamic format
  attr_reader :format #: String?

  # @dynamic default
  attr_reader :default #: String?

  # @dynamic enum
  attr_reader :enum #: Array[String]?

  # @dynamic one_of
  attr_reader :one_of #: Array[ACP::Types::EnumOption]?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs title: String?
  # @rbs description: String?
  # @rbs min_length: Integer?
  # @rbs max_length: Integer?
  # @rbs pattern: String?
  # @rbs format: String?
  # @rbs default: String?
  # @rbs enum: Array[String]?
  # @rbs one_of: Array[ACP::Types::EnumOption]?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(
    title: nil,
    description: nil,
    min_length: nil,
    max_length: nil,
    pattern: nil,
    format: nil,
    default: nil,
    enum: nil,
    one_of: nil,
    meta: nil
  )
    @title = title
    @description = description
    @min_length = min_length
    @max_length = max_length
    @pattern = pattern
    @format = format
    @default = default
    @enum = enum
    @one_of = one_of
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::StringPropertySchema
  def self.from_h(hash)
    new(
      title: hash['title'],
      description: hash['description'],
      min_length: hash['minLength'],
      max_length: hash['maxLength'],
      pattern: hash['pattern'],
      format: hash['format'],
      default: hash['default'],
      enum: hash['enum'],
      one_of: hash['oneOf']&.map { |item| ACP::Types::EnumOption.from_h(item) },
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'title' => title,
      'description' => description,
      'minLength' => min_length,
      'maxLength' => max_length,
      'pattern' => pattern,
      'format' => format,
      'default' => default,
      'enum' => enum,
      'oneOf' => one_of&.map(&:to_h),
      '_meta' => meta
    }.compact
  end
end
