# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

# @rbs!
#   class ACP::Types::StringMultiSelectItems = ACP::Types::MultiSelectItems::StringMultiSelectItems

ACP::Types::StringMultiSelectItems = ACP::Types::MultiSelectItems::StringMultiSelectItems
