# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

module ACP::Types::StringFormat
  EMAIL = 'email'
  URI = 'uri'
  DATE = 'date'
  DATE_TIME = 'date-time'
end
