# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::TerminalOutputResponse
  # @dynamic output
  attr_reader :output #: String

  # @dynamic truncated
  attr_reader :truncated #: bool

  # @dynamic exit_status
  attr_reader :exit_status #: ACP::Types::TerminalExitStatus?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs output: String
  # @rbs truncated: bool
  # @rbs exit_status: ACP::Types::TerminalExitStatus?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(output:, truncated:, exit_status: nil, meta: nil)
    @output = output
    @truncated = truncated
    @exit_status = exit_status
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::TerminalOutputResponse
  def self.from_h(hash)
    new(
      output: hash.fetch('output'),
      truncated: hash.fetch('truncated'),
      exit_status: hash['exitStatus']&.then { |value| ACP::Types::TerminalExitStatus.from_h(value) },
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'output' => output, 'truncated' => truncated, 'exitStatus' => exit_status&.to_h, '_meta' => meta }.compact
  end
end
