# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::TerminalExitStatus
  # @dynamic exit_code
  attr_reader :exit_code #: Integer?

  # @dynamic signal
  attr_reader :signal #: String?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs exit_code: Integer?
  # @rbs signal: String?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(exit_code: nil, signal: nil, meta: nil)
    @exit_code = exit_code
    @signal = signal
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::TerminalExitStatus
  def self.from_h(hash)
    new(
      exit_code: ACP::Types::Check.integer(hash['exitCode'], 'exitCode', min: 0, allow_nil: true),
      signal: ACP::Types::Check.string(hash['signal'], 'signal', allow_nil: true),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'exitCode' => exit_code, 'signal' => signal, '_meta' => meta }.compact
  end
end
