# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

# @rbs!
#   class ACP::Types::Terminal = ACP::Types::ToolCallContent::Terminal

ACP::Types::Terminal = ACP::Types::ToolCallContent::Terminal
