# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::TextResourceContents
  # @dynamic mime_type
  attr_reader :mime_type #: String?

  # @dynamic text
  attr_reader :text #: String

  # @dynamic uri
  attr_reader :uri #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs mime_type: String?
  # @rbs text: String
  # @rbs uri: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(text:, uri:, mime_type: nil, meta: nil)
    @mime_type = mime_type
    @text = text
    @uri = uri
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::TextResourceContents
  def self.from_h(hash)
    new(mime_type: hash['mimeType'], text: hash.fetch('text'), uri: hash.fetch('uri'), meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'text' => text, 'uri' => uri, 'mimeType' => mime_type, '_meta' => meta }.compact
  end
end
