# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::TextContent
  # @dynamic annotations
  attr_reader :annotations #: ACP::Types::Annotations?

  # @dynamic text
  attr_reader :text #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs annotations: ACP::Types::Annotations?
  # @rbs text: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(text:, annotations: nil, meta: nil)
    @annotations = annotations
    @text = text
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::TextContent
  def self.from_h(hash)
    new(
      annotations: ACP::Types::Check.object(
        hash['annotations'],
        'annotations',
        ACP::Types::Annotations,
        allow_nil: true
      ),
      text: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'text'), 'text'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'text' => text, 'annotations' => annotations&.to_h, '_meta' => meta }.compact
  end
end
