# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

# @rbs!
#   class ACP::Types::TextContent = ACP::Types::ContentBlock::Text

ACP::Types::TextContent = ACP::Types::ContentBlock::Text
