# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::TitledMultiSelectItems
  # @dynamic any_of
  attr_reader :any_of #: Array[ACP::Types::EnumOption]

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs any_of: Array[ACP::Types::EnumOption]
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(any_of:, meta: nil)
    @any_of = any_of
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::TitledMultiSelectItems
  def self.from_h(hash)
    any_of = ACP::Types::Check.array(ACP::Types::Check.key(hash, 'anyOf'), 'anyOf') do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::EnumOption)
    end
    new(any_of:, meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'anyOf' => any_of.map(&:to_h), '_meta' => meta }.compact
  end
end
