# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

module ACP::Types::ToolKind
  READ = 'read'
  EDIT = 'edit'
  DELETE = 'delete'
  MOVE = 'move'
  SEARCH = 'search'
  EXECUTE = 'execute'
  THINK = 'think'
  FETCH = 'fetch'
  SWITCH_MODE = 'switch_mode'
  OTHER = 'other'
end
