# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

module ACP::Types::ToolCallContent
  # @rbs!
  #   type t = ACP::Types::ToolCallContent::Content
  #          | ACP::Types::ToolCallContent::Diff
  #          | ACP::Types::ToolCallContent::Terminal
  #          | Hash[String, untyped]

  # @rbs hash: Hash[String, untyped]
  # @rbs return: t
  def self.from_h(hash)
    case hash['type']
    when 'content' then ACP::Types::ToolCallContent::Content.from_h(hash)
    when 'diff' then ACP::Types::ToolCallContent::Diff.from_h(hash)
    when 'terminal' then ACP::Types::ToolCallContent::Terminal.from_h(hash)
    else hash
    end
  end
end
