# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

# @rbs!
#   class ACP::Types::ToolCall = ACP::Types::SessionUpdate::ToolCall

ACP::Types::ToolCall = ACP::Types::SessionUpdate::ToolCall
