# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ToolCallLocation
  # @dynamic path
  attr_reader :path #: String

  # @dynamic line
  attr_reader :line #: Integer?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs path: String
  # @rbs line: Integer?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(path:, line: nil, meta: nil)
    @path = path
    @line = line
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ToolCallLocation
  def self.from_h(hash)
    new(path: hash.fetch('path'), line: hash['line'], meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'path' => path, 'line' => line, '_meta' => meta }.compact
  end
end
