# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::ToolCall
  # @dynamic tool_call_id
  attr_reader :tool_call_id #: String

  # @dynamic title
  attr_reader :title #: String

  # @dynamic name
  attr_reader :name #: String?

  # @dynamic kind
  attr_reader :kind #: String?

  # @dynamic status
  attr_reader :status #: String?

  # @dynamic content
  attr_reader :content #: Array[ACP::Types::ToolCallContent::t]?

  # @dynamic locations
  attr_reader :locations #: Array[ACP::Types::ToolCallLocation]?

  # @dynamic raw_input
  attr_reader :raw_input #: untyped

  # @dynamic raw_output
  attr_reader :raw_output #: untyped

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs tool_call_id: String
  # @rbs title: String
  # @rbs name: String?
  # @rbs kind: String?
  # @rbs status: String?
  # @rbs content: Array[ACP::Types::ToolCallContent::t]?
  # @rbs locations: Array[ACP::Types::ToolCallLocation]?
  # @rbs raw_input: untyped
  # @rbs raw_output: untyped
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(
    tool_call_id:,
    title:,
    name: nil,
    kind: nil,
    status: nil,
    content: nil,
    locations: nil,
    raw_input: nil,
    raw_output: nil,
    meta: nil
  )
    @tool_call_id = tool_call_id
    @title = title
    @name = name
    @kind = kind
    @status = status
    @content = content
    @locations = locations
    @raw_input = raw_input
    @raw_output = raw_output
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::ToolCall
  def self.from_h(hash)
    new(
      tool_call_id: hash.fetch('toolCallId'),
      title: hash.fetch('title'),
      name: hash['name'],
      kind: hash['kind'],
      status: hash['status'],
      content: hash['content']&.map { |item| ACP::Types::ToolCallContent.from_h(item) },
      locations: hash['locations']&.map { |item| ACP::Types::ToolCallLocation.from_h(item) },
      raw_input: hash['rawInput'],
      raw_output: hash['rawOutput'],
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'toolCallId' => tool_call_id,
      'title' => title,
      'name' => name,
      'kind' => kind,
      'status' => status,
      'content' => content&.map(&:to_h),
      'locations' => locations&.map(&:to_h),
      'rawInput' => raw_input,
      'rawOutput' => raw_output,
      '_meta' => meta
    }.compact
  end
end
