# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::UnstructuredCommandInput
  # @dynamic hint
  attr_reader :hint #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs hint: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(hint:, meta: nil)
    @hint = hint
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::UnstructuredCommandInput
  def self.from_h(hash)
    new(hint: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'hint'), 'hint'), meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'hint' => hint, '_meta' => meta }.compact
  end
end
