# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::WriteTextFileRequest
  # @dynamic session_id
  attr_reader :session_id #: String

  # @dynamic path
  attr_reader :path #: String

  # @dynamic content
  attr_reader :content #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs session_id: String
  # @rbs path: String
  # @rbs content: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(session_id:, path:, content:, meta: nil)
    @session_id = session_id
    @path = path
    @content = content
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::WriteTextFileRequest
  def self.from_h(hash)
    new(
      session_id: hash.fetch('sessionId'),
      path: hash.fetch('path'),
      content: hash.fetch('content'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'sessionId' => session_id, 'path' => path, 'content' => content, '_meta' => meta }.compact
  end
end
