# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

module ACP::Types::CreateElicitationRequest::Mode::Form::Scope
  # @rbs!
  #   type t = ACP::Types::ElicitationSessionScope
  #          | ACP::Types::ElicitationRequestScope
  #          | Hash[String, untyped]

  # @rbs hash: Hash[String, untyped]
  # @rbs return: t
  def self.from_h(hash)
    if hash.key?('sessionId')
      ACP::Types::ElicitationSessionScope.from_h(hash)
    elsif hash.key?('requestId')
      ACP::Types::ElicitationRequestScope.from_h(hash)
    else
      hash
    end
  end
end
