# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::CreateElicitationResponse::Action::Accept
  # @dynamic content
  attr_reader :content #: (Hash[String, String | Integer | Numeric | bool | Array[String]])?

  # @rbs content: (Hash[String, String | Integer | Numeric | bool | Array[String]])?
  # @rbs return: void
  def initialize(content: nil)
    @content = content
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::CreateElicitationResponse::Action::Accept
  def self.from_h(hash)
    new(content: hash['content'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'action' => 'accept', 'content' => content }.compact
  end
end
