# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::CreateElicitationResponse::Action::Cancel
  # @rbs return: void
  def initialize
    freeze
  end

  # @rbs _hash: Hash[String, untyped]
  # @rbs return: ACP::Types::CreateElicitationResponse::Action::Cancel
  def self.from_h(_hash)
    new
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'action' => 'cancel' }
  end
end
