# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

module ACP::Types::CreateElicitationRequest::Mode
  # @rbs!
  #   type t = ACP::Types::CreateElicitationRequest::Mode::Form
  #          | ACP::Types::CreateElicitationRequest::Mode::Url
  #          | Hash[String, untyped]

  # @rbs hash: Hash[String, untyped]
  # @rbs return: t
  def self.from_h(hash)
    case hash['mode']
    when 'form' then ACP::Types::CreateElicitationRequest::Mode::Form.from_h(hash)
    when 'url' then ACP::Types::CreateElicitationRequest::Mode::Url.from_h(hash)
    else hash
    end
  end
end
