# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::SessionUpdate::CompactionUpdate
  # @dynamic compaction_id
  attr_reader :compaction_id #: String

  # @dynamic status
  attr_reader :status #: String

  # @dynamic summary
  attr_reader :summary #: Array[ACP::Types::ContentBlock::t]?

  # @dynamic error
  attr_reader :error #: String?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs compaction_id: String
  # @rbs status: String
  # @rbs summary: Array[ACP::Types::ContentBlock::t]?
  # @rbs error: String?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(compaction_id:, status:, summary: nil, error: nil, meta: nil)
    @compaction_id = compaction_id
    @status = status
    @summary = summary
    @error = error
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::SessionUpdate::CompactionUpdate
  def self.from_h(hash)
    summary = ACP::Types::Check.array(hash['summary'], 'summary', allow_nil: true) do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::ContentBlock)
    end
    new(
      compaction_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'compactionId'), 'compactionId'),
      status: ACP::Types::Check.key(hash, 'status'),
      summary:,
      error: ACP::Types::Check.string(hash['error'], 'error', allow_nil: true),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'sessionUpdate' => 'compaction_update',
      'compactionId' => compaction_id,
      'status' => status,
      'summary' => summary&.map(&:to_h),
      'error' => error,
      '_meta' => meta
    }.compact
  end
end
