# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::SessionUpdate::ConfigOptionUpdate
  # @dynamic config_options
  attr_reader :config_options #: Array[ACP::Types::SessionConfigOption]

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs config_options: Array[ACP::Types::SessionConfigOption]
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(config_options:, meta: nil)
    @config_options = config_options
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::SessionUpdate::ConfigOptionUpdate
  def self.from_h(hash)
    config_options = ACP::Types::Check.array(
      ACP::Types::Check.key(hash, 'configOptions'),
      'configOptions'
    ) do |item, path|
      ACP::Types::Check.object(item, path, ACP::Types::SessionConfigOption)
    end
    new(config_options:, meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'sessionUpdate' => 'config_option_update',
      'configOptions' => config_options.map(&:to_h),
      '_meta' => meta
    }.compact
  end
end
