# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::SessionUpdate::CurrentModeUpdate
  # @dynamic current_mode_id
  attr_reader :current_mode_id #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs current_mode_id: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(current_mode_id:, meta: nil)
    @current_mode_id = current_mode_id
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::SessionUpdate::CurrentModeUpdate
  def self.from_h(hash)
    new(
      current_mode_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'currentModeId'), 'currentModeId'),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'sessionUpdate' => 'current_mode_update', 'currentModeId' => current_mode_id, '_meta' => meta }.compact
  end
end
