# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::SessionUpdate::Notice
  # @dynamic severity
  attr_reader :severity #: String

  # @dynamic title
  attr_reader :title #: String

  # @dynamic description
  attr_reader :description #: String?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs severity: String
  # @rbs title: String
  # @rbs description: String?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(severity:, title:, description: nil, meta: nil)
    @severity = severity
    @title = title
    @description = description
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::SessionUpdate::Notice
  def self.from_h(hash)
    new(
      severity: ACP::Types::Check.key(hash, 'severity'),
      title: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'title'), 'title'),
      description: ACP::Types::Check.string(hash['description'], 'description', allow_nil: true),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'sessionUpdate' => 'notice',
      'severity' => severity,
      'title' => title,
      'description' => description,
      '_meta' => meta
    }.compact
  end
end
