# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::SessionUpdate::PlanRemoved
  # @dynamic plan_id
  attr_reader :plan_id #: String

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs plan_id: String
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(plan_id:, meta: nil)
    @plan_id = plan_id
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::SessionUpdate::PlanRemoved
  def self.from_h(hash)
    new(plan_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'planId'), 'planId'), meta: hash['_meta'])
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'sessionUpdate' => 'plan_removed', 'planId' => plan_id, '_meta' => meta }.compact
  end
end
