# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::SessionUpdate::PlanUpdate
  # @dynamic plan
  attr_reader :plan #: ACP::Types::Unstable::PlanUpdateContent::t

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs plan: ACP::Types::Unstable::PlanUpdateContent::t
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(plan:, meta: nil)
    @plan = plan
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::SessionUpdate::PlanUpdate
  def self.from_h(hash)
    new(
      plan: ACP::Types::Check.object(
        ACP::Types::Check.key(hash, 'plan'),
        'plan',
        ACP::Types::Unstable::PlanUpdateContent
      ),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'sessionUpdate' => 'plan_update', 'plan' => plan.to_h, '_meta' => meta }.compact
  end
end
