# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::SessionUpdate::SessionMessageChunk
  # @dynamic message_id
  attr_reader :message_id #: String

  # @dynamic sender_session_id
  attr_reader :sender_session_id #: String?

  # @dynamic recipient_session_id
  attr_reader :recipient_session_id #: String?

  # @dynamic content
  attr_reader :content #: ACP::Types::ContentBlock::t

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs message_id: String
  # @rbs sender_session_id: String?
  # @rbs recipient_session_id: String?
  # @rbs content: ACP::Types::ContentBlock::t
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(message_id:, content:, sender_session_id: nil, recipient_session_id: nil, meta: nil)
    @message_id = message_id
    @sender_session_id = sender_session_id
    @recipient_session_id = recipient_session_id
    @content = content
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::SessionUpdate::SessionMessageChunk
  def self.from_h(hash)
    new(
      message_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'messageId'), 'messageId'),
      sender_session_id: ACP::Types::Check.string(hash['senderSessionId'], 'senderSessionId', allow_nil: true),
      recipient_session_id: ACP::Types::Check.string(hash['recipientSessionId'], 'recipientSessionId', allow_nil: true),
      content: ACP::Types::Check.object(ACP::Types::Check.key(hash, 'content'), 'content', ACP::Types::ContentBlock),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'sessionUpdate' => 'session_message_chunk',
      'messageId' => message_id,
      'content' => content.to_h,
      'senderSessionId' => sender_session_id,
      'recipientSessionId' => recipient_session_id,
      '_meta' => meta
    }.compact
  end
end
