# frozen_string_literal: true

# Generated by bin/types from schema/schema.unstable.json. Do not edit.
# Unstable: not part of the ACP spec, may change or disappear at any point.

class ACP::Types::Unstable::SessionUpdate::SubagentUpdate
  # @dynamic session_id
  attr_reader :session_id #: String

  # @dynamic title
  attr_reader :title #: String?

  # @dynamic description
  attr_reader :description #: String?

  # @dynamic capabilities
  attr_reader :capabilities #: ACP::Types::Unstable::SubagentSessionCapabilities?

  # @dynamic state
  attr_reader :state #: ACP::Types::Unstable::StateUpdate::t?

  # @dynamic meta
  attr_reader :meta #: Hash[String, untyped]?

  # @rbs session_id: String
  # @rbs title: String?
  # @rbs description: String?
  # @rbs capabilities: ACP::Types::Unstable::SubagentSessionCapabilities?
  # @rbs state: ACP::Types::Unstable::StateUpdate::t?
  # @rbs meta: Hash[String, untyped]?
  # @rbs return: void
  def initialize(session_id:, title: nil, description: nil, capabilities: nil, state: nil, meta: nil)
    @session_id = session_id
    @title = title
    @description = description
    @capabilities = capabilities
    @state = state
    @meta = meta
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::Unstable::SessionUpdate::SubagentUpdate
  def self.from_h(hash)
    new(
      session_id: ACP::Types::Check.string(ACP::Types::Check.key(hash, 'sessionId'), 'sessionId'),
      title: ACP::Types::Check.string(hash['title'], 'title', allow_nil: true),
      description: ACP::Types::Check.string(hash['description'], 'description', allow_nil: true),
      capabilities: ACP::Types::Check.object(
        hash['capabilities'],
        'capabilities',
        ACP::Types::Unstable::SubagentSessionCapabilities,
        allow_nil: true
      ),
      state: ACP::Types::Check.object(hash['state'], 'state', ACP::Types::Unstable::StateUpdate, allow_nil: true),
      meta: hash['_meta']
    )
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    {
      'sessionUpdate' => 'subagent_update',
      'sessionId' => session_id,
      'title' => title,
      'description' => description,
      'capabilities' => capabilities&.to_h,
      'state' => state&.to_h,
      '_meta' => meta
    }.compact
  end
end
