class ACP::Transport::Stdio
  interface _Reader
    def each_line: () { (String) -> void } -> untyped
  end

  interface _Writer
    def write: (String) -> untyped
    def flush: () -> untyped
  end

  interface _Handler
    def call: (untyped params) -> result
  end
end
