# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

module ACP::Types::CreateElicitationResponse::Action
  # @rbs!
  #   type t = ACP::Types::CreateElicitationResponse::Action::Accept
  #          | ACP::Types::CreateElicitationResponse::Action::Decline
  #          | ACP::Types::CreateElicitationResponse::Action::Cancel
  #          | Hash[String, untyped]

  # @rbs hash: Hash[String, untyped]
  # @rbs return: t
  def self.from_h(hash)
    case hash['action']
    when 'accept' then ACP::Types::CreateElicitationResponse::Action::Accept.from_h(hash)
    when 'decline' then ACP::Types::CreateElicitationResponse::Action::Decline.from_h(hash)
    when 'cancel' then ACP::Types::CreateElicitationResponse::Action::Cancel.from_h(hash)
    else hash
    end
  end
end
