# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::SetSessionConfigOptionRequest::Value::Boolean
  # @dynamic value
  attr_reader :value #: bool

  # @rbs value: bool
  # @rbs return: void
  def initialize(value:)
    @value = value
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::SetSessionConfigOptionRequest::Value::Boolean
  def self.from_h(hash)
    new(value: ACP::Types::Check.boolean(ACP::Types::Check.key(hash, 'value'), 'value'))
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'type' => 'boolean', 'value' => value }
  end
end
