# frozen_string_literal: true

# Generated by bin/types from schema/schema.json. Do not edit.

class ACP::Types::SetSessionConfigOptionRequest::Value::ValueId
  # @dynamic value
  attr_reader :value #: String

  # @rbs value: String
  # @rbs return: void
  def initialize(value:)
    @value = value
    freeze
  end

  # @rbs hash: Hash[String, untyped]
  # @rbs return: ACP::Types::SetSessionConfigOptionRequest::Value::ValueId
  def self.from_h(hash)
    new(value: hash.fetch('value'))
  end

  # @rbs return: Hash[String, untyped]
  def to_h
    { 'value' => value }
  end
end
