# frozen_string_literal: true

# Decides which defs exist and which files they become: the defs reachable
# from the x-method roots, each def's file path and name, and the alias pass.
module TypeGenerator::Plan
  extend self

  def files(schema, unstable_schema = nil)
    defs = schema.fetch('$defs')
    roots = defs.select { |_, definition| definition.key?('x-method') }.keys
    stable = reachable(defs, roots, [])
             .flat_map { |name| TypeGenerator::Resolve.definition_files(TypeGenerator::Schema.new(defs), name) }
             .concat(TypeGenerator::ALIASES.map { |name, target| alias_file(name, target) })
             .sort
             .to_h
    return stable unless unstable_schema

    stable.merge(unstable_files(defs, unstable_schema))
  end

  # The unstable pass generates the defs the stable schema does not already
  # cover: defs unique to the unstable schema and shared defs whose unstable
  # form differs (extra fields or union variants). Identical defs resolve to
  # the stable classes, so the stable namespace is byte-identical whether or
  # not a caller opts in.
  def unstable_files(defs, unstable_schema)
    unstable_defs = unstable_schema.fetch('$defs')
    twins = unstable_defs.reject { |name, definition| defs[name] == definition }.keys
    roots = unstable_defs.select { |_, definition| definition.key?('x-method') }.keys
    schema = TypeGenerator::Schema.new(unstable_defs, header: TypeGenerator::UNSTABLE_HEADER, twins:)
    generated = reachable(unstable_defs, roots, [])
                .flat_map { |name| TypeGenerator::Resolve.definition_files(schema, name) }.sort.to_h
    generated.merge(opt_in_file(generated.keys))
  end

  # lib/acp/types/unstable.rb is the opt-in: the only entry into
  # lib/acp/types/unstable, which Zeitwerk ignores so nothing loads until a
  # caller requires this file.
  def opt_in_file(paths)
    requires = paths.map { |path| "require_relative '#{path.delete_suffix('.rb')}'" }
    { 'unstable.rb' => <<~RUBY }
      # frozen_string_literal: true

      # Generated by bin/types from schema/schema.unstable.json. Do not edit.
      #
      # Callers opt into the unstable types with `require 'acp/types/unstable'`.
      # Zeitwerk ignores lib/acp/types/unstable, so referencing
      # ACP::Types::Unstable without this require raises NameError.
      # These types are not part of the ACP spec and may change or disappear at
      # any point; the stable ACP::Types namespace is unaffected.

      module ACP::Types::Unstable
      end

      #{requires.join("\n")}
    RUBY
  end

  def reachable(defs, pending, seen)
    return seen if pending.empty?

    name, *rest = pending
    return reachable(defs, rest, seen) if seen.include?(name)

    reachable(defs, rest + refs(defs.fetch(name)), seen + [name])
  end

  def refs(node)
    case node
    when Hash then node.flat_map { |key, value| key == '$ref' ? [ref_name(value)] : refs(value) }
    when Array then node.flat_map { |value| refs(value) }
    else []
    end
  end

  def ref_name(ref) = ref.delete_prefix('#/$defs/')

  def const(name) = "#{TypeGenerator::NAMESPACE}::#{name}"

  def path(const)
    "#{const.delete_prefix("#{TypeGenerator::NAMESPACE}::").split('::').map { |part| snake(part) }.join('/')}.rb"
  end

  def snake(name) = name.delete_prefix('_').gsub(/([a-z\d])([A-Z])/, '\1_\2').downcase

  def camel(name) = name.split(/[^a-zA-Z\d]/).map(&:capitalize).join

  def alias_file(name, target)
    rbs = "# @rbs!\n#   class #{const(name)} = #{const(target)}\n"
    [path(const(name)), "#{TypeGenerator::HEADER}\n#{rbs}\n#{const(name)} = #{const(target)}\n"]
  end
end
