# frozen_string_literal: true

# Decides which defs exist and which files they become: the defs reachable
# from the x-method roots, each def's file path and name, and the alias pass.
module TypeGenerator::Plan
  extend self

  def files(schema, unstable_schema = nil)
    defs = schema.fetch('$defs')
    roots = defs.select { |_, definition| definition.key?('x-method') }.keys
    pass = TypeGenerator::Schema.new(defs)
    generated, = generate(pass, roots)
    stable = generated
             .merge(TypeGenerator::ALIASES.to_h { |name, target| alias_file(pass, name, pass.const(target)) })
             .sort.to_h
    return stable unless unstable_schema

    stable.merge(unstable_files(defs, unstable_schema))
  end

  # The unstable pass generates the defs the stable schema does not already
  # cover: defs unique to the unstable schema and shared defs whose unstable
  # form differs (extra fields or union variants). Identical defs resolve to
  # the stable classes, so the stable namespace is byte-identical whether or
  # not a caller opts in.
  def unstable_files(defs, unstable_schema)
    unstable_defs = unstable_schema.fetch('$defs')
    twins = unstable_defs.reject { |name, definition| defs[name] == definition }.keys
    roots = unstable_defs.select { |_, definition| definition.key?('x-method') }.keys
    schema = TypeGenerator::Schema.new(unstable_defs, header: TypeGenerator::UNSTABLE_HEADER, twins:)
    generated, aliases = generate(schema, roots)
    generated.merge(opt_in_file(generated.keys, aliases))
  end

  # lib/acp/types/unstable.rb is the opt-in: the only entry into
  # lib/acp/types/unstable, which Zeitwerk ignores so nothing loads until a
  # caller requires this file. Aliases are required after the classes they
  # alias: nothing autoloads here, so constant assignment evaluates its target.
  def opt_in_file(paths, aliases)
    classes, alias_files = paths.partition { |path| !aliases.include?(path) }
    requires = [*classes, *alias_files].map { |path| "require_relative '#{path.delete_suffix('.rb')}'" }
    { 'unstable.rb' => <<~RUBY }
      # frozen_string_literal: true

      # Generated by bin/types from schema/schema.unstable.json. Do not edit.
      #
      # Callers opt into the unstable types with `require 'acp/types/unstable'`.
      # Zeitwerk ignores lib/acp/types/unstable, so referencing
      # ACP::Types::Unstable without this require raises NameError.
      # These types are not part of the ACP spec and may change or disappear at
      # any point; the stable ACP::Types namespace is unaffected.

      module ACP::Types::Unstable
      end

      #{requires.join("\n")}
    RUBY
  end

  # One pass's file set: a class file per def a normal edge reaches, an alias
  # file per def a single variant class subsumes — replacing only that def's
  # own class file, since its nested union modules are still referenced — and
  # nothing for a def several variant classes subsume (no single alias target)
  # or that the stable pass already emitted. Returns the files plus the paths
  # of the alias files among them.
  def generate(schema, roots)
    seen = reachable(schema, roots.map { |name| [name, :normal] }, {})
    subsumed = seen.filter_map { |name, status| [name, status.first] if status.is_a?(Array) && status.size == 1 }.to_h
    defs = schema.with_subsumed(subsumed)
    files = seen.flat_map do |name, status|
      next [] unless schema.generated?(name)
      next TypeGenerator::Resolve.definition_files(defs, name) if status == :normal

      kept = TypeGenerator::Resolve.definition_files(defs, name).reject { |path, _| path == path(schema.const(name)) }
      kept.push(alias_file(schema, name, subsumed[name])) if subsumed[name]
      kept
    end.sort.to_h
    aliases = subsumed.filter_map { |name, _| path(schema.const(name)) if schema.generated?(name) }.sort
    [files, aliases]
  end

  # Walks the defs out from the roots, classifying each by how it is reached:
  # :normal keeps its own class, while a subsuming variant option's allOf ref
  # hands the def to the variant classes claiming it — collected as an array
  # of their constants. A def a normal edge also reaches is never subsumed.
  # Traversal continues through subsumed defs: their fields inline into the
  # variant classes, so refs inside them still generate classes.
  def reachable(defs, pending, seen)
    return seen if pending.empty?

    ((name, edge), *rest) = pending
    prior = seen[name]
    return reachable(defs, rest, seen) if prior == :normal
    return reachable(defs, rest, seen.merge(name => edge == :normal ? :normal : prior | edge)) if prior

    reachable(defs, rest + edges(defs, name), seen.merge(name => edge))
  end

  # A def's outgoing edges as [name, edge] pairs: :normal for every ref in
  # the def, and a claimed constant for each def its own variant classes
  # subsume.
  def edges(defs, name)
    definition = defs.fetch(name)
    plain_refs(definition).map { |ref| [ref, :normal] } +
      subsumed_edges(defs, name).map { |ref, variant| [ref, [variant]] }
  end

  # A subsuming option's allOf ref is not a normal edge — the refed def's
  # fields inline into the variant class — but the option's own properties
  # keep theirs.
  def plain_refs(node)
    case node
    when Hash
      node = node.except('allOf') if TypeGenerator::Unions.subsumes_ref?(node)
      node.flat_map { |key, value| key == '$ref' ? [ref_name(value)] : plain_refs(value) }
    when Array then node.flat_map { |value| plain_refs(value) }
    else []
    end
  end

  def subsumed_edges(defs, name)
    union = TypeGenerator::Resolve.union_const(defs, name)
    union ? TypeGenerator::Unions.variant_refs(defs, union, defs.fetch(name)) : []
  end

  def ref_name(ref) = ref.delete_prefix('#/$defs/')

  def path(const)
    "#{const.delete_prefix("#{TypeGenerator::NAMESPACE}::").split('::').map { |part| snake(part) }.join('/')}.rb"
  end

  def snake(name) = name.delete_prefix('_').gsub(/([a-z\d])([A-Z])/, '\1_\2').downcase

  def camel(name) = name.split(/[^a-zA-Z\d]/).map(&:capitalize).join

  def alias_file(schema, name, target)
    rbs = "# @rbs!\n#   class #{schema.const(name)} = #{target}\n"
    [path(schema.const(name)), "#{schema.header}\n#{rbs}\n#{schema.const(name)} = #{target}\n"]
  end
end
