# frozen_string_literal: true

require 'test_helper'
require_relative 'fixtures'

describe TypeGenerator::Plan do
  it 'emits exactly the defs reachable from the x-method roots, plus the aliases' do
    assert_equal %w[
      any_list.rb
      blend.rb
      blend/plain.rb
      blend/tagged.rb
      choice.rb
      choice/read.rb
      choice/write.rb
      mode.rb
      note.rb
      session_list_request.rb
      session_list_response.rb
      session_load_request.rb
      session_new_request.rb
      session_prompt_request.rb
      step.rb
      widget_request.rb
    ],
                 FixtureSchemas::FILES.keys
  end

  it 'does not emit defs no other file references' do
    refute_includes FixtureSchemas::FILES.keys, 'orphan.rb'
  end

  it 'emits aliases as reassignments of their target constants' do
    assert_equal <<~RUBY, FixtureSchemas::FILES.fetch('session_list_request.rb')
      # frozen_string_literal: true

      # Generated by bin/types from schema/schema.json. Do not edit.

      # @rbs!
      #   class ACP::Types::SessionListRequest = ACP::Types::ListSessionsRequest

      ACP::Types::SessionListRequest = ACP::Types::ListSessionsRequest
    RUBY
  end

  it 'regenerates only the defs the unstable schema changes or adds' do
    assert_equal %w[unstable.rb unstable/gadget.rb unstable/step.rb],
                 (FixtureSchemas::ALL_FILES.keys - FixtureSchemas::FILES.keys).sort
  end

  it 'routes defs whose unstable form is identical to the stable classes' do
    assert_equal %w[unstable/gadget unstable/step],
                 FixtureSchemas::ALL_FILES.fetch('unstable.rb').scan(/require_relative '(.+)'/).flatten.sort
  end

  it 'generates changed twins under the unstable namespace' do
    assert_includes FixtureSchemas::ALL_FILES.fetch('unstable/step.rb'), 'class ACP::Types::Unstable::Step'
  end
end
