# frozen_string_literal: true

require 'test_helper'
require_relative 'fixtures'

describe TypeGenerator::Unions do
  it 'dispatches a discriminated union on its tag' do
    assert_equal <<~RUBY, FixtureSchemas::FILES.fetch('choice.rb')
      # frozen_string_literal: true

      # Generated by bin/types from schema/schema.json. Do not edit.

      module ACP::Types::Choice
        # @rbs!
        #   type t = ACP::Types::Choice::Read
        #          | ACP::Types::Choice::Write
        #          | Hash[String, untyped]

        # @rbs hash: Hash[String, untyped]
        # @rbs return: t
        def self.from_h(hash)
          case hash['kind']
          when 'read' then ACP::Types::Choice::Read.from_h(hash)
          when 'write' then ACP::Types::Choice::Write.from_h(hash)
          else hash
          end
        end
      end
    RUBY
  end

  it 'routes the untagged variant through the nil branch' do
    assert_equal <<~RUBY, FixtureSchemas::FILES.fetch('blend.rb')
      # frozen_string_literal: true

      # Generated by bin/types from schema/schema.json. Do not edit.

      module ACP::Types::Blend
        # @rbs!
        #   type t = ACP::Types::Blend::Tagged
        #          | ACP::Types::Blend::Plain
        #          | Hash[String, untyped]

        # @rbs hash: Hash[String, untyped]
        # @rbs return: t
        def self.from_h(hash)
          case hash['type']
          when 'tagged' then ACP::Types::Blend::Tagged.from_h(hash)
          when nil then ACP::Types::Blend::Plain.from_h(hash)
          else hash
          end
        end
      end
    RUBY
  end

  it 'stamps the tag value into a tagged variant to_h' do
    assert_equal <<~RUBY, FixtureSchemas::FILES.fetch('blend/tagged.rb')
      # frozen_string_literal: true

      # Generated by bin/types from schema/schema.json. Do not edit.

      class ACP::Types::Blend::Tagged
        # @rbs return: void
        def initialize
          freeze
        end

        # @rbs _hash: Hash[String, untyped]
        # @rbs return: ACP::Types::Blend::Tagged
        def self.from_h(_hash)
          new
        end

        # @rbs return: Hash[String, untyped]
        def to_h
          { 'type' => 'tagged' }
        end
      end
    RUBY
  end

  it 'keys array-union branches on the distinguishing required keys' do
    assert_equal <<~RUBY, FixtureSchemas::FILES.fetch('any_list.rb')
      # frozen_string_literal: true

      # Generated by bin/types from schema/schema.json. Do not edit.

      module ACP::Types::AnyList
        # @rbs!
        #   type t = Array[ACP::Types::Step]
        #          | Array[ACP::Types::Note]
        #          | Array[Hash[String, untyped]]

        # @rbs items: Array[Hash[String, untyped]]
        # @rbs return: t
        def self.from_a(items)
          if items.all? { |item| item.key?('index') }
            items.each_with_index.map do |item, index|
              ACP::Types::Check.object(item, [index], ACP::Types::Step)
            end #: Array[ACP::Types::Step]
          elsif items.all? { |item| item.key?('text') }
            items.each_with_index.map do |item, index|
              ACP::Types::Check.object(item, [index], ACP::Types::Note)
            end #: Array[ACP::Types::Note]
          else
            items
          end
        end
      end
    RUBY
  end

  it 'collects the const values as enum constants' do
    assert_equal <<~RUBY, FixtureSchemas::FILES.fetch('mode.rb')
      # frozen_string_literal: true

      # Generated by bin/types from schema/schema.json. Do not edit.

      module ACP::Types::Mode
        READ = 'read'
        WRITE = 'write'
        DELETE = 'delete'
      end
    RUBY
  end
end
